; RAM layout from ram_map.json (RetroAchievements Code Notes).
; Regenerated by tools/disasm.py; do not edit by hand.

SECTION "HRAM $ff8a", HRAM[$ff8a]

; [8-bit] SCY shadow, applied in VBlank
hScrollY:: db

; [8-bit] SCX shadow, applied in VBlank
hScrollX:: db

; [8-bit] Increments every VBlank
hVBlankCounter:: db

; [8-bit] Set at end of VBlank handler; AdvanceFrame waits on it
hVBlankOccurred:: db

; [8-bit] Nonzero = wDebugTextBuffer needs re-upload
hDebugTextDirty:: db

; [8-bit] Nonzero when wFrameTasks is consistent; cleared while the list is mutated so the frame hook skips it
hFrameTasksReady:: db

; [8-bit] Player Input Flags
;
; Bit 7 - Down
; Bit 6 - Up
; Bit 5 - Left
; Bit 4 - Right
; Bit 3 - Start
; Bit 2 - Select
; Bit 1 - B
; Bit 0 - A
hPlayerInputFlags:: db

; [8-bit] Buttons newly pressed this frame (same bit layout as hPlayerInputFlags)
hInputPressed:: db

; [8-bit] Buttons held for key-repeat tracking
hInputRepeatButtons:: db

; [8-bit] Frames until next key-repeat fire
hInputRepeatTimer:: db

; [8-bit] Buttons newly pressed this frame (raw, before repeat processing)
hInputRisingEdge:: db

; [8-bit] Shadow of the current ROM bank (written together with the MBC register at $2000)
hRomBank:: db

; [8-bit] Shadow of the current WRAM bank (last value written to rSVBK); match engine swaps banks 4-7 for per-character data
hWramBank:: db

; [8-bit] Shadow of the current SRAM bank (always written together with the MBC RAM-bank register at $4000)
hSramBank:: db

; [8-bit] 1 = VBlank switches BG map to the debug console view
hShowDebugConsole:: db

; [8-bit] Nonzero = VRAM copy / tile-write queues have pending entries
hVRAMQueueDirty:: db
	ds 1

; [8-bit] Write offset into the OAM shadow buffer (max $a0)
hSpriteQueueIndex:: db

; [8-bit] OAM shadow offset where per-frame sprites start (entries below persist)
hSpriteQueueBase:: db

; [8-bit] Bit 0 = BG palettes dirty, bit 1 = OBJ palettes dirty
hPaletteDirtyFlags:: db

; [8-bit] Debug pause/frame-step mode (0 = off, 1-3)
hDebugStepMode:: db
	ds 1

; [8-bit] Peak LY at end-of-frame (frame time meter shown on debug console)
hPeakLY:: db

; [8-bit] Frames until hPeakLY decays
hPeakLYFrames:: db

; [8-bit] Bit 0 = fading out, bit 1 = fading in, bit 7 = fade to white
hFadeState:: db

; [8-bit] Fade step per frame
hFadeSpeed:: db

; [8-bit] Fade progress counter (starts at $7c)
hFadeCounter:: db
	ds 1

; [8-bit] Key-repeat interval reload value
hInputRepeatDelay:: db

; [8-bit] Sign scratch for signed multiply/divide wrappers
hMathSign:: db

; [32-bit] Full 32-bit product from MulHLByDE
hMulResult:: ds 4
	ds 12

; [8-bit] Nonzero = row in wBGRowBlitBuffer awaits VBlank blit
hBGRowBlitPending:: db

; [8-bit] Nonzero = column in wBGColumnBlitBuffer awaits VBlank blit
hBGColumnBlitPending:: db

; [8-bit] Set when the slow column blit ran this VBlank (skips VRAM queue)
hBGColumnBlitDone:: db
	ds 1

; [8-bit] Nonzero = screen currently faded out
hFadedOut:: db
	ds 3

; [8-bit] Last byte received over the serial link (captured from rSB in the serial interrupt)
hLinkRxByte:: db

; [8-bit] Next byte to transmit over the serial link (copied to rSB)
hLinkTxByte:: db

; [8-bit] Serial link state/role (0 = idle, 1/2 = connected roles); gates the encode/decode paths
hLinkState:: db
	ds 5

; [8-bit] Serial link exchange/frame counter; increments per exchange and caps at 8
hLinkCounter:: db
	ds 4

; [8-bit] Jingle sound id currently overriding BGM (0 = none)
hActiveJingle:: db

; [8-bit] Music (0x00 - on, 0x01 - off)
hMusic:: db
	ds 45

; [16-bit] RNG state (x*5 + $3573 per VBlank)
hRandomSeed:: dw

; [8-bit] 1 = running on Game Boy Color hardware
hIsCGB:: db
