; RAM layout from ram_map.json (RetroAchievements Code Notes).
; Regenerated by tools/disasm.py; do not edit by hand.

SECTION "HRAM $ff8a", HRAM[$ff8a]

; [8-bit] SCY shadow, applied in VBlank
hScrollY:: db

; [8-bit] SCX shadow, applied in VBlank
hScrollX:: db

; [8-bit] Increments every VBlank
hVBlankCounter:: db

; [8-bit] Set at end of VBlank handler; AdvanceFrame waits on it
hVBlankOccurred:: db

; [8-bit] Nonzero = wDebugTextBuffer needs re-upload
hDebugTextDirty:: db

; [8-bit] Nonzero when wFrameTasks is consistent; cleared while the list is mutated so the frame hook skips it
hFrameTasksReady:: db

; [8-bit] Player Input Flags
;
; Bit 7 - Down
; Bit 6 - Up
; Bit 5 - Left
; Bit 4 - Right
; Bit 3 - Start
; Bit 2 - Select
; Bit 1 - B
; Bit 0 - A
hPlayerInputFlags:: db

; [8-bit] Buttons newly pressed this frame (same bit layout as hPlayerInputFlags)
hInputPressed:: db

; [8-bit] Buttons held for key-repeat tracking
hInputRepeatButtons:: db

; [8-bit] Frames until next key-repeat fire
hInputRepeatTimer:: db

; [8-bit] Buttons newly pressed this frame (raw, before repeat processing)
hInputRisingEdge:: db

; [8-bit] Shadow of the current ROM bank (written together with the MBC register at $2000)
hRomBank:: db

; [8-bit] Shadow of the current WRAM bank (last value written to rSVBK); match engine swaps banks 4-7 for per-character data
hWramBank:: db

; [8-bit] Shadow of the current SRAM bank (always written together with the MBC RAM-bank register at $4000)
hSramBank:: db

; [8-bit] 1 = VBlank switches BG map to the debug console view
hShowDebugConsole:: db

; [8-bit] Nonzero = VRAM copy / tile-write queues have pending entries
hVRAMQueueDirty:: db
	ds 1

; [8-bit] Write offset into the OAM shadow buffer (max $a0)
hSpriteQueueIndex:: db

; [8-bit] OAM shadow offset where per-frame sprites start (entries below persist)
hSpriteQueueBase:: db

; [8-bit] Bit 0 = BG palettes dirty, bit 1 = OBJ palettes dirty
hPaletteDirtyFlags:: db

; [8-bit] Debug pause/frame-step mode (0 = off, 1-3)
hDebugStepMode:: db
	ds 1

; [8-bit] Peak LY at end-of-frame (frame time meter shown on debug console)
hPeakLY:: db

; [8-bit] Frames until hPeakLY decays
hPeakLYFrames:: db

; [8-bit] Bit 0 = fading out, bit 1 = fading in, bit 7 = fade to white
hFadeState:: db

; [8-bit] Fade step per frame
hFadeSpeed:: db

; [8-bit] Fade progress counter (starts at $7c)
hFadeCounter:: db
	ds 1

; [8-bit] Key-repeat interval reload value
hInputRepeatDelay:: db

; [8-bit] Sign scratch for signed multiply/divide wrappers
hMathSign:: db

; [32-bit] Full 32-bit product from MulHLByDE
hMulResult:: ds 4
	ds 12

; [8-bit] Nonzero = row in wBGRowBlitBuffer awaits VBlank blit
hBGRowBlitPending:: db

; [8-bit] Nonzero = column in wBGColumnBlitBuffer awaits VBlank blit
hBGColumnBlitPending:: db

; [8-bit] Set when the slow column blit ran this VBlank (skips VRAM queue)
hBGColumnBlitDone:: db
	ds 1

; [8-bit] Nonzero = screen currently faded out
hFadedOut:: db
	ds 3

; [8-bit] Last byte received over the serial link (captured from rSB in the serial interrupt)
hLinkRxByte:: db

; [8-bit] Next byte to transmit over the serial link (copied to rSB)
hLinkTxByte:: db

; [8-bit] Serial link state/role (0 = idle, 1/2 = connected roles); gates the encode/decode paths
hLinkState:: db
	ds 5

; [8-bit] Serial link exchange/frame counter; increments per exchange and caps at 8
hLinkCounter:: db
	ds 4

; [8-bit] Jingle sound id currently overriding BGM (0 = none)
hActiveJingle:: db

; [8-bit] Music (0x00 - on, 0x01 - off)
hMusic:: db
	ds 1

; Shared HRAM scratch pool: the serial-link input path, the bank-0
; sound driver, the sprite queue and the story actor engine reuse the same
; bytes (they never run concurrently). Only proven consumers are named;
; sites outside every variant's scope keep the numeric address.
UNION
; serial-link input slots (default: link-aware match/menu code in many banks)
	ds 3
; [8-bit] Effective external input byte produced by SerialDecodeInput (local/remote merged per link role); also the scripted-input feed for demo/CPU-driven characters
hLinkInput:: db
; [8-bit] Input byte decoded from the last received link frame
hLinkRemoteInput:: db
; [8-bit] Buffered remote input from the previous exchange (double-buffered on the slave side)
hLinkRemoteInputBuf:: db
	ds 26
NEXTU
; sound driver (bank 0, $3373-$3ddf)
; [16-bit] Current channel's script/state pointer, copied from the channel struct each update (borrows the sprite-queue bytes; RunSoundEngine save/restores them)
hSndScriptPtr:: dw
; [8-bit] Channel type in the low 2 bits (0=square1/sweep, 1=square2, 2=wave, 3=noise); high nibble carries the vibrato depth / note-length index
hSndChannelType:: db
; [16-bit] Pointer to the current channel's note/command data
hSndDataPtr:: dw
; [8-bit] ROM bank of the current channel's data (loaded into hRomBank/$2000)
hSndDataBank:: db
; [8-bit] Tone control: bits 6-7 duty, bit 4 flag, low nibble = note-length increment paired with hSndLengthAccum
hSndToneCtrl:: db
; [8-bit] Fractional note-length accumulator; hSndToneCtrl's low nibble is added each update and carries a step at $10
hSndLengthAccum:: db
; [8-bit] Current channel volume/envelope value (high nibble = level; envelope steps by $10)
hSndVolume:: db
; [8-bit] Portamento/glide countdown; while non-zero the channel slides toward the target note instead of advancing the script (cmd $a7)
hSndPortamentoTimer:: db
; [8-bit] Wave-pattern id for the wave channel (compared with wSndLoadedWaveId); reused as a note/instrument byte on the other channels
hSndWaveId:: db
; [8-bit] Signed note offset/detune applied when a note is triggered (bit 7 = active); set by cmd $a4
hSndNoteOffset:: db
; [8-bit] Per-channel transpose added to note ids (cmd $a9 $f0/$f1/$ff)
hSndTranspose:: db
; [8-bit] Instrument-envelope sweep speed (high nibble); set with hSndEnvLength by cmd $c0-$cf and consumed by TickInstrumentEnvelope
hSndEnvRate:: db
; [8-bit] Instrument-envelope sweep length/target; on the wave channel it doubles as a note-length byte
hSndEnvLength:: db
; [8-bit] Current instrument-envelope position, advanced toward hSndEnvLength each update
hSndEnvPos:: db
; [8-bit] Volume-slide state (bit 7 direction, remaining steps in the low bits); set by cmd $b0-$df, ticked by TickVolumeSlide
hSndVolSlide:: db
; [8-bit] Volume-slide period reload value
hSndVolSlideReload:: db
; [8-bit] Volume-slide countdown to the next step
hSndVolSlideTimer:: db
; [8-bit] Base period low byte of the current note, saved as the vibrato centre (TickVibrato offsets from it)
hSndPeriodLo:: db
; [8-bit] Shadow of NRx4 (period high + control); bit 5 ($20) is a software note-on marker used to tell whether a note is sounding
hSndPeriodHi:: db
; [8-bit] Echo state: low nibble echo depth (ScaleEchoVolume), high nibble saved volume level; set by cmd $aa
hSndEcho:: db
; [8-bit] This channel's rAUDTERM left/right output bits, merged into wSndPanShadow; set/swapped by cmd $a5
hSndPanMask:: db
; [8-bit] Note-length reload value (cmd $a3)
hSndNoteLenReload:: db
; [8-bit] Note-length countdown; suppresses vibrato/effects until it reaches 0
hSndNoteLenTimer:: db
; [8-bit] Instrument selector: high nibble picks the wave pattern / envelope-pointer table, low nibble the envelope sequence; set by cmd $a8
hSndInstrument:: db
; [8-bit] Echo repeat counter (cmd $aa); note this HRAM byte is hActorPtr under the story-actor variant
hSndEchoTimer:: db
; [8-bit] Echo control: high nibble enable/count, low nibble note offset
hSndEchoCtrl:: db
; [8-bit] Script loop counter (cmd $ac)
hSndLoopCount:: db
; [16-bit] Saved script pointer for the active loop (cmd $ac/$ad)
hSndLoopReturnPtr:: dw
; [8-bit] Non-zero when the current step is a rest/tie; suppresses the volume envelope in ApplyChannelEnvelope
hSndRestFlag:: db
NEXTU
; sprite queue (bank 0, $2ced-$2d9f)
; [8-bit] Screen Y origin of the multi-sprite block being queued (QueueSprite32x32)
hSpriteBlitY:: db
; [8-bit] Screen X origin of the multi-sprite block being queued
hSpriteBlitX:: db
NEXTU
; story actor engine (banks $04/$05/$0a)
	ds 26
; [16-bit] Pointer to the actor struct currently being processed (stashed around GetActorStateAddr / StepActorScript)
hActorPtr:: dw
ENDU

	ds 12

; [16-bit] RNG state (x*5 + $3573 per VBlank)
hRandomSeed:: dw

; [8-bit] 1 = running on Game Boy Color hardware
hIsCGB:: db
