; RAM layout from ram_map.json (RetroAchievements Code Notes).
; Regenerated by tools/disasm.py; do not edit by hand.

SECTION "HRAM $ff8f", HRAM[$ff8f]

; [8-bit] Nonzero when wFrameTasks is consistent; cleared while the list is mutated so the frame hook skips it
hFrameTasksReady:: db

; [8-bit] Player Input Flags
;
; Bit 7 - Down
; Bit 6 - Up
; Bit 5 - Left
; Bit 4 - Right
; Bit 3 - Start
; Bit 2 - Select
; Bit 1 - B
; Bit 0 - A
hPlayerInputFlags:: db

; [8-bit] Buttons newly pressed this frame (same bit layout as hPlayerInputFlags)
hInputPressed:: db
	ds 3

; [8-bit] Shadow of the current ROM bank (written together with the MBC register at $2000)
hRomBank:: db

; [8-bit] Shadow of the current WRAM bank (last value written to rSVBK); match engine swaps banks 4-7 for per-character data
hWramBank:: db
	ds 55

; [8-bit] Music (0x00 - on, 0x01 - off)
hMusic:: db
