; RAM layout from ram_map.json (RetroAchievements Code Notes).
; Regenerated by tools/disasm.py; do not edit by hand.

SECTION "SRAM $a020", SRAM[$a020]

; Battery-save header fields (SRAM bank 0), owned by the bank $03 save
; engine; scoped so unrelated $a0xx literals in other banks stay numeric
UNION
; save engine (bank $03)
; [16 bytes] "CAMELOTGBTENNIS\0" signature (ROM copy at SaveSignature, 03:47e9)
sSaveSignature:: ds 16
; [16-bit LE] byte-sum of $a038-$a76f (version byte + block directory)
sSaveMasterChecksum:: dw
	ds 6
; [8-bit] save layout version byte, always $71; first byte covered by the master checksum
sSaveFormatVersion:: db
	ds 6
ENDU

	ds 3

; [Lower4] Mario Minigame Completion Flags (1/4)
;
; Bit 3 - Boo Blast Level 1
; Bit 2 - Boo Blast Level 2
; Bit 1 - Boo Blast Level 3
; Bit 0 - Shooting Star Level 1
sMarioMinigameCompletionFlags1:: db

; [8-bit] Mario Minigame Completion Flags (2/4)
;
; Bit 7 - Shooting Star Level 2
; Bit 6 - Shooting Star Level 3
; Bit 5 - Perfect Shot Level 1
; Bit 4 - Perfect Shot Level 2
; Bit 3 - Perfect Shot Level 3
; Bit 2 - Target Shot Level 1
; Bit 1 - Target Shot Level 2
; Bit 0 - Target Shot Level 3
sMarioMinigameCompletionFlags2:: db
	ds 1

; [8-bit] Mario Minigame Completion Flags (3/4)
;
; Bit 7 - Fruit Fantasy Level 1
; Bit 6 - Fruit Fantasy Level 2
; Bit 5 - Fruit Fantasy Level 3
; Bit 4 - Banana Bunch Level 1
; Bit 3 - Banana Bunch Level 2
; Bit 2 - Banana Bunch Level 3
; Bit 1 - Treasure Box Level 1
; Bit 0 - Treasure Box Level 2
sMarioMinigameCompletionFlags3:: db

; [8-bit] Mario Minigame Completion Flags (4/4)
;
; Bit 7 - Treasure Box Level 3
; Bit 6 - Medallion Match Level 1
; Bit 5 - Medallion Match Level 2
; Bit 4 - Medallion Match Level 3
; Bit 3 - Two-On-One Level 1
; Bit 2 - Two-On-One Level 2
; Bit 1 - Two-On-One Level 3
sMarioMinigameCompletionFlags4:: db

; [8-bit] Court Unlock Flags
;
; Bit 6 - Star Court
; Bit 5 - Castle Court
; Bit 4 - Tropics Court
; Bit 3 - Jungle Court
; Bit 2 - Warehouse Court
sCourtUnlockFlags:: db
	ds 24

; Save block directory: 113 16-byte entries (see docs/save_format.md);
; entry = valid, SRAM bank, offset, length, checksum, tag
UNION
; save engine (bank $03)
; [113 x 16 bytes] block directory; +0 valid, +1 SRAM bank, +2 offset word, +4 length word, +6 checksum word, +8 tag (hi,lo)
sSaveBlockDirectory:: ds 1808
ENDU
