; RAM layout from ram_map.json (RetroAchievements Code Notes).
; Regenerated by tools/disasm.py; do not edit by hand.

SECTION "WRAM0 $c0a0", WRAM0[$c0a0]

; [80 bytes] VBlank VRAM copy queue: 10 x 8-byte entries [rom bank, wram bank, size hi, size lo, vbk, dest hi, dest lo, src?]; processed by ProcessVRAMCopyQueues
wVRAMCopyQueue:: ds 80

; [4 bytes] Play timer: frames (0-59), seconds, minutes, hours (caps at 99)
wGameTimer:: ds 4
	ds 12

; [64 bytes] Live BG palette buffer, uploaded in VBlank when hPaletteDirtyFlags bit 0 set
wBGPalettes:: ds 64

; [64 bytes] Live OBJ palette buffer, uploaded in VBlank when hPaletteDirtyFlags bit 1 set
wOBJPalettes:: ds 64

; [64 bytes] VBlank single-tile write queue: 16 x 4-byte entries [addr hi, addr lo, tile (VBK0), attr (VBK1)]
wTileWriteQueue:: ds 64

; [64 bytes] Frame task list: 4-byte records [id, ptr lo, ptr hi, rom bank] of banked callbacks run each frame (RegisterFrameTask / ClearFrameTasks)
wFrameTasks:: ds 64

; [128 bytes] Master palette copy (BG+OBJ); fades scale this into wBGPalettes/wOBJPalettes
wMasterPalettes:: ds 128

; [8-bit] Story Mode - Current Location
;
; 0x00 - Not in Story Mode
; 0x05 - Academy Main Building
; 0x06 - Academy Wing
; 0x07 - Courtyard
; 0x08 - Restaurant Plaza
; 0x09 - Dorm Entrance
; 0x0a - Dormitory
; 0x0b, 0x0c - Junior Class Court
; 0x0d - Restaurant
; 0x0e - Cafeteria
; 0x0f - Training Court
; 0x10 - Senior Class Court
; 0x11 - Training Center
; 0x12 - Tennis Machine Room
; 0x13 - Wall Practice Room
; 0x14 - Academy Entrance
; 0x15 - Tournament Courtyard
; 0x16 - Court #1
; 0x17 - Court #2
; 0x18 - Center Court
; 0x19 - Tournament
; 0x1a - Awards Ceremony
; 0x1b - Plane Cutscene
; 0x1c - Castle Court
; 0x1d - Peach's Castle
; 0x1e-0x29 - Final Credits Sequence
wStoryModeCurrentLocation:: db
	ds 20

; [8-bit] Story Mode - entry point / spawn-door ID for the location being loaded; $ff = none (keep saved player position). LoadStoryEntryPointRecord searches the location's entry table with it
wStoryModeEntryPoint:: db

; [5 bytes] Story Mode - player spawn/return buffer: X (16-bit), Y (16-bit), facing; filled from the matched entry-point record or backed up from wStoryModePlayersXPosition before a submode
wStoryModeSpawnPosition:: ds 5
	ds 6

; [8-bit] Story Mode - nonzero requests leaving the current location loop (RunLocationExit + reload); one of the event-request flags at $c2a0-$c2a5 cleared by ClearStoryEventRequests
wStoryModeExitLocationRequest:: db
	ds 18

; [16-bit] Water Sprite Minigame - Timer (Frames)
wWaterSpriteMinigameTimer:: dw

; [16-bit] Water Sprite Minigame - Swing Count
wWaterSpriteMinigameSwingCount:: dw
	ds 2

; [8-bit] Water Sprite Minigame Flag (0x17 when in minigame)
wWaterSpriteMinigameFlag:: db
	ds 21

; [16-bit] Story Mode - Player's X Position
wStoryModePlayersXPosition:: dw

; [16-bit] Story Mode - Player's Y Position
wStoryModePlayersYPosition:: dw
	ds 1

; [8-bit] Story Mode - nonzero shows the location-name popup after fade-in (derived from wStoryModeEntryPoint != $ff; name pointer at $c2d6/$c2d7)
wStoryModeShowLocationName:: db
	ds 74

; [16-bit] BG scroll-buffer camera X (tiles<<3?)
wCameraX:: dw

; [16-bit] BG scroll-buffer camera Y
wCameraY:: dw
	ds 2

; [16-bit] Tilemap address for the queued BG row blit
wBGRowBlitDest:: dw

; [8-bit] Tilemap column for the queued BG column blit
wBGColumnBlitX:: db
	ds 5

; [8-bit] Current story-cutscene scene index; indexes SceneGfxSlotTable (index*16) and drives LoadAndDisplayScene / InitSceneTileAnimations
wCurrentScene:: db
	ds 15

; [8-bit] Current BGM
;
; 0x00 - Silence
; 0x01 - Intro Cutscene
; 0x02 - Title Screen
; 0x03 - Main Menu
; 0x04 - Status Screen
; 0x05 - Dictionary
; 0x06 - Exhibition Match
; 0x07 - Unused
; 0x08 - Mario Minigame Screen
; 0x09 - You Win
; 0x0a - You Lose
; 0x0b - Earning EXP
; 0x0c - Distributing EXP
; 0x0d - Distributing Stats
; 0x0e - Tiebreaker
; 0x0f - Set/Match Point
; 0x10 - Game Point
; 0x11 - Star Court
; 0x12 - Castle Court/Peach's Castle
; 0x13 - Tropic Court/Fruit Fantasy
; 0x14 - Warehouse Court/Treasure Box
; 0x15 - Two-on-One
; 0x16 - Jungle Court/Banana Bunch
; 0x17 - Unused
; 0x18 - Unused
; 0x19 - Shooting Star/Target Shot/Medallion Match
; 0x1a - Academy Main Building
; 0x1b - Story Mode Outdoors
; 0x1c - Dormitory
; 0x1d - Story Mode Indoors
; 0x1e - Tennis Machine
; 0x1f - Wall Practice
; 0x20 - Practice Match
; 0x21 - Junior Ranking Match
; 0x22 - Senior Ranking Match
; 0x23 - Varsity Ranking Match
; 0x24 - Training Court Match
; 0x25 - Training Court Practice
; 0x26 - Island Open Beginning Rounds
; 0x27 - Island Open Semifinals
; 0x28 - Island Open Finals
; 0x29 - Dream Match
; 0x2a - Unused
; 0x2b - Island Open Congratulations
; 0x2c - Credits
; 0x2d - The End
; 0x2e - Done For The Day
; 0x2f - Level Up
; 0x30 - High Score
; 0x31 - Exhibition Match Start
; 0x32 - Story Match Start
wCurrentBGM:: db
	ds 45

; [8-bit] Active story save-slot index (0-2); selects which SRAM story slot CheckStorySlot / SaveStorySlotWithTimer operate on
wCurrentStorySlot:: db
	ds 9

; [8-bit] Minigame Level (0x00-0x03)
;
; Value is current minigame level - 1
wMinigameLevel:: db
	ds 48

; [8-bit] High byte of current OAM shadow buffer ($c0/$c5); toggled each frame, OAM DMA source
wSpriteBufferPage:: db
	ds 10

; [8-bit] BG attribute written for window-frame cells ($80 = BG priority)
wWindowFrameAttr:: db

; [8-bit] WRAM bank of the shadow (off-screen) tilemap buffer; paired with wShadowTilemapPtr
wShadowTilemapBank:: db

; [16-bit] Base pointer of the shadow tilemap buffer (in bank wShadowTilemapBank); tiles at base, attributes at base+$0400
wShadowTilemapPtr:: dw

; [8-bit] CGB BG attribute byte applied to window/glyph tiles when drawing (default $80 = BG priority)
wWindowTileAttr:: db

; [16-bit] Glyph-stream horizontal pen position (sub-pixel fixed point); advanced per glyph by DrawStreamGlyph
wGlyphPenX:: dw
	ds 73

; [16-bit] Ball X position, integer part (lateral, signed)
wBallX:: dw
	ds 2

; [16-bit] Ball depth position, integer part (signed, net at 0)
wBallDepth:: dw
	ds 2

; [16-bit] Ball height above the court, integer part
wBallHeight:: dw
	ds 21

; [16-bit] Ball X velocity, integer part (24-bit fixed-point triple $c420-$c422, fraction byte at $c420); decayed by ApplyBallAirDrag
wBallVelocityX:: dw
	ds 1

; [16-bit] Ball depth velocity, integer part (triple $c423-$c425); curved by ApplyBallSpin
wBallVelocityDepth:: dw
	ds 1

; [16-bit] Ball height (vertical) velocity, integer part (triple $c426-$c428)
wBallVelocityHeight:: dw
	ds 17

; [16-bit] Aim angle of the shot being launched (high byte = angle, $100 per turn; low byte = fraction, top nibble used by MulSinCos); projected from ball position into wBallTargetX/Depth
wShotAimAngle:: dw
	ds 20

; [16-bit] Projected ball target/landing X (same world units as wBallX)
wBallTargetX:: dw

; [16-bit] Projected ball target/landing depth (companion to wBallTargetX; net at 0)
wBallTargetDepth:: dw
	ds 12

; [16-bit] Projected X of the ball-bounce dust effect (cached at bounce time)
wBounceEffectX:: dw

; [16-bit] Projected Y of the ball-bounce dust effect
wBounceEffectY:: dw

; [16-bit] Projected X of the swing-hit effect (cached at hit time)
wHitEffectX:: dw

; [16-bit] Projected Y of the swing-hit effect
wHitEffectY:: dw
	ds 16

; [16-bit] Camera X offset added before the <<3 screen projection (Func_08_59bb)
wCameraOffsetX:: dw

; [16-bit] Camera Y offset added before the <<3 screen projection
wCameraOffsetY:: dw

; [16-bit] Minigames - Current Score
wMinigamesCurrentScore:: dw

; [16-bit] Minigames - Target Score
wMinigamesTargetScore:: dw

; [16-bit] Projected X of the lob landing marker
wLandingMarkerX:: dw

; [16-bit] Projected Y of the lob landing marker
wLandingMarkerY:: dw
	ds 28

; [8-bit] Shot-type code of the shot in flight (rst00 jumptable in ExecuteShot; $09 smash, $0a lob, $0b drop - checked by RecordSmashAce/Lob/DropShot)
wCurrentShotType:: db
	ds 7

; [8-bit] Frames left of the ball-bounce dust effect (starts at $14)
wBounceEffectTimer:: db

; [8-bit] Frames left of the normal swing-hit spark (starts at $10)
wHitSparkTimer:: db

; [8-bit] Frames left of the special-shot hit flash (starts at $10; drives the bank $28 screen effect)
wSpecialHitTimer:: db
	ds 11

; [8-bit] Rally Length; number of times the ball was hit in the span of a point
wRallyLength:: db
	ds 3

; [8-bit] Nonzero draws the ball sprite slot
wBallSpriteEnabled:: db

; [8-bit] Nonzero draws the ball ground-shadow slot
wBallShadowEnabled:: db

; [8-bit] Nonzero draws the ball trail afterimages from the position history ring
wBallTrailEnabled:: db

; [8-bit] Trail palette index into BallTrailPalettes; nonzero also extends the trail from 2 to 5 ghosts
wBallTrailColor:: db
	ds 6

; [8-bit] Nonzero draws edge arrows for off-screen characters (set during the rally)
wOffscreenArrowsEnabled:: db
	ds 5

; [8-bit] Set in singles only; enables the wide flickering ground shadow under grounded characters
wStandingShadowsEnabled:: db
	ds 4

; [8-bit] wOnCourtCharCount - 1 (0x00-0x03); jumptable index for the match engine's per-character-count dispatches
wOnCourtCharCountMinus1:: db
	ds 3

; [8-bit] Current Serving Player (0x00-0x03)
wCurrentServingPlayer:: db
	ds 4

; [8-bit] 0 while the rally runs; point-end cause code once the point resolves
wPointOutcome:: db
	ds 295

; Dialogue string buffer (160 bytes); text-bank fetch routines copy string N here when called with a = 0
wTextBuffer:: db
	ds 191

; 32-byte staging buffer for inline text args (player name, arg strings, short texts) rendered via RenderInlineString
wInlineTextBuffer:: ds 32
	ds 172

; [8-bit] Nonzero draws the 4-corner court target zone (training drills)
wTargetZoneEnabled:: db
	ds 3

; [16-bit] Target zone X bound 1 (world units)
wTargetZoneX1:: dw

; [16-bit] Target zone depth bound 1 (world units)
wTargetZoneDepth1:: dw

; [16-bit] Target zone X bound 2 (world units)
wTargetZoneX2:: dw

; [16-bit] Target zone depth bound 2 (world units)
wTargetZoneDepth2:: dw
	ds 26

; [16-bit] Pointer to the current game mode's callback table (indexed by CallModeHook)
wModeHookTable:: dw

; [8-bit] ROM bank of the mode callback table (0 = no hooks registered)
wModeHookBank:: db
	ds 75

; [buffer] WRAM staging buffer for SRAM save-block I/O (WriteSaveBlock / VerifySaveBlock / ReadSaveBlock); also reused as a general bulk copy/decompress buffer
wSaveBlockBuffer:: db
	ds 23

; [8-bit] Story Mode - Main Character Level (0x01-0x63)
wStoryModeMainCharacterLevel:: db
	ds 7

; [8-bit] Story Mode - Main Character Top Stat (0x00-0x09)
wStoryModeMainCharacterTopStat:: db

; [8-bit] Story Mode - Main Character Slice Stat (0x00-0x09)
wStoryModeMainCharacterSliceStat:: db

; [8-bit] Story Mode - Main Character Serve Stat (0x00-0x09)
wStoryModeMainCharacterServeStat:: db

; [8-bit] Story Mode - Main Character Stroke Stat (0x00-0x09)
wStoryModeMainCharacterStrokeStat:: db

; [8-bit] Story Mode - Main Character Volley Stat (0x00-0x09)
wStoryModeMainCharacterVolleyStat:: db

; [8-bit] Story Mode - Main Character Angle Stat (0x00-0x09)
wStoryModeMainCharacterAngleStat:: db

; [8-bit] Story Mode - Main Character Placement Stat (0x00-0x09)
wStoryModeMainCharacterPlacementStat:: db

; [8-bit] Story Mode - Main Character Speed Stat (0x00-0x09)
wStoryModeMainCharacterSpeedStat:: db

; [8-bit] Story Mode - Main Character Dash Stat (0x00-0x09)
wStoryModeMainCharacterDashStat:: db

; [8-bit] Story Mode - Main Character Reaction Stat (0x00-0x09)
wStoryModeMainCharacterReactionStat:: db

; [8-bit] Story Mode - Main Character Stop Stat (0x00-0x09)
wStoryModeMainCharacterStopStat:: db
	ds 1

; [16-bit] Story Mode - Main Character EXP
wStoryModeMainCharacterEXP:: dw
	ds 10

; [8-bit] Story Mode - Main Character Spin Level
wStoryModeMainCharacterSpinLevel:: db

; [8-bit] Story Mode - Main Character Power Level
wStoryModeMainCharacterPowerLevel:: db

; [8-bit] Story Mode - Main Character Control Level
wStoryModeMainCharacterControlLevel:: db

; [8-bit] Story Mode - Main Character Speed Level
wStoryModeMainCharacterSpeedLevel:: db
	ds 28

; [8-bit] Story Mode - Partner Character Level (0x01-0x63)
wStoryModePartnerCharacterLevel:: db
	ds 7

; [8-bit] Story Mode - Partner Character Top Stat (0x00-0x09)
wStoryModePartnerCharacterTopStat:: db

; [8-bit] Story Mode - Partner Character Slice Stat (0x00-0x09)
wStoryModePartnerCharacterSliceStat:: db

; [8-bit] Story Mode - Partner Character Serve Stat (0x00-0x09)
wStoryModePartnerCharacterServeStat:: db

; [8-bit] Story Mode - Partner Character Stroke Stat (0x00-0x09)
wStoryModePartnerCharacterStrokeStat:: db

; [8-bit] Story Mode - Partner Character Volley Stat (0x00-0x09)
wStoryModePartnerCharacterVolleyStat:: db

; [8-bit] Story Mode - Partner Character Angle Stat (0x00-0x09)
wStoryModePartnerCharacterAngleStat:: db

; [8-bit] Story Mode - Partner Character Placement Stat (0x00-0x09)
wStoryModePartnerCharacterPlacementStat:: db

; [8-bit] Story Mode - Partner Character Speed Stat (0x00-0x09)
wStoryModePartnerCharacterSpeedStat:: db

; [8-bit] Story Mode - Partner Character Dash Stat (0x00-0x09)
wStoryModePartnerCharacterDashStat:: db

; [8-bit] Story Mode - Partner Character Reaction Stat (0x00-0x09)
wStoryModePartnerCharacterReactionStat:: db

; [8-bit] Story Mode - Partner Character Stop Stat (0x00-0x09)
wStoryModePartnerCharacterStopStat:: db
	ds 1

; [16-bit] Story Mode - Partner Character EXP
wStoryModePartnerCharacterEXP:: dw
	ds 10

; [8-bit] Story Mode - Partner Character Spin Level
wStoryModePartnerCharacterSpinLevel:: db

; [8-bit] Story Mode - Partner Character Power Level
wStoryModePartnerCharacterPowerLevel:: db

; [8-bit] Story Mode - Partner Character Control Level
wStoryModePartnerCharacterControlLevel:: db

; [8-bit] Story Mode - Partner Character Speed Level
wStoryModePartnerCharacterSpeedLevel:: db
	ds 40

; [8-bit] Message Speed
;
; 0x00 - Fast
; 0x01 - Normal
; 0x02 - Slow
wMessageSpeed:: db
	ds 1

; [8-bit] Game Mode
;
; 0x00 - Not playing tennis
; 0x01 - Story Mode - Ranking Match
; 0x02 - Story Mode - Island Open Match
; 0x03 - Story Mode - Practice Match
; 0x04 - Exhibition Mode
; 0x05 - Story Mode - Training Court Minigames
; 0x06 - Story Mode - Tennis Machine
; 0x07 - Story Mode - Wall Practice
; 0x08 - Mario Minigames
; 0x0a - Story Mode - Dream Match
wGameMode:: db
	ds 25

; [8-bit] Character 1 Service Aces
wCharacter1ServiceAces:: db

; [8-bit] Character 1 Return Aces
wCharacter1ReturnAces:: db

; [8-bit] Character 1 Smash Aces
wCharacter1SmashAces:: db

; [8-bit] Character 1 Lob Shot Winners
wCharacter1LobShotWinners:: db

; [8-bit] Character 1 Drop Shot Winners
wCharacter1DropShotWinners:: db

; [8-bit] Character 1 Faults
wCharacter1Faults:: db

; [8-bit] Character 1 Double Faults
wCharacter1DoubleFaults:: db
	ds 1

; [8-bit] Character 2 Service Aces
wCharacter2ServiceAces:: db

; [8-bit] Character 2 Return Aces
wCharacter2ReturnAces:: db

; [8-bit] Character 2 Smash Aces
wCharacter2SmashAces:: db

; [8-bit] Character 2 Lob Shot Winners
wCharacter2LobShotWinners:: db

; [8-bit] Character 2 Drop Shot Winners
wCharacter2DropShotWinners:: db

; [8-bit] Character 2 Faults
wCharacter2Faults:: db

; [8-bit] Character 2 Double Faults
wCharacter2DoubleFaults:: db
	ds 1

; [8-bit] Character 3 Service Aces
wCharacter3ServiceAces:: db

; [8-bit] Character 3 Return Aces
wCharacter3ReturnAces:: db

; [8-bit] Character 3 Smash Aces
wCharacter3SmashAces:: db

; [8-bit] Character 3 Lob Shot Winners
wCharacter3LobShotWinners:: db

; [8-bit] Character 3 Drop Shot Winners
wCharacter3DropShotWinners:: db

; [8-bit] Character 3 Drop Shot Winners
wCharacter3DropShotWinners2:: db

; [8-bit] Character 3 Double Faults
wCharacter3DoubleFaults:: db
	ds 1

; [8-bit] Character 4 Service Aces
wCharacter4ServiceAces:: db

; [8-bit] Character 4 Return Aces
wCharacter4ReturnAces:: db

; [8-bit] Character 4 Smash Aces
wCharacter4SmashAces:: db

; [8-bit] Player 4 Lob Shot Winners
wPlayer4LobShotWinners:: db

; [8-bit] Character 4 Drop Shot Winners
wCharacter4DropShotWinners:: db

; [8-bit] Character 4 Faults
wCharacter4Faults:: db

; [8-bit] Character 4 Double Faults
wCharacter4DoubleFaults:: db
	ds 1

; [8-bit] Player 1 Sets Won (0x00-0x03)
wPlayer1SetsWon:: db

; [8-bit] Player 2 Sets Won (0x00-0x03)
wPlayer2SetsWon:: db

; [8-bit] Player 1 Games Won (0x00-0x07)
wPlayer1GamesWon:: db

; [8-bit] Player 2 Games Won (0x00-0x07)
wPlayer2GamesWon:: db

; [8-bit] Player 1 Points Won
;
; 0x00 - 0
; 0x01 - 15
; 0x02 - 30
; 0x03 - 40
; 0x04 - Advantage/Deuce
; 0x05-0x07 - Tiebreaker only
wPlayer1PointsWon:: db

; [8-bit] Player 2 Points Won; for values see 0xc8e4
wPlayer2PointsWon:: db

; [8-bit] Deuce Indicator (0x01 when deuce, 0x00 otherwise)
wDeuceIndicator:: db

; [8-bit] Tiebreaker Indicator (0x01 when tiebreaker, 0x00 otherwise)
wTiebreakerIndicator:: db

; [8-bit] Match Win/Lose Flag (0x01 - win, 0xff - lose, 0x00 otherwise)
wMatchWinLoseFlag:: db

; [8-bit] Set Win/Lose Flag (0x01 - win, 0xff - lose, 0x00 otherwise)
wSetWinLoseFlag:: db

; [8-bit] Game Win/Lose Flag (0x01 - win, 0xff - lose, 0x00 otherwise))
wGameWinLoseFlag:: db

; [8-bit] Point Win/Lose Flag (0x01 - win, 0xff - lose, 0x00 otherwise)
wPointWinLoseFlag:: db

; [8-bit] Total Games Won In Match
wTotalGamesWonInMatch:: db

; [8-bit] Total Points Scored In Current Game
wTotalPointsScoredInCurrentGame:: db
	ds 2

; [8-bit] Match Type - Number Of Sets (0x01, 0x03, 0x05)
wMatchTypeNumberOfSets:: db

; [8-bit] Match Type - Number Of Games (0x02, 0x06)
wMatchTypeNumberOfGames:: db

; [8-bit] Nonzero when the current match is doubles; selects the wider court bound and 4 on-court characters
wMatchIsDoubles:: db

; [8-bit] Number of characters on court (2 singles, 4 doubles, 3 in Two-On-One); one banked WRAM struct each in banks 4-7
wOnCourtCharCount:: db

; [8-bit] Currently Used Court
;
; 0x00 - Hard Court
; 0x01 - Clay Court
; 0x02 - Grass Court (Exhibition)
; 0x03 - Composition Court
; 0x04 - Star Court
; 0x05 - Castle Court
; 0x06 - Tropics Court
; 0x07 - Jungle Court
; 0x08 - Warehouse Court
; 0x09 - Training Court (Practice)
; 0x0a - Tennis Machine
; 0x0b - Wall Practice
; 0x0c - Center Court (Island Open Finals)
; 0x0d - Grass Court (Island Open)
; 0x0f - Target Shot
; 0x10 - Shooting Star
; 0x11 - Banana Bunch
; 0x12 - Boo Blast
; 0x13 - Perfect Shot
; 0x14 - Treasure Box
; 0x15 - Medallion Match
; 0x16 - Fruit Fantasy
; 0x17 - Two-On-One
; 0x18 - Training Court (Match)
wCurrentlyUsedCourt:: db
	ds 1

; [16-bit BE] Current Minigame/Story Match
;
; 0x0000 - Singles Junior Practice Match
; 0x0001 - Singles Junior #4
; 0x0002 - Singles Junior #3
; 0x0003 - Singles Junior #2
; 0x0004 - Singles Junior #1
; 0x0005 - Singles Senior Practice Match
; 0x0006 - Singles Senior #4
; 0x0007 - Singles Senior #3
; 0x0008 - Singles Senior #2
; 0x0009 - Singles Senior #1
; 0x000a - Singles Varsity Practice Match
; 0x000b - Singles Varsity #4
; 0x0010 - Singles Island Open Round 1
; 0x0011 - Singles Island Open Round 2
; 0x0012 - Singles Island Open Semifinals
; 0x0013 - Singles Island Open Finals
; 0x0016 - Singles Dream Match (MAX)
; 0x0017 - Singles Dream Match (Intense)
; 0x0018 - Singles Dream Match (Hard/First time)
; 0x0100 - Doubles Junior Practice Match
; 0x0102 - Doubles Junior #3
; 0x0103 - Doubles Junior #2
; 0x0104 - Doubles Junior #1
; 0x0105 - Doubles Senior Practice Match
; 0x0107 - Doubles Senior #3
; 0x0108 - Doubles Senior #2
; 0x0109 - Doubles Senior #1
; 0x010a - Doubles Varsity Practice Match
; 0x010d - Doubles Varsity #2
; 0x0111 - Doubles Island Open Round 1
; 0x0112 - Doubles Island Open Semifinals
; 0x0113 - Doubles Island Open Finals
; 0x0116 - Doubles Dream Match (MAX)
; 0x0117 - Doubles Dream Match (Intense)
; 0x0118 - Doubles Dream Match (Hard/First time)
; 0x0200 - Service Match 1
; 0x0201 - Service Match 2
; 0x0202 - Service Match 3
; 0x0203 - Service Practice 1
; 0x0204 - Service Practice 2
; 0x0205 - Service Practice 3
; 0x0206 - Net Play Match 1
; 0x0207 - Net Play Match 2
; 0x0208 - Net Play Match 3
; 0x0209 - Net Play Practice 1
; 0x020a - Net Play Practice 2
; 0x020b - Net Play Practice 3
; 0x020c - Stroke Match 1
; 0x020d - Stroke Match 2
; 0x020e - Stroke Match 3
; 0x020f - Stroke Practice 1
; 0x0210 - Stroke Practice 2
; 0x0211 - Stroke Practice 3
; 0x0212 - Tennis Machine 1
; 0x0213 - Tennis Machine 2
; 0x0214 - Tennis Machine 3
; 0x0215 - Tennis Machine 4
; 0x0216 - Wall Practice 1
; 0x0217 - Wall Practice 2
; 0x0218 - Wall Practice 3
; 0x0219 - Wall Practice 4
; 0x021a - Tennis Machine High Score
; 0x021b - Wall Practice High Score
; 0x021c - Boo Blast
; 0x021d - Shooting Star
; 0x021e - Perfect Shot
; 0x021f - Target Shot
; 0x0220 - Fruit Fantasy
; 0x0221 - Banana Bunch
; 0x0222 - Treasure Box
; 0x0223 - Medallion Match
; 0x0224 - Two-On-One
wCurrentMinigameStoryMatch:: dw
	ds 8

; [ASCII, 7 Bytes] Story Mode - Name of Main Character
wStoryModeNameOfMainCharacter:: ds 7
	ds 4

; [8-bit] Story Mode - Main Character Overworld Sprite
;
; 0x00 - Alex
; 0x01 - Nina
; 0x02 - Harry
; 0x03 - Kate
; Loops for all other values
wStoryModeMainCharacterOverworldSprite:: db

; [8-bit] Story Mode - Main Character Overworld Sprite Color
;
; 0x00 - Green
; 0x01 - Pink
; 0x02 - Yellow
; 0x03 - Red
; 0x04 - Blue
; All other values result in glitched sprite
wStoryModeMainCharacterOverworldSpriteColor:: db
	ds 47

; [Lower4] Equipped Racket
;
; 0x0 - Normal Racket
; 0x1 - Large Racket
; 0x2 - Small Racket
; 0x3 - Iron Racket
; 0x4 - Gold Racket
; 0x5 - Silver Racket
; 0x6 - Drive Racket
;
; [Upper4] Equipped Shoes
;
; 0x0 - Normal Shoes
; 0x1 - Iron Shoes
; 0x2 - Light Shoes
wEquippedRacket:: db
	ds 3

; [ASCII, 7 Bytes] Story Mode - Name of Partner Character
wStoryModeNameOfPartnerCharacter:: ds 7
	ds 4

; [8-bit] Story Mode - Partner Character Overworld Sprite; for values see 0x00c90b
wStoryModePartnerCharacterOverworldSprite:: db

; [8-bit] Story Mode - Partner Character Overworld Sprite Color; for values see 0x00c90c
wStoryModePartnerCharacterOverworldSpriteColor:: db
	ds 115

; Event flag bit-array; rst $20/$28/$30 set/clear/test wGameFlags[byte] with mask $80 >> bit
wGameFlags:: db
	ds 4

; [8-bit] Singles/Doubles Indicator (Story & Exhibition Mode)
;
; 0x00 - Singles
; 0x01 - Doubles
wSinglesDoublesIndicator:: db

; [Lower4] Story Mode - Match Completion Flags (1/6)
;
; Bit 0 - Doubles Island Open Round 1
; Bit 1 - Doubles Island Open Semifinals
; Bit 2 - Doubles Island Open Finals
; Bit 3 - Doubles Dream Match
wStoryModeMatchCompletionFlags1:: db

; [8-bit] Story Mode - Match Completion Flags (2/6)
;
; Bit 0 - Singles Island Open Round 1
; Bit 1 - Singles Island Open Round 2
; Bit 2 - Singles Island Open Semifinals
; Bit 3 - Singles Island Open Finals
; Bit 4 - Singles Dream Match
wStoryModeMatchCompletionFlags2:: db

; [8-bit] Story Mode - Match Completion Flags (3/6)
;
; Bit 7 - Doubles Junior Rank 3
; Bit 6 - Doubles Junior Rank 2
; Bit 5 - Doubles Junior Rank 1
; Bit 3 - Doubles Senior Rank 3
; Bit 2 - Doubles Senior Rank 2
; Bit 1 - Doubles Senior Rank 1
wStoryModeMatchCompletionFlags3:: db

; [Upper4] Story Mode - Match Completion Flags (4/6)
;
; Bit 7 - Doubles Varsity Rank 2
wStoryModeMatchCompletionFlags4:: db

; [8-bit] Story Mode - Match Completion Flags (5/6)
;
; Bit 7 - Singles Junior Rank 4
; Bit 6 - Singles Junior Rank 3
; Bit 5 - Singles Junior Rank 2
; Bit 4 - Singles Junior Rank 1
; Bit 3 - Singles Senior Rank 4
; Bit 2 - Singles Senior Rank 3
; Bit 1 - Singles Senior Rank 2
; Bit 0 - Singles Senior Rank 1
wStoryModeMatchCompletionFlags5:: db

; [Upper4] Story Mode - Match Completion Flags (6/6)
;
; Bit 7 - Singles Varsity Rank 4
wStoryModeMatchCompletionFlags6:: db

; [8-bit] Story Mode - Equipment Flags (1/2)
;
; Bit 6 - Large Racket
; Bit 5 - Small Racket
; Bit 4 - Iron Racket
; Bit 3 - Silver Racket
; Bit 2 - Gold Racket
; Bit 1 - Drive Racket
; Bit 0 - Iron Shoes
wStoryModeEquipmentFlags1:: db

; [Upper4] Story Mode - Equipment Flags (2/2)
;
; Bit 7 - Light Shoes
wStoryModeEquipmentFlags2:: db
	ds 10

; [8-bit] Story Mode - Minigame Completion Flags (1/4)
;
; Bit 7 - Service Match 1
; Bit 6 - Service Match 2
; Bit 5 - Service Match 3
; Bit 4 - Service Practice 1
; Bit 3 - Service Practice 2
; Bit 2 - Service Practice 3
; Bit 1 - Net Play Match 1
; Bit 0 - Net Play Match 2
wStoryModeMinigameCompletionFlags1:: db

; [8-bit] Story Mode - Minigame Completion Flags (2/4)
;
; Bit 7 - Net Play Match 3
; Bit 6 - Net Play Practice 1
; Bit 5 - Net Play Practice 2
; Bit 4 - Net Play Practice 3
; Bit 3 - Stroke Match 1
; Bit 2 - Stroke Match 2
; Bit 1 - Stroke Match 3
; Bit 0 - Stroke Practice 1
wStoryModeMinigameCompletionFlags2:: db

; [8-bit] Story Mode - Minigame Completion Flags (3/4)
;
; Bit 7 - Stroke Practice 2
; Bit 6 - Stroke Practice 3
; Bit 5 - Machine Level 1
; Bit 4 - Machine Level 2
; Bit 3 - Machine Level 3
; Bit 2 - Machine Level 4
; Bit 1 - Wall Level 1
; Bit 0 - Wall Level 2
wStoryModeMinigameCompletionFlags3:: db

; [Upper4] Story Mode - Minigame Completion Flags (4/4)
;
; Bit 7 - Wall Level 3
; Bit 6 - Wall Level 4
wStoryModeMinigameCompletionFlags4:: db
	ds 47

; [8-bit] Player 1 Current Main Character
;
; 0x00 - Alex
; 0x01 - Nina
; 0x02 - Harry
; 0x03 - Kate
; 0x04 - Allie
; 0x05 - Joy
; 0x06 - Brian
; 0x07 - Pam
; 0x08 - Bob
; 0x09 - Beth
; 0x0a - Fay
; 0x0b - Curt
; 0x0c - Mark
; 0x0d - Sean
; 0x0e - Sammi
; 0x0f - Elden
; 0x10 - Spike
; 0x11 - Emily
; 0x12 - B. Coz
; 0x13 - A. Coz
; 0x14 - Kevin (dummied out)
; 0x15 - Tennis Machine
; 0x16 - Allie 2 (never shows up?)
; 0x17 - Luigi
; 0x18 - Donkey Kong
; 0x19 - Baby Mario
; 0x1a - Mario
; 0x1b - Waluigi
; 0x1c - Yoshi
; 0x1d - Bowser
; 0x1e - Wario
; 0x1f - Peach
wPlayer1CurrentMainCharacter:: db
	ds 63

; [8-bit] Player 1 Current Partner Character; for values see 0xca0b
wPlayer1CurrentPartnerCharacter:: db
	ds 19

; [8-bit] Exhibition Mode - Player Partner Character Difficulty
;
; 0x00 - Easy
; 0x01 - Normal
; 0x02 - Hard
; 0x03 - Intense
wExhibitionModePlayerPartnerCharacterDifficulty:: db
	ds 43

; [8-bit] Player 2 Current Main Character; for values see 0xca0b
wPlayer2CurrentMainCharacter:: db
	ds 19

; [8-bit] Exhibition Mode - CPU Main Character Difficulty; for values see 0x00ca5f
wExhibitionModeCPUMainCharacterDifficulty:: db
	ds 43

; [8-bit] Player 2 Current Partner Character; for values see 0xca0b
wPlayer2CurrentPartnerCharacter:: db
	ds 19

; [8-bit] Exhibition Mode - CPU Partner Character Difficulty; for values see 0x00ca5f
wExhibitionModeCPUPartnerCharacterDifficulty:: db
	ds 36

; [8-bit] Menu cursor column; MoveMenuCursor wraps it at the column count in b
wMenuCursorX:: db

; [8-bit] Menu cursor row; MoveMenuCursor wraps it at the row count in c
wMenuCursorY:: db
	ds 7

; [8-bit] Menu loop's copy of hInputPressed (same bit layout as hPlayerInputFlags)
wMenuInputPressed:: db

; [8-bit] Match-format menu: singles (0) / doubles (1) selection; copied to wMatchIsDoubles
wMatchFormatDoubles:: db

; [8-bit] Match-format menu: games-per-set selection index; table-mapped to wMatchTypeNumberOfGames
wMatchFormatGames:: db

; [8-bit] Match-format menu: number-of-sets selection index (0-2); table-mapped to wMatchTypeNumberOfSets
wMatchFormatSets:: db

; [8-bit] Menu transition direction (1 = forward into submenu, 0 = back); direction arg to the *SlideIn/*SlideOut menu transitions
wMenuSlideDirection:: db
	ds 47

; [8-bit] Intro Cutscene Check (0x00 when in intro cutscene, 0x01 otherwise)
wIntroCutsceneCheck:: db
	ds 31

; Dirty flags for the bank $18 BG map shadow buffers: low nibble set -> queue $d800->$9800 tilemap copy, high nibble -> $dc00->VRAM1 $9800 attrmap copy (FlushBgMapShadowToVram clears it).
wBgMapShadowDirty:: db
	ds 20

; VRAM tile-data write pointer for the proportional-glyph renderer (bank $05 text engine)
wGlyphTileWritePtr:: dw
	ds 136

; [576 bytes] Debug text console tilemap buffer, DMAed to $9d00 rows when active
wDebugTextBuffer:: ds 576


SECTION "WRAMX $d841", WRAMX[$d841]

; WRAM5: frame counter for the text continue-arrow blink task (bit 4 selects tile)
wTextArrowBlinkCounter:: db
	ds 5

; WRAM5: write index into wTextArgStringQueue (max 16)
wTextArgStringWriteIndex:: db
	ds 1

; WRAM5: write index for the short-text-id arg queue
wTextArgShortTextWriteIndex:: db

; WRAM5: count of queued arg strings (mirrors wTextArgStringWriteIndex)
wTextArgStringCount:: db
	ds 5

; WRAM5: set by TextCmdWaitButtonPage; TextInterpreterLoop saves resume offset to $d84e/f and returns
wTextPageBreakRequest:: db
	ds 19

; WRAM5: current VRAM destination address for glyph tiles (lo/hi)
wGlyphVramDest:: dw
	ds 3

; WRAM5: current read pointer into the text byte stream
wTextStreamPtr:: dw
	ds 21

; Short string buffer (16 bytes); text-bank fetch routines copy here when called with a != 0
wShortTextBuffer:: db
	ds 47

; WRAM5: 16 x 2-byte string pointers queued by PushTextArgString (hi nibble = WRAM bank tag)
wTextArgStringQueue:: ds 32

; WRAM5: 16 x 2-byte values queued by PushTextArgNumber for TextCmdPrintArgNumber
wTextArgNumberQueue:: ds 32
