; RAM layout from ram_map.json (RetroAchievements Code Notes).
; Regenerated by tools/disasm.py; do not edit by hand.

SECTION "WRAM0 $c0a0", WRAM0[$c0a0]

; [80 bytes] VBlank VRAM copy queue: 10 x 8-byte entries [rom bank, wram bank, size hi, size lo, vbk, dest hi, dest lo, src?]; processed by ProcessVRAMCopyQueues
wVRAMCopyQueue:: ds 80

; [4 bytes] Play timer: frames (0-59), seconds, minutes, hours (caps at 99)
wGameTimer:: ds 4
	ds 12

; [64 bytes] Live BG palette buffer, uploaded in VBlank when hPaletteDirtyFlags bit 0 set
wBGPalettes:: ds 64

; [64 bytes] Live OBJ palette buffer, uploaded in VBlank when hPaletteDirtyFlags bit 1 set
wOBJPalettes:: ds 64

; [64 bytes] VBlank single-tile write queue: 16 x 4-byte entries [addr hi, addr lo, tile (VBK0), attr (VBK1)]
wTileWriteQueue:: ds 64

; [64 bytes] Frame task list: 4-byte records [id, ptr lo, ptr hi, rom bank] of banked callbacks run each frame (RegisterFrameTask / ClearFrameTasks)
wFrameTasks:: ds 64

; [128 bytes] Master palette copy (BG+OBJ); fades scale this into wBGPalettes/wOBJPalettes
wMasterPalettes:: ds 128

; [8-bit] Story Mode - Current Location
;
; 0x00 - Not in Story Mode
; 0x05 - Academy Main Building
; 0x06 - Academy Wing
; 0x07 - Courtyard
; 0x08 - Restaurant Plaza
; 0x09 - Dorm Entrance
; 0x0a - Dormitory
; 0x0b, 0x0c - Junior Class Court
; 0x0d - Restaurant
; 0x0e - Cafeteria
; 0x0f - Training Court
; 0x10 - Senior Class Court
; 0x11 - Training Center
; 0x12 - Tennis Machine Room
; 0x13 - Wall Practice Room
; 0x14 - Academy Entrance
; 0x15 - Tournament Courtyard
; 0x16 - Court #1
; 0x17 - Court #2
; 0x18 - Center Court
; 0x19 - Tournament
; 0x1a - Awards Ceremony
; 0x1b - Plane Cutscene
; 0x1c - Castle Court
; 0x1d - Peach's Castle
; 0x1e-0x29 - Final Credits Sequence
wStoryModeCurrentLocation:: db
	ds 20

; [8-bit] Story Mode - entry point / spawn-door ID for the location being loaded; $ff = none (keep saved player position). LoadStoryEntryPointRecord searches the location's entry table with it
wStoryModeEntryPoint:: db

; [5 bytes] Story Mode - player spawn/return buffer: X (16-bit), Y (16-bit), facing; filled from the matched entry-point record or backed up from wStoryModePlayersXPosition before a submode
wStoryModeSpawnPosition:: ds 5
	ds 5

; [8-bit] Story Mode - queued tile trigger-script id (behavior-map cell with low nibble 1 stores its high nibble here); nonzero makes the overworld loop run RunQueuedTriggerScript
wStoryModeTriggerScript:: db

; [8-bit] Story Mode - nonzero requests leaving the current location loop (RunLocationExit + reload); one of the event-request flags at $c2a0-$c2a5 cleared by ClearStoryEventRequests
wStoryModeExitLocationRequest:: db
	ds 2

; [8-bit] Story Mode - set to 1 on an A-press in the overworld; the event loop then tries NPC interaction (FindActorFacingPlayer), facing-tile script, and tile trigger
wStoryModeInteractRequest:: db

; [8-bit] Story Mode - set to 1 on a Start-press in the overworld; opens the story-mode menu (RunStoryModeMenu)
wStoryModeMenuRequest:: db
	ds 14

; [16-bit] Water Sprite Minigame - Timer (Frames)
wWaterSpriteMinigameTimer:: dw

; [16-bit] Water Sprite Minigame - Swing Count
wWaterSpriteMinigameSwingCount:: dw
	ds 2

; [8-bit] Water Sprite Minigame Flag (0x17 when in minigame)
wWaterSpriteMinigameFlag:: db
	ds 21

; [16-bit] Story Mode - Player's X Position
wStoryModePlayersXPosition:: dw

; [16-bit] Story Mode - Player's Y Position
wStoryModePlayersYPosition:: dw
	ds 1

; [8-bit] Story Mode - nonzero shows the location-name popup after fade-in (derived from wStoryModeEntryPoint != $ff; name pointer at $c2d6/$c2d7)
wStoryModeShowLocationName:: db

; [16-bit] Story Mode - text id of the current location's name, passed in hl to ShowLocationNamePopup when wStoryModeShowLocationName is set
wStoryModeLocationNameTextId:: dw
	ds 72

; [16-bit] BG scroll-buffer camera X (tiles<<3?)
wCameraX:: dw

; [16-bit] BG scroll-buffer camera Y
wCameraY:: dw
	ds 2

; [16-bit] Tilemap address for the queued BG row blit
wBGRowBlitDest:: dw

; [8-bit] Tilemap column for the queued BG column blit
wBGColumnBlitX:: db
	ds 5

; [8-bit] Current story-cutscene scene index; indexes SceneGfxSlotTable (index*16) and drives LoadAndDisplayScene / InitSceneTileAnimations
wCurrentScene:: db
	ds 15

; [8-bit] Current BGM
;
; 0x00 - Silence
; 0x01 - Intro Cutscene
; 0x02 - Title Screen
; 0x03 - Main Menu
; 0x04 - Status Screen
; 0x05 - Dictionary
; 0x06 - Exhibition Match
; 0x07 - Unused
; 0x08 - Mario Minigame Screen
; 0x09 - You Win
; 0x0a - You Lose
; 0x0b - Earning EXP
; 0x0c - Distributing EXP
; 0x0d - Distributing Stats
; 0x0e - Tiebreaker
; 0x0f - Set/Match Point
; 0x10 - Game Point
; 0x11 - Star Court
; 0x12 - Castle Court/Peach's Castle
; 0x13 - Tropic Court/Fruit Fantasy
; 0x14 - Warehouse Court/Treasure Box
; 0x15 - Two-on-One
; 0x16 - Jungle Court/Banana Bunch
; 0x17 - Unused
; 0x18 - Unused
; 0x19 - Shooting Star/Target Shot/Medallion Match
; 0x1a - Academy Main Building
; 0x1b - Story Mode Outdoors
; 0x1c - Dormitory
; 0x1d - Story Mode Indoors
; 0x1e - Tennis Machine
; 0x1f - Wall Practice
; 0x20 - Practice Match
; 0x21 - Junior Ranking Match
; 0x22 - Senior Ranking Match
; 0x23 - Varsity Ranking Match
; 0x24 - Training Court Match
; 0x25 - Training Court Practice
; 0x26 - Island Open Beginning Rounds
; 0x27 - Island Open Semifinals
; 0x28 - Island Open Finals
; 0x29 - Dream Match
; 0x2a - Unused
; 0x2b - Island Open Congratulations
; 0x2c - Credits
; 0x2d - The End
; 0x2e - Done For The Day
; 0x2f - Level Up
; 0x30 - High Score
; 0x31 - Exhibition Match Start
; 0x32 - Story Match Start
wCurrentBGM:: db
	ds 45

; [8-bit] Active story save-slot index (0-2); selects which SRAM story slot CheckStorySlot / SaveStorySlotWithTimer operate on
wCurrentStorySlot:: db
	ds 9

; [8-bit] Minigame Level (0x00-0x03)
;
; Value is current minigame level - 1
wMinigameLevel:: db
	ds 48

; [8-bit] High byte of current OAM shadow buffer ($c0/$c5); toggled each frame, OAM DMA source
wSpriteBufferPage:: db
	ds 8

; [8-bit] Character id (see 0xca0b values) assigned to court slot 0 (player's main character) during match setup; also used for portraits/sprites
wMatchPlayerChar:: db

; [8-bit] Character id assigned to court slot 2 (opponent's main character) during match setup ($ff = none); set via SetStoryMatchOpponent
wMatchOpponentChar:: db

; [8-bit] BG attribute written for window-frame cells ($80 = BG priority)
wWindowFrameAttr:: db

; [8-bit] WRAM bank of the shadow (off-screen) tilemap buffer; paired with wShadowTilemapPtr
wShadowTilemapBank:: db

; [16-bit] Base pointer of the shadow tilemap buffer (in bank wShadowTilemapBank); tiles at base, attributes at base+$0400
wShadowTilemapPtr:: dw

; [8-bit] CGB BG attribute byte applied to window/glyph tiles when drawing (default $80 = BG priority)
wWindowTileAttr:: db

; [16-bit] Glyph-stream horizontal pen position (sub-pixel fixed point); advanced per glyph by DrawStreamGlyph
wGlyphPenX:: dw
	ds 73

; [16-bit] Ball X position, integer part (lateral, signed)
wBallX:: dw
	ds 2

; [16-bit] Ball depth position, integer part (signed, net at 0)
wBallDepth:: dw
	ds 2

; [16-bit] Ball height above the court, integer part
wBallHeight:: dw
	ds 2

; [16-bit] Ball physics - horizontal heading angle of the ball's velocity (same $100-per-turn encoding as wShotAimAngle). Written by UpdateBallAnglesAndSpeed ($08:$45f1) as AngleFromVector16(de=wBallVelocityX, hl=wBallVelocityDepth); read by ApplyBallSpin ($08:$5724, MulSinCosSigned to split the topspin term back onto the X/depth axes) and by PredictBallLateralOffset ($08:$70f5).
wBallHeadingAngle:: dw
	ds 6

; [16-bit] Ball depth at the start of the frame (integer part). StepBallPhysics ($08:$576b) copies the whole 12-byte position block $c400-$c40b to $c410-$c41b before adding velocity, so $c410/$c414/$c418 mirror the wBallX/wBallDepth/wBallHeight 32-bit triples; only the depth integer part is ever read back. HandleBallNetCrossing ($08:$581c) XORs wBallDepth+1 with $c417 and tests bit 7 to detect the net crossing; DidBallCrossGate ($08:$6773) reads the full word.
wBallPrevDepth:: dw
	ds 4

; [16-bit] Ball physics - top/backspin coefficient (rotation about the lateral axis). Set from bc by SetBallSpinComponents ($08:$45de). ApplyBallSpin ($08:$56a9-$5765): while nonzero it multiplies wBallVelocityHeight by it and adds the (negated) product along wBallHeadingAngle into the X/depth velocities ($c420/$c423), and multiplies wBallSpeedHorizontal by it and adds that into the height velocity ($c426) - i.e. a Magnus rotation of the (horizontal, vertical) velocity pair. Decayed by 3/256 per frame at $08:$574a-$5765.
wBallTopspin:: dw

; [16-bit] Ball physics - sidespin/curve coefficient (rotation about the vertical axis). Set from de by SetBallSpinComponents ($08:$45d8). ApplyBallSpin ($08:$5613-$56a8): while nonzero it adds +k*wBallVelocityDepth to the X velocity ($c420) and -k*wBallVelocityX to the depth velocity ($c423), curving the ball laterally; then decays itself by 3/256 per frame ($08:$568d-$56a8).
wBallSideSpin:: dw
	ds 1

; [16-bit] Ball X velocity, integer part (24-bit fixed-point triple $c420-$c422, fraction byte at $c420); decayed by ApplyBallAirDrag
wBallVelocityX:: dw
	ds 1

; [16-bit] Ball depth velocity, integer part (triple $c423-$c425); curved by ApplyBallSpin
wBallVelocityDepth:: dw
	ds 1

; [16-bit] Ball height (vertical) velocity, integer part (triple $c426-$c428)
wBallVelocityHeight:: dw
	ds 1

; [16-bit] Magnitude of the ball's horizontal (X,depth) velocity, integer part of the 24-bit triple $c429-$c42b (fraction byte at $c429). Written by UpdateBallAnglesAndSpeed ($08:$4606) as VectorLengthFromAngle(bc=wBallHeadingAngle, hl=wBallVelocityDepth, de=wBallVelocityX); read by ApplyBallSpin ($08:$56ed) as the horizontal-speed factor of the topspin lift term.
wBallSpeedHorizontal:: dw
	ds 4

; [16-bit] World X the shot is aimed at, in the same units as wBallX. Written by ComputeShotTrajectory ($07:$5746) from ComputeShotTargetX, copied on to wBallTargetX at $07:$5863, and drawn as a world-space marker sprite at $08:$54f3 (ProjectWorldToScreen + QueueSprite). Cleared with $c432 by ResetBallState ($08:$5149).
wShotAimTargetX:: dw

; [16-bit] World depth the shot is aimed at (companion to wShotAimTargetX; net at 0, sign already corrected for the hitter's court side at $07:$5725). Written by ComputeShotTrajectory ($07:$572b), copied on to wBallTargetDepth at $07:$5863, read as the depth of the aim marker sprite at $08:$54ed.
wShotAimTargetDepth:: dw

; [16-bit] wShotAimTargetX - wBallX, the lateral leg of the ball->target vector. Written by ComputeShotTrajectory ($07:$5758). Read by every court bank's SetBallTargetByPrediction ($20/$21/$22/$23/$2a/$2b/$2c:$40a3, $24:$40af, $29:$40a3) and by the trajectory-length path at $20:$416a, where it is passed as the hl argument of VectorLengthFromAngle together with wShotAimDeltaDepth in de.
wShotAimDeltaX:: dw

; [16-bit] wShotAimTargetDepth - wBallDepth, the depth leg of the ball->target vector. Written by ComputeShotTrajectory ($07:$573d) and immediately fed to AngleFromVector16 at $07:$5764 (with wShotAimDeltaX in de) to produce wShotAimAngle; read again as the de argument of VectorLengthFromAngle at $20:$4164 and in the other court banks.
wShotAimDeltaDepth:: dw
	ds 2

; [16-bit] Aim angle of the shot being launched (high byte = angle, $100 per turn; low byte = fraction, top nibble used by MulSinCos); projected from ball position into wBallTargetX/Depth
wShotAimAngle:: dw
	ds 2

; [16-bit] Base lateral aim spread used to place a rally shot's target: $0220 in singles, $0320 in doubles ($08:$4104-$4111, at match init). ComputeAimBaseOffset ($07:$56b7) returns (this + |wCharPosDepth|/8) scaled by the character's aim stat $df69, which ComputeShotTargetX then adds to / subtracts from wBallX before clamping.
wAimSpreadBase:: dw

; [16-bit] Match camera current X (projected space). SnapCameraTo ($08:$61ac) sets it and the target together; UpdateMatchCamera eases it toward wMatchCameraTargetX ($08:$61f4-$625c) and then derives wCameraOffsetX from it at $08:$6281-$62c3.
wMatchCameraX:: dw

; [16-bit] Match camera current Y (projected space); eased toward wMatchCameraTargetY and shifted into wCameraOffsetY at $08:$62c4.
wMatchCameraY:: dw

; [16-bit] Match camera target X. Written by SetCameraTarget ($08:$61cb) and SnapCameraTo ($08:$61b2, plus the bank $0d copy SnapCameraTo_0d $4942), overwritten every frame from wBallGroundProjX while wCameraFollowBall is set; UpdateMatchCamera steps wMatchCameraX toward it with a fixed $0040 step (VectorFromLengthAndAngleRaw at $08:$6222).
wMatchCameraTargetX:: dw

; [16-bit] Match camera target Y (companion to wMatchCameraTargetX; same writers and the same snap-on-overshoot logic at $08:$6263-$6280).
wMatchCameraTargetY:: dw

; [16-bit] Ball X minus the current character's X (wBallX - wCharPosX+1), signed. Written by UpdateCharBallGeometry ($08:$6e6a-$6e75) for whichever character bank is mapped; read by AiSteerTowardBall ($08:$7944) as the de leg of AngleFromVectorCoarse and by the swing/contact range checks at $08:$6ef2/$6fed/$704e.
wBallRelCharX:: dw

; [16-bit] Ball depth minus the current character's depth, signed (same struct as wBallRelCharX). Read by CheckBallContactWindow ($08:$6fa7), CheckBallInSwingRange ($08:$702a), ComputeBallEtaToChar ($08:$70ca-$70e7, divided by wBallVelocityDepth to get frames-to-arrival), PredictBallLateralOffset ($08:$70fb) and the AI at $08:$7b99.
wBallRelCharDepth:: dw

; [16-bit] Ball height minus the current character's height, signed (third word of the same struct). Read by the reach/height gates at $08:$6f12 and $08:$700d, each comparing |value| against the character's reach field $df70.
wBallRelCharHeight:: dw
	ds 2

; [16-bit] Projected ball target/landing X (same world units as wBallX)
wBallTargetX:: dw

; [16-bit] Projected ball target/landing depth (companion to wBallTargetX; net at 0)
wBallTargetDepth:: dw
	ds 12

; [16-bit] Projected X of the ball-bounce dust effect (cached at bounce time)
wBounceEffectX:: dw

; [16-bit] Projected Y of the ball-bounce dust effect
wBounceEffectY:: dw

; [16-bit] Projected X of the swing-hit effect (cached at hit time)
wHitEffectX:: dw

; [16-bit] Projected Y of the swing-hit effect
wHitEffectY:: dw
	ds 4

; [16-bit] Projected screen-space X of the ball's ground (shadow) position, from ProjectWorldToScreen(wBallX, wBallDepth) in BuildBallShadowSlot ($08:$5267). UpdateMatchCamera ($08:$61e2) copies $c46c-$c46f into the camera target $c444-$c447 whenever wCameraFollowBall is set.
wBallGroundProjX:: dw

; [16-bit] Projected screen-space Y of the ball's ground position (companion to wBallGroundProjX, from the bc return of ProjectWorldToScreen at $08:$526d).
wBallGroundProjY:: dw
	ds 8

; [16-bit] Camera X offset added before the <<3 screen projection (Func_08_59bb)
wCameraOffsetX:: dw

; [16-bit] Camera Y offset added before the <<3 screen projection
wCameraOffsetY:: dw

; [16-bit] Minigames - Current Score
wMinigamesCurrentScore:: dw

; [16-bit] Minigames - Target Score
wMinigamesTargetScore:: dw

; [16-bit] Projected X of the lob landing marker
wLandingMarkerX:: dw

; [16-bit] Projected Y of the lob landing marker
wLandingMarkerY:: dw

; [16-bit] In-bounds lateral limit, stored as the two's-complement negative of the |X| bound: $fe50 (= -$1b0) in singles, $fdc0 (= -$240) in doubles ($08:$40e8, $08:$4300-$430d, $0d:$4690). CheckBallOutOfBounds ($08:$463c) adds it to |wBallX| and treats the carry as 'out'; ClampShotTargetX ($07:$56e3) clamps the aim target to (-value - $20); ComputeShotTrajectory ($07:$57f4) uses the same figure to shorten wShotDistMax when the aim line would leave the court sideways.
wCourtLimitX:: dw

; [16-bit] In-bounds depth limit, also stored negated: $fb20 (= -$4e0, the baseline) normally, tightened to $fd60 (= -$2a0, the service line) while a serve is in flight ($08:$4cff) and restored at $08:$40ee / $0d:$4bd2. CheckBallOutOfBounds ($08:$4657) adds it to |wBallDepth| and sets bit 1 of the out-of-bounds mask on carry.
wCourtLimitDepth:: dw

; [16-bit] Height of the net in ball-height units ($0060 in a normal match, $08:$40f7; $0000 for the solo minigames that have no net, $0d:$4b0b). HandleBallNetCrossing ($08:$5830-$5853) adds it to wBallHeight at the moment the ball crosses depth 0 and, if the sum is still non-negative (heights are negative-up), plays sound $5a, starts the bounce effect, sets wBallHasBouncedFlag and negates the depth position and velocity - i.e. the ball clipped the net.
wNetHeight:: dw

; [16-bit] Shot solver - minimum distance along the aim line, i.e. the distance from the ball to where the aim line crosses depth $0140 past the net. ComputeShotTrajectory ($07:$5783-$57a1) computes |wBallDepth| + $0140, divides by sin(wShotAimAngle) (DivBySin, $07:$5787), takes the absolute value and stores it here; $c48e caches value>>6. Every court bank's ApplyBallTrajectory ($20:$4108, $4135, $419c, $41cf and the same offsets in $21-$24, $29-$2c) loads it into de and passes it to BallTrajEntryPtr6/4 as the starting row of the trajectory table.
wShotDistMin:: dw

; [16-bit] Shot solver - maximum distance along the aim line: distance to where the aim line crosses depth $0480 (just inside the baseline at $4e0), computed the same way at $07:$57b8-$57d6, then shortened at $07:$582c-$5850 to the distance at which the aim line would cross the sideline (wCourtLimitX + $0020) if that comes first. $c48f caches value>>6. Read by the court banks at $20:$4175/$4183 (and the same offsets elsewhere) to clamp the actual ball->target length before selecting a trajectory row.
wShotDistMax:: dw

; [8-bit] wShotDistMin >> 6 - the first row index of the per-court ball-trajectory table to consider. Written at $07:$5799 as the high byte of (wShotDistMin << 2). Loaded into d as the loop counter by every court bank's SeekBallTrajEntry6/4 ($20:$401f and $20:$403e, mirrored in $21-$24, $29-$2c).
wShotTrajRowMin:: db

; [8-bit] wShotDistMax >> 6 - the last row index the trajectory search may reach. Written at $07:$57ce and re-written at $07:$5848 when wShotDistMax is shortened by the sideline clamp. Loaded into e by SeekBallTrajEntry6/4, which stops as soon as d (wShotTrajRowMin, incremented per row) reaches it.
wShotTrajRowMax:: db
	ds 1

; [8-bit] Winning-shot type for the point just won: 0=none, 1=service ace, 2=return ace, 3=smash ace, 4=lob winner, 5=drop-shot winner. Reset to 0 in the per-point state clear ($08:$4cd5); set by the Record*Stat functions ($08:$5c5f+) which also credit the matching wCharacterN stat. The on-court winner banner is ShowCourtBanner(value+$17) at $08:$4e75, i.e. banner ids 24-28 (SERVICE/RETURN/SMASH ACE, LOB, DROP SHOT) - confirmed in-game.
wPointWinnerShotType:: db

; [8-bit] Companion abort flag to wMatchAbortFlag ($ff set by every quit-menu action): makes StepMatchFrames return immediately and suppresses result jingles
wMatchFramesAbort:: db
	ds 1

; [8-bit] Scoreboard layout/caption style code, 0-7. Chosen by Func_08_454b ($08:$454b) from wOnCourtCharCount (singles/doubles) or, for minigames ($c8f5 == 2), from $c7ba/$c7bb as 3/4/7. Used as an rst00 jumptable index by DrawScoreboardCaption ($06:$477a) and DrawScoreboard ($06:$49c0), as a table index at $06:$49ae and $06:$507b, and checked against 3 by the bank $09 serve-indicator spawner ($09:$4133, $09:$425a).
wScoreboardLayout:: db
	ds 11

; [8-bit] Shot-type code of the shot in flight (rst00 jumptable in ExecuteShot; $09 smash, $0a lob, $0b drop - checked by RecordSmashAce/Lob/DropShot)
wCurrentShotType:: db
	ds 1

; [8-bit] Charge level of the shot being executed, 0-$3f. Snapshotted from the hitter's $df4b and clamped to $3f in ExecuteShot ($07:$5413-$541c). Scales the shot speed in AddChargeSpeedBonus / AddChargeSpeedBonusHalf ($07:$5345, $535c, both offsetting by $ffe0 first) and in WeakenShotByCharge / BoostShotByCharge ($07:$54de, $54ed); $08:$53f9 compares it against $3f (fully charged) to pick the special hit flash instead of the normal spark.
wShotChargeLevel:: db
	ds 2

; [8-bit] Nonzero when the shot just struck counts as a special/power hit. Cleared at the top of ExecuteShot ($07:$53e6); set to 1 at $07:$59f8 when the ball is struck above height $0140, and set from the 32-entry toss-height table at $07:$5a1c on the serve paths. Read at $08:$53f3, where it forces the special-shot flash (wSpecialHitTimer) instead of the normal swing spark, and at $08:$42d4, where a nonzero value on the first shot of the rally shows court banner $0e.
wSpecialShotFlag:: db
	ds 1

; [8-bit] 0/1 parity flag: when 1, the shot's lateral aim offsets are negated. Written by ExecuteShot ($07:$540d) as the low bit of a count of four conditions (hitter state $df15 == 6, == $0a, $df94 nonzero, wRallyLength == 0). Read by LoadShotPlacementEntry ($07:$52b5) to negate the placement entry's angle offset before storing it at $c41e, and by every court bank's SetBallVelocityFromEntry6 ($20:$406a, $2a:$40c7 and the same offsets in the other court banks) to negate the table entry's angle delta before adding it to wShotAimAngle.
wShotAimMirror:: db

; [8-bit] Frames left of the ball-bounce dust effect (starts at $14)
wBounceEffectTimer:: db

; [8-bit] Frames left of the normal swing-hit spark (starts at $10)
wHitSparkTimer:: db

; [8-bit] Frames left of the special-shot hit flash (starts at $10; drives the bank $28 screen effect)
wSpecialHitTimer:: db

; [8-bit] Frames left of the 'ball hit a character' effect; started at $28 by StartBallTouchCharEffect ($08:$547c), ticked and used as an animation-table index by DrawBallTouchCharEffect ($08:$5482-$54bb).
wBallTouchCharTimer:: db

; [8-bit] Court surface horizontal bounce damping (8-bit fraction, e.g. $cd = 0.80 on court 0). Loaded per court from the 4-byte-per-court table at $08:$5dc4 ($08:$5e3e). ApplyCourtBounceDamping ($08:$46b3, $46c5) multiplies both horizontal velocity triples ($c420 = X, $c423 = depth) by it.
wCourtSurfaceFriction:: db

; [8-bit] Court surface vertical restitution (8-bit fraction), loaded from the same per-court record at $08:$5e42. ApplyCourtBounceDamping ($08:$46d7) multiplies the height velocity triple $c426 by it.
wCourtSurfaceBounce:: db

; [8-bit] Set to 1 at $08:$6f30 when the ball reaches a character's body (the same site sets bit 2 of $df50 and forces the character to state 0). HandleBallTouchCharEvent ($08:$43d3) consumes it once per frame: clears it, plays sound $77, starts the effect and calls ApplyBallTouchOutcome. Cleared by ResetPointState ($08:$4cc6).
wBallTouchCharFlag:: db

; [8-bit] Character index (0-3) of the character the ball touched, stored from wCharIndex alongside wBallTouchCharFlag at $08:$6f36. DrawBallTouchCharEffect ($08:$5487) maps it through CharIndexToWramBank to read that character's screen position; $08:$5dbc turns its low bit into the +1/-1 side sign for the point outcome.
wBallTouchCharIndex:: db

; [8-bit] Which quadrant of the court the ball is currently over: bit 1 = sign of wBallDepth (which side of the net), bit 0 = sign of wBallX (which half laterally). Rebuilt every frame by StepBallPhysics ($08:$5798-$57a9) by rotating the two sign bits into b; forced to $02 by the bank $0d wall-practice setup ($0d:$480f).
wBallCourtQuadrant:: db
	ds 1

; [8-bit] Number of bounces since the last time the ball was struck, saturating at $0a. Zeroed by HandleBallHitEvent ($08:$42c5) and by ResetPointState ($08:$4cbd); incremented by HandleBallBounceEvent ($08:$4360-$4368). Read as 'first bounce' (== 1) by EvaluateBounceOutcome ($08:$4389), the fault check ($08:$4342), the drill graders in bank $0b ($41e6, $5e55, $6d75, $721f) and $0d:$47d0.
wBallBounceCount:: db

; [8-bit] Per-frame bounce event code, cleared at the top of StepBallPhysics ($08:$5768): 1 = the ball reached the ground this frame ($08:$57e8, set right after GetBallHeightSign), 2 = the ball bounced off a court fence/wall ($08:$597e and $08:$59b4, inside BounceBallOffCourtFences after ApplyCourtBounceDamping). HandleBallBounceEvent ($08:$4352) returns immediately when it is 0.
wBallBounceEvent:: db

; [8-bit] Set to 1 for the single frame in which the ball crosses the net plane; cleared at the top of HandleBallNetCrossing ($08:$5815) and set at $08:$5827 once the wBallDepth sign flip is detected. Read by TickRallyTimers ($08:$4242), by AiTrackBallPhase ($08:$7d77) and by the minigame target checks CheckBallHitsMinigameTarget ($0a:$672d) and CheckBallHitsMinigameTargetAlt ($0a:$6df4).
wBallCrossedNetFlag:: db
	ds 1

; [8-bit] Rally Length; number of times the ball was hit in the span of a point
wRallyLength:: db

; [8-bit] Set to 1 by ExecuteShot ($07:$53b8), which also refuses to run twice while it is set ($07:$53b0-$53b5). HandleBallHitEvent ($08:$427a) consumes it once per frame: increments wRallyLength, clears it, clears wBallHasBouncedFlag and wLandingMarkerActive, then starts the landing marker and hit effect and pokes every character's state. Cleared by ResetPointState ($08:$4cc3).
wBallHitEvent:: db

; [8-bit] Character index (0-3) of the character who hit the ball, snapshotted from wCharIndex by ExecuteShot ($07:$53be). Used at $08:$5cb2 to select the wCharacterN stat block (index * 8) when crediting an ace/winner, at $08:$5da9 to turn the low bit into the point-outcome side sign, and by the bank $0d minigames ($4e80, $5292, $56f0) to test whether the player or the machine hit.
wLastShotCharIndex:: db

; [8-bit] wCharServeRole of the character who hit the ball, snapshotted by ExecuteShot ($07:$53c4). Read once, at $08:$4337, where role 1 (the server) selects point outcome 7 (fault) instead of 8 when the ball goes out on the first bounce.
wLastShotServeRole:: db

; [8-bit] Nonzero draws the ball sprite slot
wBallSpriteEnabled:: db

; [8-bit] Nonzero draws the ball ground-shadow slot
wBallShadowEnabled:: db

; [8-bit] Nonzero draws the ball trail afterimages from the position history ring
wBallTrailEnabled:: db

; [8-bit] Trail palette index into BallTrailPalettes; nonzero also extends the trail from 2 to 5 ghosts
wBallTrailColor:: db

; [8-bit] wBallCourtQuadrant captured at the moment the shot was struck ($07:$53df-$53e2). EvaluateBounceOutcome XORs it against the live wBallCourtQuadrant and tests bit 1 ($08:$4394-$439b, did the ball reach the other side of the net) and bit 0 ($08:$43b4-$43bb, did it change lateral half - the serve's diagonal-box rule). The bank $0d wall-practice bounce flips its bit 1 manually at $0d:$4b7c.
wBallQuadrantAtHit:: db

; [8-bit] Set to 1 when the ball bounces on the court ($08:$5848, in the net-crossing/ground-contact path that also fires StartBounceEffect); cleared by HandleBallHitEvent ($08:$428c) and ResetPointState ($08:$4cc9). Read by EvaluateBounceOutcome ($08:$43c3), by TickRallyTimers ($08:$4262) and by AiTrackBallPhase ($08:$7d73).
wBallHasBouncedFlag:: db

; [8-bit] Nonzero freezes the per-frame match simulation: UpdateMatchFrame skips ClearSpriteSlots/UpdateMatchCamera/UpdateAllChars/ball events/UpdateBallVisuals/timers and the mode hook. Set $ff during match setup and while the pause menu is open, cleared before the play loop
wMatchSimFrozen:: db

; [8-bit] Nonzero freezes actor drawing: UpdateMatchFrame skips DrawActorsByDepth. Set $ff alongside wMatchSimFrozen while the pause menu is open
wMatchDrawFrozen:: db

; [8-bit] Nonzero blocks the pause menu: HandlePauseMenu ($08:$449c) returns immediately when it is set. Set to 1 during match setup ($08:$40d2), for the whole changeover sequence (RunChangeoverSequence $08:$5f8e) and while the characters walk off court (WalkCharsOffCourt $08:$6012); cleared by ResetPointState ($08:$4ce3) and by PlayMinigameCountdown ($0d:$48d5).
wPauseDisabled:: db

; [8-bit] $ff = abort the match (bit 7 breaks the point/game/set/match loops); set by every pause/quit-menu action, cleared per point by ResetPointState
wMatchAbortFlag:: db

; [8-bit] Nonzero draws edge arrows for off-screen characters (set during the rally)
wOffscreenArrowsEnabled:: db
	ds 1

; [8-bit] Set to 1 by ApplyFallbackBallTrajectory_24 ($24:$57ff), the shared handler the court banks jump to when the requested trajectory row is out of range; cleared at the top of ExecuteShot ($07:$53ec). Read by StartLandingMarker ($08:$52e1), which then draws the lob landing marker, and by AiIsIncomingLobShot ($08:$79e7), which treats it like SHOTTYPE_LOB.
wFallbackTrajectoryFlag:: db

; [8-bit] Nonzero when the player chose Retry / Select New Level / Quit in the quit menu (discriminated by wMatchRetryRequest/wMatchSelectNewLevelRequest); outer mode loops branch on it
wMatchExitRequest:: db
	ds 1

; [8-bit] Nonzero makes UpdateMatchCamera ($08:$61dc) overwrite the camera target from wBallGroundProjX/Y each frame instead of holding the target set by SetCameraTarget. Cleared by SetCameraTarget and SnapCameraTo ($08:$61c5, $61d8, $0d:$4955); set to 1 when the rally starts ($08:$425f), by the bank $0d wall bounce ($0d:$4b72), and explicitly cleared by KeepMinigameCameraFixed ($0d:$47be).
wCameraFollowBall:: db

; [8-bit] Set in singles only; enables the wide flickering ground shadow under grounded characters
wStandingShadowsEnabled:: db

; [8-bit] Nonzero when the court view is mirrored so the human player stays on the near side. Recomputed by UpdateViewFlipState ($08:$4c33-$4c4a) as (wCourtViewOption != 0) && (bit 1 of $c8cf). FlipAllCharPositions ($08:$4c4e) skips flipping every character's court-position code when it is 0, and RefreshCourtScoreboard ($08:$5e99) picks the mirrored scoreboard column layout when it is set.
wCourtViewFlipped:: db
	ds 1

; [8-bit] Set to 1 at $08:$4c2f when bit 1 of the game-count state $c8cf toggles, i.e. the players must change ends. RunChangeoverSequence ($08:$5f97) shows court banner $00 and walks the characters to their new ends when it is set, then clears it with $c4cc at $08:$5fb8; also cleared during match setup ($08:$4177).
wChangeEndsPending:: db

; [8-bit] Nonzero when wCourtViewFlipped changed on the last UpdateViewFlipState pass - computed there as old minus new ($08:$4c44-$4c4a). RefreshCourtAfterEndChange ($08:$5f43) returns immediately when it is 0, and ReinitPointAfterPause ($08:$44c5) uses it to decide whether the court needs redrawing after the pause menu.
wCourtViewFlipChanged:: db

; [8-bit] wOnCourtCharCount - 1 (0x00-0x03); jumptable index for the match engine's per-character-count dispatches
wOnCourtCharCountMinus1:: db

; [8-bit] Set when the point ended as a service ace (point outcome 6 with rally length 1); credited to the winner's ServiceAces stat
wServiceAceFlag:: db

; [8-bit] Set when the point ended as a return ace (point outcome 6 with rally length 2); credited to the winner's ReturnAces stat
wReturnAceFlag:: db

; [8-bit] WRAM bank (4-7) of the character currently serving, stored by IdentifyServingPlayer ($08:$4c83) from FindServerCharBank. Read once, at $08:$44dc, where ReinitPointAfterPause maps that bank in to put the server back into the serve state.
wServingCharWramBank:: db

; [8-bit] Current Serving Player (0x00-0x03)
wCurrentServingPlayer:: db

; [8-bit] wCharCourtPos of the serving character, stored by IdentifyServingPlayer ($08:$4c8f). Bit 1 (which side of the net the server is on) selects the serve camera target in GetServeCameraTarget ($08:$6199) and the ace-banner offset at $08:$42df; bank $09 uses the whole value as the serve-indicator object template index ($09:$4248, $4261, $4310) and mixes it with wServeFaultFlag at $09:$6c54.
wServingCharCourtPos:: db

; [8-bit] Match-point indicator: $01/$ff = P1/P2 side wins the match by taking the next point, 0 = none (EvaluatePointSituation simulates the next point)
wMatchPointFlag:: db

; [8-bit] Set-point indicator ($01/$ff/0, same scheme as wMatchPointFlag)
wSetPointFlag:: db

; [8-bit] Game-point indicator ($01/$ff/0, same scheme as wMatchPointFlag)
wGamePointFlag:: db

; [8-bit] 0 while the rally runs; point-end cause code once the point resolves
wPointOutcome:: db

; [8-bit] Side/sign code stored alongside wPointOutcome when a point-ending event fires ($01/$ff); negated through the court-side parity bits to decide which side won the point
wPointOutcomeSide:: db

; [8-bit] Nonzero while the lob landing marker is shown. Set to 1 with sound $6d by StartLandingMarker ($08:$533c) right after it fills wLandingMarkerX/Y; DrawLandingMarker ($08:$5342) returns when it is 0. Cleared by HandleBallHitEvent ($08:$428f), HandleBallBounceEvent ($08:$436a), EndPointBallEffects ($08:$4fad), ResetPointState ($08:$4cd2) and $0d:$4bc9; the AI reads it at $08:$7b7b as 'a lob is coming'.
wLandingMarkerActive:: db

; [8-bit] wMatchTypeNumberOfSets >> 1, stored during match setup ($08:$4120). ShowMatchRulesPages ($06:$4137) combines it as (this * 2 + wRulesGamesIndex) to form wRulesPageListIndex, selecting one of the six MatchRulesPageLists records.
wRulesSetsIndex:: db

; [8-bit] Bit 2 of wMatchTypeNumberOfGames, stored during match setup ($08:$412a); the low half of the wRulesPageListIndex computation at $06:$4133.
wRulesGamesIndex:: db

; [8-bit] The saved 'camera / court view' option. Loaded from story save-slot flag B at $08:$4526 (forced to 0 for minigames and game mode 8 at $08:$4530), edited by MatchPauseMenu_CameraSelect ($06:$441e/$4433, which writes it back with SetStorySlotFlagB). UpdateViewFlipState ($08:$4c35) only mirrors the court when it is nonzero.
wCourtViewOption:: db

; [8-bit] Set to 1 by MatchQuitMenu_Retry; reruns the current drill/minigame (RunTrainingDrillByID)
wMatchRetryRequest:: db

; [8-bit] Set to 1 by MatchQuitMenu_SelectNewLevel; returns to the level-select screen after the match teardown
wMatchSelectNewLevelRequest:: db

; [8-bit] Pause/quit menu selection (rst00 jumptable index: check rules / review controls / change options / save-quit); $ff = cancelled
wMatchMenuSelection:: db

; [8-bit] Item id of the first entry of the story option submenu about to be drawn ($04 court view, $06 message speed, $09 music, $0b save; $0e for the story pause root at $06:$6fec). RunStoryTwoOptionMenu ($06:$70cc) and RunStoryThreeOptionMenu ($06:$717a) draw this id, +1 and +2, add wMatchMenuSelection to it to pick the caption text ($0162 + n) and to load the highlighted item graphics.
wStoryMenuFirstItem:: db

; [8-bit] Nonzero means the shadow tilemap needs flushing to VRAM. FlushTilemapToVramIfDirty ($06:$45f3) returns when it is 0 and FlushTilemapToVram clears it at $06:$45f9; set to 1 by the debug stats editor after redrawing ($06:$6c0f).
wTilemapDirtyFlag:: db

; [16-bit] Packed base position of the match scoreboard layout (low byte $c4e3, high byte $c4e4), added to the fixed offsets of each element. Set by PrepareScoreboardGfx ($06:$4917/$491c, to $0002 or $0202 depending on wScoreboardLayout) and to 5 in the low byte by ShowMatchScoreboardScreen ($06:$48bb). Read as a coordinate pair by all four ScoreboardCaption_* handlers ($06:$478e, $47a1, $47b4, $47df), by DrawScoreboard ($06:$49a8), by the pip drawers ($06:$4a13, $4a3d, $4a57) and, as h/l shifted left 3, by the sprite helpers Func_06_506a ($06:$506a) and Func_06_69c8 ($06:$69ca).
wScoreboardOrigin:: dw

; [8-bit] Which rules/description page list to display. Set by ShowMatchRulesPages ($06:$413c, from wRulesSetsIndex/wRulesGamesIndex), ShowTrainingRulesPages ($06:$4180, from wCurrentMinigameStoryMatch+1) and the minigame variant at $06:$422a (drill id * 3 + wMinigameLevel). Each of those then indexes a 4-byte-per-record page list (MatchRulesPageLists at $06:$4165 and its siblings) with it.
wRulesPageListIndex:: db

; [8-bit] Which menu_def record the pause menu system should run. Set before every RunMatchMenu / RunMatchQuitMenu / RunStoryMenu call in bank $06 ($06:$404c, $40c7, $43fd, $4426, $4443, $4470, $447b, $6fc9, $6ff1). GetMatchMenuItemCount ($06:$4820) and GetStoryMenuItemCount ($06:$6d8a) both index their 8-byte menu_def tables with it.
wPauseMenuId:: db

; [8-bit] Number of items in the menu currently being run. RunMatchMenu ($06:$46ea) and RunStoryMenu ($06:$6d13) store the result of Get*MenuItemCount here; it is the wrap modulus passed to MoveCursorHorizontal ($06:$4724, $6d3e), the loop counter in DrawMatchMenuItems / DrawStoryMenuItems ($06:$483d, $6da7) and the index into the per-count item-position tables ($06:$482f, $4873, $6d99, $6ddd).
wPauseMenuItemCount:: db

; [16-bit] Text id of the first body page of the rules sequence being shown ($2c62 for match rules at $06:$414f, $2c6a for training rules at $06:$4193, or a per-minigame value loaded from a table at $06:$424a). ShowRulesPageSequence adds the current page number to it at $06:$4342 to get the page's text id.
wRulesFirstPageTextId:: dw

; [16-bit] Text id of the caption/title shown above the rules pages, computed as a fixed base plus wRulesPageListIndex ($2c25 + n at $06:$4146, $2c2b + n at $06:$418a, $2c47 + n at $06:$4234). Read at $06:$432d and passed to DrawMenuCaptionWindow.
wRulesTitleTextId:: dw

; [16-bit] The saved best score for the current minigame, copied out of the record ReadMinigameRecord returns in WRAM bank 7 at $de00 ($0d:$4107). $06:$50cf draws it instead of wMinigamesTargetScore when $c7bc marks a high-score attempt, and $0d:$41fc compares the current score against it.
wMinigameHighScore:: dw

; [8-bit] Flag byte for the built-in debug test match; set to $fe by RunDebugTestMatch ($07:$5e9a). Bit 1 makes the character setup call OverrideCharStatsForDebug ($07:$5c35); bit 0 makes the frame-stepping loop at $08:$4447 ignore the input wait.
wDebugMatchFlags:: db
	ds 273

; Dialogue string buffer (160 bytes); text-bank fetch routines copy string N here when called with a = 0
wTextBuffer:: db
	ds 191

; 32-byte staging buffer for inline text args (player name, arg strings, short texts) rendered via RenderInlineString
wInlineTextBuffer:: ds 32
	ds 160

; Mode-local scratch ($c780-$c78f is reused by each game mode;
; only proven consumers are named, sites in other modes stay numeric)
UNION
; character select (bank $1b)
	ds 1
; [8-bit] Character id under the char-select cursor, looked up from the roster grid at $c7a0 by UpdateCharSelectSelection
wCharSelectChar:: db
; [8-bit] Character id selected on the previous frame (change detection)
wCharSelectPrevChar:: db
; [8-bit] Char-select cursor column in the roster grid
wCharSelectCol:: db
; [8-bit] Char-select cursor row in the roster grid
wCharSelectRow:: db
ENDU

	ds 7

; [8-bit] Nonzero draws the 4-corner court target zone (training drills)
wTargetZoneEnabled:: db
	ds 3

; [16-bit] Target zone X bound 1 (world units)
wTargetZoneX1:: dw

; [16-bit] Target zone depth bound 1 (world units)
wTargetZoneDepth1:: dw

; [16-bit] Target zone X bound 2 (world units)
wTargetZoneX2:: dw

; [16-bit] Target zone depth bound 2 (world units)
wTargetZoneDepth2:: dw
	ds 26

; [16-bit] Pointer to the current game mode's callback table (indexed by CallModeHook)
wModeHookTable:: dw

; [8-bit] ROM bank of the mode callback table (0 = no hooks registered)
wModeHookBank:: db
	ds 75

; [buffer] Base of the story-slot state image (WRAM $c800-$caff): the live region holding the wStoryModeMainCharacter*/wGameMode/match-settings/roster fields, saved wholesale as save block 2N (see docs/save_format.md) and reloaded from it on slot load
wStorySlotData:: db
	ds 23

; [8-bit] Story Mode - Main Character Level (0x01-0x63)
wStoryModeMainCharacterLevel:: db
	ds 7

; [8-bit] Story Mode - Main Character Top Stat (0x00-0x09)
wStoryModeMainCharacterTopStat:: db

; [8-bit] Story Mode - Main Character Slice Stat (0x00-0x09)
wStoryModeMainCharacterSliceStat:: db

; [8-bit] Story Mode - Main Character Serve Stat (0x00-0x09)
wStoryModeMainCharacterServeStat:: db

; [8-bit] Story Mode - Main Character Stroke Stat (0x00-0x09)
wStoryModeMainCharacterStrokeStat:: db

; [8-bit] Story Mode - Main Character Volley Stat (0x00-0x09)
wStoryModeMainCharacterVolleyStat:: db

; [8-bit] Story Mode - Main Character Angle Stat (0x00-0x09)
wStoryModeMainCharacterAngleStat:: db

; [8-bit] Story Mode - Main Character Placement Stat (0x00-0x09)
wStoryModeMainCharacterPlacementStat:: db

; [8-bit] Story Mode - Main Character Speed Stat (0x00-0x09)
wStoryModeMainCharacterSpeedStat:: db

; [8-bit] Story Mode - Main Character Dash Stat (0x00-0x09)
wStoryModeMainCharacterDashStat:: db

; [8-bit] Story Mode - Main Character Reaction Stat (0x00-0x09)
wStoryModeMainCharacterReactionStat:: db

; [8-bit] Story Mode - Main Character Stop Stat (0x00-0x09)
wStoryModeMainCharacterStopStat:: db
	ds 1

; [16-bit] Story Mode - Main Character EXP
wStoryModeMainCharacterEXP:: dw
	ds 10

; [8-bit] Story Mode - Main Character Spin Level
wStoryModeMainCharacterSpinLevel:: db

; [8-bit] Story Mode - Main Character Power Level
wStoryModeMainCharacterPowerLevel:: db

; [8-bit] Story Mode - Main Character Control Level
wStoryModeMainCharacterControlLevel:: db

; [8-bit] Story Mode - Main Character Speed Level
wStoryModeMainCharacterSpeedLevel:: db
	ds 28

; [8-bit] Story Mode - Partner Character Level (0x01-0x63)
wStoryModePartnerCharacterLevel:: db
	ds 7

; [8-bit] Story Mode - Partner Character Top Stat (0x00-0x09)
wStoryModePartnerCharacterTopStat:: db

; [8-bit] Story Mode - Partner Character Slice Stat (0x00-0x09)
wStoryModePartnerCharacterSliceStat:: db

; [8-bit] Story Mode - Partner Character Serve Stat (0x00-0x09)
wStoryModePartnerCharacterServeStat:: db

; [8-bit] Story Mode - Partner Character Stroke Stat (0x00-0x09)
wStoryModePartnerCharacterStrokeStat:: db

; [8-bit] Story Mode - Partner Character Volley Stat (0x00-0x09)
wStoryModePartnerCharacterVolleyStat:: db

; [8-bit] Story Mode - Partner Character Angle Stat (0x00-0x09)
wStoryModePartnerCharacterAngleStat:: db

; [8-bit] Story Mode - Partner Character Placement Stat (0x00-0x09)
wStoryModePartnerCharacterPlacementStat:: db

; [8-bit] Story Mode - Partner Character Speed Stat (0x00-0x09)
wStoryModePartnerCharacterSpeedStat:: db

; [8-bit] Story Mode - Partner Character Dash Stat (0x00-0x09)
wStoryModePartnerCharacterDashStat:: db

; [8-bit] Story Mode - Partner Character Reaction Stat (0x00-0x09)
wStoryModePartnerCharacterReactionStat:: db

; [8-bit] Story Mode - Partner Character Stop Stat (0x00-0x09)
wStoryModePartnerCharacterStopStat:: db
	ds 1

; [16-bit] Story Mode - Partner Character EXP
wStoryModePartnerCharacterEXP:: dw
	ds 10

; [8-bit] Story Mode - Partner Character Spin Level
wStoryModePartnerCharacterSpinLevel:: db

; [8-bit] Story Mode - Partner Character Power Level
wStoryModePartnerCharacterPowerLevel:: db

; [8-bit] Story Mode - Partner Character Control Level
wStoryModePartnerCharacterControlLevel:: db

; [8-bit] Story Mode - Partner Character Speed Level
wStoryModePartnerCharacterSpeedLevel:: db
	ds 40

; [8-bit] Message Speed
;
; 0x00 - Fast
; 0x01 - Normal
; 0x02 - Slow
wMessageSpeed:: db
	ds 1

; [8-bit] Game Mode
;
; 0x00 - Not playing tennis
; 0x01 - Story Mode - Ranking Match
; 0x02 - Story Mode - Island Open Match
; 0x03 - Story Mode - Practice Match
; 0x04 - Exhibition Mode
; 0x05 - Story Mode - Training Court Minigames
; 0x06 - Story Mode - Tennis Machine
; 0x07 - Story Mode - Wall Practice
; 0x08 - Mario Minigames
; 0x0a - Story Mode - Dream Match
wGameMode:: db

; [8-bit] Nonzero makes ResetMatchState skip clearing the per-character match stats (set by MatchQuitMenu_SaveAndQuit so a resumed match keeps its stats); cleared after use
wKeepMatchStatsFlag:: db
	ds 24

; [8-bit] Character 1 Service Aces
wCharacter1ServiceAces:: db

; [8-bit] Character 1 Return Aces
wCharacter1ReturnAces:: db

; [8-bit] Character 1 Smash Aces
wCharacter1SmashAces:: db

; [8-bit] Character 1 Lob Shot Winners
wCharacter1LobShotWinners:: db

; [8-bit] Character 1 Drop Shot Winners
wCharacter1DropShotWinners:: db

; [8-bit] Character 1 Faults
wCharacter1Faults:: db

; [8-bit] Character 1 Double Faults
wCharacter1DoubleFaults:: db
	ds 1

; [8-bit] Character 2 Service Aces
wCharacter2ServiceAces:: db

; [8-bit] Character 2 Return Aces
wCharacter2ReturnAces:: db

; [8-bit] Character 2 Smash Aces
wCharacter2SmashAces:: db

; [8-bit] Character 2 Lob Shot Winners
wCharacter2LobShotWinners:: db

; [8-bit] Character 2 Drop Shot Winners
wCharacter2DropShotWinners:: db

; [8-bit] Character 2 Faults
wCharacter2Faults:: db

; [8-bit] Character 2 Double Faults
wCharacter2DoubleFaults:: db
	ds 1

; [8-bit] Character 3 Service Aces
wCharacter3ServiceAces:: db

; [8-bit] Character 3 Return Aces
wCharacter3ReturnAces:: db

; [8-bit] Character 3 Smash Aces
wCharacter3SmashAces:: db

; [8-bit] Character 3 Lob Shot Winners
wCharacter3LobShotWinners:: db

; [8-bit] Character 3 Drop Shot Winners
wCharacter3DropShotWinners:: db

; [8-bit] Character 3 Drop Shot Winners
wCharacter3DropShotWinners2:: db

; [8-bit] Character 3 Double Faults
wCharacter3DoubleFaults:: db
	ds 1

; [8-bit] Character 4 Service Aces
wCharacter4ServiceAces:: db

; [8-bit] Character 4 Return Aces
wCharacter4ReturnAces:: db

; [8-bit] Character 4 Smash Aces
wCharacter4SmashAces:: db

; [8-bit] Player 4 Lob Shot Winners
wPlayer4LobShotWinners:: db

; [8-bit] Character 4 Drop Shot Winners
wCharacter4DropShotWinners:: db

; [8-bit] Character 4 Faults
wCharacter4Faults:: db

; [8-bit] Character 4 Double Faults
wCharacter4DoubleFaults:: db

; [8-bit] Match RNG state: seeded from hVBlankCounter at match start, stirred by AdvanceMatchRng (+$73 plus ball position bytes)
wMatchRngState:: db

; [8-bit] Player 1 Sets Won (0x00-0x03)
wPlayer1SetsWon:: db

; [8-bit] Player 2 Sets Won (0x00-0x03)
wPlayer2SetsWon:: db

; [8-bit] Player 1 Games Won (0x00-0x07)
wPlayer1GamesWon:: db

; [8-bit] Player 2 Games Won (0x00-0x07)
wPlayer2GamesWon:: db

; [8-bit] Player 1 Points Won
;
; 0x00 - 0
; 0x01 - 15
; 0x02 - 30
; 0x03 - 40
; 0x04 - Advantage/Deuce
; 0x05-0x07 - Tiebreaker only
wPlayer1PointsWon:: db

; [8-bit] Player 2 Points Won; for values see 0xc8e4
wPlayer2PointsWon:: db

; [8-bit] Deuce Indicator (0x01 when deuce, 0x00 otherwise)
wDeuceIndicator:: db

; [8-bit] Tiebreaker Indicator (0x01 when tiebreaker, 0x00 otherwise)
wTiebreakerIndicator:: db

; [8-bit] Match Win/Lose Flag (0x01 - win, 0xff - lose, 0x00 otherwise)
wMatchWinLoseFlag:: db

; [8-bit] Set Win/Lose Flag (0x01 - win, 0xff - lose, 0x00 otherwise)
wSetWinLoseFlag:: db

; [8-bit] Game Win/Lose Flag (0x01 - win, 0xff - lose, 0x00 otherwise))
wGameWinLoseFlag:: db

; [8-bit] Point Win/Lose Flag (0x01 - win, 0xff - lose, 0x00 otherwise)
wPointWinLoseFlag:: db

; [8-bit] Total Games Won In Match
wTotalGamesWonInMatch:: db

; [8-bit] Total Points Scored In Current Game
wTotalPointsScoredInCurrentGame:: db

; [8-bit] 1 after a first-serve fault (the next fault becomes a double fault, point outcome 2); cleared on double fault and at match reset
wServeFaultFlag:: db
	ds 1

; [8-bit] Match Type - Number Of Sets (0x01, 0x03, 0x05)
wMatchTypeNumberOfSets:: db

; [8-bit] Match Type - Number Of Games (0x02, 0x06)
wMatchTypeNumberOfGames:: db

; [8-bit] Nonzero when the current match is doubles; selects the wider court bound and 4 on-court characters
wMatchIsDoubles:: db

; [8-bit] Number of characters on court (2 singles, 4 doubles, 3 in Two-On-One); one banked WRAM struct each in banks 4-7
wOnCourtCharCount:: db

; [8-bit] Currently Used Court
;
; 0x00 - Hard Court
; 0x01 - Clay Court
; 0x02 - Grass Court (Exhibition)
; 0x03 - Composition Court
; 0x04 - Star Court
; 0x05 - Castle Court
; 0x06 - Tropics Court
; 0x07 - Jungle Court
; 0x08 - Warehouse Court
; 0x09 - Training Court (Practice)
; 0x0a - Tennis Machine
; 0x0b - Wall Practice
; 0x0c - Center Court (Island Open Finals)
; 0x0d - Grass Court (Island Open)
; 0x0f - Target Shot
; 0x10 - Shooting Star
; 0x11 - Banana Bunch
; 0x12 - Boo Blast
; 0x13 - Perfect Shot
; 0x14 - Treasure Box
; 0x15 - Medallion Match
; 0x16 - Fruit Fantasy
; 0x17 - Two-On-One
; 0x18 - Training Court (Match)
wCurrentlyUsedCourt:: db
	ds 1

; [16-bit BE] Current Minigame/Story Match
;
; 0x0000 - Singles Junior Practice Match
; 0x0001 - Singles Junior #4
; 0x0002 - Singles Junior #3
; 0x0003 - Singles Junior #2
; 0x0004 - Singles Junior #1
; 0x0005 - Singles Senior Practice Match
; 0x0006 - Singles Senior #4
; 0x0007 - Singles Senior #3
; 0x0008 - Singles Senior #2
; 0x0009 - Singles Senior #1
; 0x000a - Singles Varsity Practice Match
; 0x000b - Singles Varsity #4
; 0x0010 - Singles Island Open Round 1
; 0x0011 - Singles Island Open Round 2
; 0x0012 - Singles Island Open Semifinals
; 0x0013 - Singles Island Open Finals
; 0x0016 - Singles Dream Match (MAX)
; 0x0017 - Singles Dream Match (Intense)
; 0x0018 - Singles Dream Match (Hard/First time)
; 0x0100 - Doubles Junior Practice Match
; 0x0102 - Doubles Junior #3
; 0x0103 - Doubles Junior #2
; 0x0104 - Doubles Junior #1
; 0x0105 - Doubles Senior Practice Match
; 0x0107 - Doubles Senior #3
; 0x0108 - Doubles Senior #2
; 0x0109 - Doubles Senior #1
; 0x010a - Doubles Varsity Practice Match
; 0x010d - Doubles Varsity #2
; 0x0111 - Doubles Island Open Round 1
; 0x0112 - Doubles Island Open Semifinals
; 0x0113 - Doubles Island Open Finals
; 0x0116 - Doubles Dream Match (MAX)
; 0x0117 - Doubles Dream Match (Intense)
; 0x0118 - Doubles Dream Match (Hard/First time)
; 0x0200 - Service Match 1
; 0x0201 - Service Match 2
; 0x0202 - Service Match 3
; 0x0203 - Service Practice 1
; 0x0204 - Service Practice 2
; 0x0205 - Service Practice 3
; 0x0206 - Net Play Match 1
; 0x0207 - Net Play Match 2
; 0x0208 - Net Play Match 3
; 0x0209 - Net Play Practice 1
; 0x020a - Net Play Practice 2
; 0x020b - Net Play Practice 3
; 0x020c - Stroke Match 1
; 0x020d - Stroke Match 2
; 0x020e - Stroke Match 3
; 0x020f - Stroke Practice 1
; 0x0210 - Stroke Practice 2
; 0x0211 - Stroke Practice 3
; 0x0212 - Tennis Machine 1
; 0x0213 - Tennis Machine 2
; 0x0214 - Tennis Machine 3
; 0x0215 - Tennis Machine 4
; 0x0216 - Wall Practice 1
; 0x0217 - Wall Practice 2
; 0x0218 - Wall Practice 3
; 0x0219 - Wall Practice 4
; 0x021a - Tennis Machine High Score
; 0x021b - Wall Practice High Score
; 0x021c - Boo Blast
; 0x021d - Shooting Star
; 0x021e - Perfect Shot
; 0x021f - Target Shot
; 0x0220 - Fruit Fantasy
; 0x0221 - Banana Bunch
; 0x0222 - Treasure Box
; 0x0223 - Medallion Match
; 0x0224 - Two-On-One
wCurrentMinigameStoryMatch:: dw

; [8-bit] BGM id (see wCurrentBGM values) played for the current match/court; tiebreak overrides it with $0e
wMatchBGM:: db
	ds 7

; [ASCII, 7 Bytes] Story Mode - Name of Main Character
wStoryModeNameOfMainCharacter:: ds 7
	ds 4

; [8-bit] Story Mode - Main Character Overworld Sprite
;
; 0x00 - Alex
; 0x01 - Nina
; 0x02 - Harry
; 0x03 - Kate
; Loops for all other values
wStoryModeMainCharacterOverworldSprite:: db

; [8-bit] Story Mode - Main Character Overworld Sprite Color
;
; 0x00 - Green
; 0x01 - Pink
; 0x02 - Yellow
; 0x03 - Red
; 0x04 - Blue
; All other values result in glitched sprite
wStoryModeMainCharacterOverworldSpriteColor:: db

; [8-bit] Story Mode - main character's gender: $00 = male, $01 = female. Copied from StoryCharGenderTable by InitPlayerRecordFromTemplate ($02:$43db) and read-only thereafter. Proven by the dialogue pairs it selects via AdvanceDialogueTextCursor: $30:433 "Take good care of him, OK?" vs $30:434 "...of her, OK?" ($10:$7844), and $31:60 "He's , the Academy's newest student." vs $31:61 "She's ..." ($13:$49b8). Also picks the gendered overworld object defs ($56 + gender).
wStoryModeGenderOfMainCharacter:: db

; [8-bit] Story Mode - nonzero when the main character plays left-handed. Written from wCharSelectHandedness at $38:$48ba (record offset +$0e) and, on the bank $02 new-game path, from bit 2 of the character id ($02:$51c5). Bank $17 uses it to swap the spin-serve briefing text between $36:696 ("serve to the right with topspin and to the left with slice") and $36:697, its mirror image.
wStoryModeMainCharacterLeftHanded:: db
	ds 45

; [Lower4] Equipped Racket
;
; 0x0 - Normal Racket
; 0x1 - Large Racket
; 0x2 - Small Racket
; 0x3 - Iron Racket
; 0x4 - Gold Racket
; 0x5 - Silver Racket
; 0x6 - Drive Racket
;
; [Upper4] Equipped Shoes
;
; 0x0 - Normal Shoes
; 0x1 - Iron Shoes
; 0x2 - Light Shoes
wEquippedRacket:: db
	ds 3

; [ASCII, 7 Bytes] Story Mode - Name of Partner Character
wStoryModeNameOfPartnerCharacter:: ds 7
	ds 4

; [8-bit] Story Mode - Partner Character Overworld Sprite; for values see 0x00c90b
wStoryModePartnerCharacterOverworldSprite:: db

; [8-bit] Story Mode - Partner Character Overworld Sprite Color; for values see 0x00c90c
wStoryModePartnerCharacterOverworldSpriteColor:: db

; [8-bit] Story Mode - doubles partner's gender ($00 male, $01 female), the partner record's copy of the field at the $40 stride. Selects the partner object def ($58 + gender) and, with the main character's gender, the four-way scene key (main << 1) | (main XOR partner) that $13:$78c4 passes to RunStorySceneByMode.
wStoryModeGenderOfPartnerCharacter:: db

; [8-bit] Story Mode - the partner record's copy of the left-handed flag (record offset +$0e at the $40 stride); written by the same character-select path as wStoryModeMainCharacterLeftHanded.
wStoryModePartnerCharacterLeftHanded:: db
	ds 113

; Event flag bit-array; rst $20/$28/$30 set/clear/test wGameFlags[byte] with mask $80 >> bit
wGameFlags:: db
	ds 4

; [8-bit] Singles/Doubles Indicator (Story & Exhibition Mode)
;
; 0x00 - Singles
; 0x01 - Doubles
wSinglesDoublesIndicator:: db

; [Lower4] Story Mode - Match Completion Flags (1/6)
;
; Bit 0 - Doubles Island Open Round 1
; Bit 1 - Doubles Island Open Semifinals
; Bit 2 - Doubles Island Open Finals
; Bit 3 - Doubles Dream Match
wStoryModeMatchCompletionFlags1:: db

; [8-bit] Story Mode - Match Completion Flags (2/6)
;
; Bit 0 - Singles Island Open Round 1
; Bit 1 - Singles Island Open Round 2
; Bit 2 - Singles Island Open Semifinals
; Bit 3 - Singles Island Open Finals
; Bit 4 - Singles Dream Match
wStoryModeMatchCompletionFlags2:: db

; [8-bit] Story Mode - Match Completion Flags (3/6)
;
; Bit 7 - Doubles Junior Rank 3
; Bit 6 - Doubles Junior Rank 2
; Bit 5 - Doubles Junior Rank 1
; Bit 3 - Doubles Senior Rank 3
; Bit 2 - Doubles Senior Rank 2
; Bit 1 - Doubles Senior Rank 1
wStoryModeMatchCompletionFlags3:: db

; [Upper4] Story Mode - Match Completion Flags (4/6)
;
; Bit 7 - Doubles Varsity Rank 2
wStoryModeMatchCompletionFlags4:: db

; [8-bit] Story Mode - Match Completion Flags (5/6)
;
; Bit 7 - Singles Junior Rank 4
; Bit 6 - Singles Junior Rank 3
; Bit 5 - Singles Junior Rank 2
; Bit 4 - Singles Junior Rank 1
; Bit 3 - Singles Senior Rank 4
; Bit 2 - Singles Senior Rank 3
; Bit 1 - Singles Senior Rank 2
; Bit 0 - Singles Senior Rank 1
wStoryModeMatchCompletionFlags5:: db

; [Upper4] Story Mode - Match Completion Flags (6/6)
;
; Bit 7 - Singles Varsity Rank 4
wStoryModeMatchCompletionFlags6:: db

; [8-bit] Story Mode - Equipment Flags (1/2)
;
; Bit 6 - Large Racket
; Bit 5 - Small Racket
; Bit 4 - Iron Racket
; Bit 3 - Silver Racket
; Bit 2 - Gold Racket
; Bit 1 - Drive Racket
; Bit 0 - Iron Shoes
wStoryModeEquipmentFlags1:: db

; [Upper4] Story Mode - Equipment Flags (2/2)
;
; Bit 7 - Light Shoes
wStoryModeEquipmentFlags2:: db
	ds 10

; [8-bit] Story Mode - Minigame Completion Flags (1/4)
;
; Bit 7 - Service Match 1
; Bit 6 - Service Match 2
; Bit 5 - Service Match 3
; Bit 4 - Service Practice 1
; Bit 3 - Service Practice 2
; Bit 2 - Service Practice 3
; Bit 1 - Net Play Match 1
; Bit 0 - Net Play Match 2
wStoryModeMinigameCompletionFlags1:: db

; [8-bit] Story Mode - Minigame Completion Flags (2/4)
;
; Bit 7 - Net Play Match 3
; Bit 6 - Net Play Practice 1
; Bit 5 - Net Play Practice 2
; Bit 4 - Net Play Practice 3
; Bit 3 - Stroke Match 1
; Bit 2 - Stroke Match 2
; Bit 1 - Stroke Match 3
; Bit 0 - Stroke Practice 1
wStoryModeMinigameCompletionFlags2:: db

; [8-bit] Story Mode - Minigame Completion Flags (3/4)
;
; Bit 7 - Stroke Practice 2
; Bit 6 - Stroke Practice 3
; Bit 5 - Machine Level 1
; Bit 4 - Machine Level 2
; Bit 3 - Machine Level 3
; Bit 2 - Machine Level 4
; Bit 1 - Wall Level 1
; Bit 0 - Wall Level 2
wStoryModeMinigameCompletionFlags3:: db

; [Upper4] Story Mode - Minigame Completion Flags (4/4)
;
; Bit 7 - Wall Level 3
; Bit 6 - Wall Level 4
wStoryModeMinigameCompletionFlags4:: db
	ds 47

; [8-bit] Player 1 Current Main Character
;
; 0x00 - Alex
; 0x01 - Nina
; 0x02 - Harry
; 0x03 - Kate
; 0x04 - Allie
; 0x05 - Joy
; 0x06 - Brian
; 0x07 - Pam
; 0x08 - Bob
; 0x09 - Beth
; 0x0a - Fay
; 0x0b - Curt
; 0x0c - Mark
; 0x0d - Sean
; 0x0e - Sammi
; 0x0f - Elden
; 0x10 - Spike
; 0x11 - Emily
; 0x12 - B. Coz
; 0x13 - A. Coz
; 0x14 - Kevin (dummied out)
; 0x15 - Tennis Machine
; 0x16 - Allie 2 (never shows up?)
; 0x17 - Luigi
; 0x18 - Donkey Kong
; 0x19 - Baby Mario
; 0x1a - Mario
; 0x1b - Waluigi
; 0x1c - Yoshi
; 0x1d - Bowser
; 0x1e - Wario
; 0x1f - Peach
wPlayer1CurrentMainCharacter:: db
	ds 63

; [8-bit] Player 1 Current Partner Character; for values see 0xca0b
wPlayer1CurrentPartnerCharacter:: db
	ds 19

; [8-bit] Exhibition Mode - Player Partner Character Difficulty
;
; 0x00 - Easy
; 0x01 - Normal
; 0x02 - Hard
; 0x03 - Intense
wExhibitionModePlayerPartnerCharacterDifficulty:: db
	ds 43

; [8-bit] Player 2 Current Main Character; for values see 0xca0b
wPlayer2CurrentMainCharacter:: db
	ds 19

; [8-bit] Exhibition Mode - CPU Main Character Difficulty; for values see 0x00ca5f
wExhibitionModeCPUMainCharacterDifficulty:: db
	ds 43

; [8-bit] Player 2 Current Partner Character; for values see 0xca0b
wPlayer2CurrentPartnerCharacter:: db
	ds 19

; [8-bit] Exhibition Mode - CPU Partner Character Difficulty; for values see 0x00ca5f
wExhibitionModeCPUPartnerCharacterDifficulty:: db
	ds 32

; [8-bit] Story Mode - which of the two story character records the character-select / name-entry / char-data screens are acting on: 0 = main character, 1 = partner. Used as a $40-stride index into the wStoryModeMainCharacter*/wStoryModePartnerCharacter* pair (GetActiveStoryNameBuffer at $38:$73fa returns wStoryModeNameOfMainCharacter or ...OfPartnerCharacter straight off it).
wStoryCharacterSlot:: db
	ds 3

; [8-bit] Menu cursor column; MoveMenuCursor wraps it at the column count in b
wMenuCursorX:: db

; [8-bit] Menu cursor row; MoveMenuCursor wraps it at the row count in c
wMenuCursorY:: db

; [8-bit] Secondary menu cursor column (parallel to wMenuCursorX; second selection region of the shared menu-input handler)
wMenuCursor2X:: db

; [8-bit] Secondary menu cursor row (parallel to wMenuCursorY)
wMenuCursor2Y:: db

; [8-bit] Menu cursor lock flags: bit 0 / bit 1 freeze the primary / secondary cursor's movement (set on confirm) in the shared menu-input handler
wMenuCursorLockFlags:: db
	ds 2

; [8-bit] Which animated-tile set the shared UpdateAnimatedTiles frame task ($39:$4342) cycles: masked with $03 and used as the index into the two pointer tables at $39:$4403 and $39:$440b. Written (values $00-$03 only) by the screen setup routines that install the task: $10:$4f92 (main menu, 0), $17:$44a6/$44f5 (court diagram, 0), $17:$6f4c (1), $1b:$73e7 (1), $1e:$7333 (1), $3b:$44b3/$496d/$4d03/$5151 (0), $3b:$7a03 (star-chart results, 1), $3e:$49f7/$4abc/$4c2b (link screens, 0), $16:$4a18/$4a30 (match result: 2 on win, 3 on lose, alongside the matching palette load).
wAnimatedTileSet:: db

; [8-bit] Frame period of the animated-tile task: $cb0a counts 0,1,..,period-1 and the animation only steps on the frame it wraps to 0 ($39:$434e-$4363). Written with $03 by almost every caller, $05 at $3e:$4ac1, $06 at $16:$4a6c.
wAnimatedTilePeriod:: db

; [8-bit] Menu loop's copy of hInputPressed (same bit layout as hPlayerInputFlags)
wMenuInputPressed:: db

; [8-bit] Match-format menu: singles (0) / doubles (1) selection; copied to wMatchIsDoubles
wMatchFormatDoubles:: db

; [8-bit] Match-format menu: games-per-set selection index; table-mapped to wMatchTypeNumberOfGames
wMatchFormatGames:: db

; [8-bit] Match-format menu: number-of-sets selection index (0-2); table-mapped to wMatchTypeNumberOfSets
wMatchFormatSets:: db

; [8-bit] Menu transition direction (1 = forward into submenu, 0 = back); direction arg to the *SlideIn/*SlideOut menu transitions
wMenuSlideDirection:: db
	ds 20

; [8-bit] Window handle owned by bank $1a's menu code. Stored from the return value of CreateMenuWindowFromText ($1a:$403c) and CreateWindow ($1a:$43c0), then passed in a to RunMenuSelectionShared ($1a:$404b), CloseWindow ($1a:$4070, $1a:$444d), WriteStringToWindow ($1a:$43df/$43f9) and GetWindowStructPtr ($1a:$4149).
wPauseMenuWindowId:: db

; [8-bit] Preset cursor row for the next RunMenuSelectionShared ($05:$4aa8) call: at menu open it is copied into the live row variable ($d830, WRAM bank $05) and then cleared to 0 ($05:$4ad1-$4ad8), so it defaults to row 0. Bank $1a writes the last selected row here ($1a:$41b8/$41ca/$4203/$4232) before rebuilding the pause menu so re-entry restores the cursor; $1a:$4093 clears it when the menu closes for good.
wMenuInitialRow:: db

; [8-bit] Per-row mask of menu rows on which LEFT/RIGHT act as a value adjust: bit 7 = mask present, bits 0-6 = one bit per row (tested by rotating right ($d830)+1 times, $05:$4c77-$4c8e and $05:$4ca3-$4cba). Gates the LEFT/RIGHT branch of the menu driver (Func_05_4c76, called at $05:$4bd5) and makes AnimateMenuScrollArrowsTask draw the left/right arrows on that row. Set by bank $1a: $83 (rows 0-1) for the pause menu at $1a:$4249, $8c (rows 2-3) for the minigame pause menu at $1a:$4386; cleared at $1a:$4096.
wMenuAdjustRowMask:: db

; [8-bit] Per-row mask (same bit7-present + rotate-by-row encoding as $cb28) of menu rows that must NOT close the menu window when chosen: after RunMenuSelectionShared returns, $1a:$4057-$406e tests the bit for the chosen row and jumps past the CloseWindow call at $1a:$4070 when set. Written with the same values as $cb28 ($83 at $1a:$424e, $8c at $1a:$4389); cleared at $1a:$409c.
wMenuKeepOpenRowMask:: db
	ds 3

; [8-bit] Study Vocabulary / Tennis Dictionary screen (bank $3f): index of the first entry shown in the 6-row scrolling term list. Absolute entry = ($cb2d + $cb2e) mod $cb2f (Func_3f_517b, $3f:$5181). Advanced/wrapped against $cb2f when the cursor runs off the top/bottom ($3f:$56d6-$56e2, $3f:$5700-$570c), recomputed by the page-jump helpers Func_3f_5192/Func_3f_520f, and used as the render start in Func_3f_5261 ($3f:$528d). Cleared on screen entry at $3f:$40c8.
wTennisDictScrollTop:: db

; [8-bit] Study Vocabulary screen (bank $3f): cursor row within the visible page. On the scrolling term list it is clamped to 0-5 ($3f:$56c6-$56f8) and scrolls $cb2d past those limits; on the 9-cell category index page it is clamped to 0-8 ($3f:$55b0-$55de). Drives the highlight row (stride $80 = 4 tilemap rows, Func_3f_54c8) and the hand-cursor sprite Y (stride $10 px, $3f:$4f9a-$4fab). Cleared at $3f:$40cb and reset to 0 by the page-jump helpers ($3f:$51a2, $3f:$522c, $3f:$5495).
wTennisDictCursorRow:: db

; [8-bit] Study Vocabulary screen (bank $3f): number of list entries that pass the current category filter. Computed by Func_3f_50f7 ($3f:$5102-$5116) by counting bytes of SelectionMaskGrid_3f_539e that AND with $cb32 (up to the $40 terminator), and used as the wrap modulus for the scroll offset ($3f:$5181, $3f:$5700, $3f:$51ac).
wTennisDictEntryCount:: db
	ds 2

; [8-bit] Study Vocabulary screen (bank $3f): category filter mask. Set from the screen mode at $3f:$40be - $01/$02/$04/$08/$10 for modes 0-4, $1f (all categories) for mode 5 and any other value. Every list walk ANDs it against the per-entry category byte in SelectionMaskGrid_3f_539e to decide whether an entry is listed ($3f:$5102, $3f:$5295, $3f:$5339, $3f:$5422, $3f:$547c, $3f:$51a5, $3f:$522f, $3f:$5625).
wTennisDictCategoryMask:: db
	ds 1

; [8-bit] Study Vocabulary screen (bank $3f): the mode argument passed in a to TennisDictionaryScreen, stored at $3f:$4082. Modes 0-5 pick the category mask in $cb32 and open the term list directly; mode 6 (the only value used in the retail flow, $10:$54b8) opens the 9-cell category index page instead - checked at $3f:$40f0, $3f:$412a, $3f:$4ed4 (index-page sprite animation) and $3f:$56ab (B-button return code $10 vs $01).
wTennisDictMode:: db
	ds 2

; [8-bit] Study Vocabulary screen (bank $3f) display flags, cleared at $3f:$40c5. bit 0 = a description window is open: set at $3f:$5620 before CreateDialogueWindow, cleared at $3f:$5699/$413a, and freezes the hand-cursor animation counter $cb3e ($3f:$4f8c). bit 1 = the scrolling term list is on screen (set $3f:$414d/$41d0, cleared $3f:$421a for the index page); gates drawing of the cursor sprites ($3f:$4f85) and shifts the index-page sprites by $10 px ($3f:$4f1f/$4f3a/$4f55/$4f70). bit 2 / bit 3 = flash the left / right page arrow this frame - set on LEFT ($3f:$571b) and RIGHT ($3f:$5731), drawn from SpriteTemplate_3f_5006 at X $18 / $88 ($3f:$4fc9/$4fdc), and both cleared at the top of every input tick ($3f:$560a).
wTennisDictFlags:: db
	ds 7

; [8-bit] Bank $6b cutscene driver (intro/title/award ceremony): current step index, dispatched through the per-scene jumptable
wCutsceneStep:: db

; [8-bit] Bank $6b cutscene driver: frame counter for the current step; incremented per frame and compared against per-step thresholds to advance wCutsceneStep
wCutsceneStepTimer:: db

; [8-bit] Intro Cutscene Check (0x00 when in intro cutscene, 0x01 otherwise)
wIntroCutsceneCheck:: db

; [8-bit] Bank $6b cutscene driver: accumulated horizontal pan position, copied to hScrollX each frame
wCutsceneScrollX:: db
	ds 7

; [16-bit] Intro cutscene (bank $6b): world-space vertical scroll/camera position, little-endian. Initialised to $0120 at the start of scenes 00/12/19 ($6b:$41bf, $6b:$4916, $6b:$4c65) and decremented every frame by the per-frame delta table at $6b:$4cc1 indexed by wCutsceneStepTimer ($6b:$4caa-$4cbd). Consumers: ApplyCutsceneScrollToSpriteX ($6b:$5191) subtracts it from the sprite base coordinate that QueueSpriteTemplate treats as Y (the sp+0 slot, $00:$1ebf - so despite the existing label it is the Y axis), and SetCameraYFromScrollPos ($6b:$60d5) shifts it left 5 into wCameraY. $6b:$60fe uses ($cb48 - $cb4a) as the on-screen Y of the object drawn by QueueIntroSpriteBlock.
wIntroCutsceneScrollY:: dw
	ds 4

; [8-bit] Story-mode character-select screen (bank $38): handedness toggle, 0 = default, 1 = mirrored (left-handed). Cleared on entry ($38:$4815, $38:$4984, $38:$4a82) and flipped by START ($38:$48fc `xor $01`) - the on-screen prompt for that row is text 30:118 'START: Change Hands' ($38:$4b0c). When non-zero, Func_38_4bac sets bit 5 (OAM X-flip) in wCharSpriteSlot+1 for all four displayed characters ($38:$4c6f-$4ca6), and Func_38_4e23 draws the marker sprite with tile base $00 instead of $02 ($38:$4e3c). The chosen value is written into the story character record at +$0e ($38:$48ba).
wCharSelectHandedness:: db
	ds 1

; [8-bit] Story-mode character-select screen (bank $38): which pick is in progress - 0 = main character, 1 = partner. Stored from the b argument of RunCharacterSelectScreen ($38:$47d0; callers pass 0 at $10:$40bb and $1b:$61fa, 1 at $1b:$629b). Selects the prompt text (0 -> text 30:117 'Pick a Character' at $38:$4ae8, 1 -> text 30:119 'Choose Partner' at $38:$4afb), swaps in mugshots 2/3 and repositions the two character sprites ($38:$4a27, $38:$4c13), and is doubled into the character id: id = 2*$cb52 + cursor ($38:$4896, $38:$4958, $38:$4e09).
wCharSelectIsPartner:: db

; [8-bit] Court-select: the link partner's bonus-court unlock mask, received over the cable. Cleared at $10:$5171 for local play; set at $38:$75ef/$75f7 from the received link block ($ca8a or $ca0a depending on hLinkState) right after the block-$26 exchange that sends our own $cb54 ($38:$759c). ORed with $cb54 before StoreCourtUnlockBits ($3e:$5d18, $3e:$65db) and before choosing the 9-court vs 4-court menu ($38:$748d).
wLinkPartnerCourtMask:: db

; [8-bit] Bitmask of the five unlockable bonus courts (court ids 4-8; courts 0-3 are always available per IsCourtUnlocked $3e:$697b). Built from the save flags by ComputeUnlockedCourtFlags ($3e:$69a0-$69c9, one bit per row of the 5-entry table at $3e:$69ca) and cleared at $10:$5174. Passed in b to StoreCourtUnlockBits ($3e:$695a), which explodes it into the five per-court bytes at $d000 in WRAM bank $02; also decides whether the 9-court or the 4-court select menu runs ($10:$5199, $38:$7489) and is the payload of link block $26 ($38:$759c).
wUnlockedCourtMask:: db
	ds 12

; Dirty flags for the bank $18 BG map shadow buffers: low nibble set -> queue $d800->$9800 tilemap copy, high nibble -> $dc00->VRAM1 $9800 attrmap copy (FlushBgMapShadowToVram clears it).
wBgMapShadowDirty:: db

; [8-bit] Debug character viewer (Func_1a_67d4, reachable only from the unused debug path at $01:$41bf/$41fd with hDebugStepMode set): page of the 2x16 character grid, 0 or 1. Cleared at $1a:$67d5, incremented/decremented when the cursor wraps off the bottom/top row ($1a:$695f, $1a:$698f), and combined into the selected character id as ($cb62 << 4) + $cb63 -> $d002 ($1a:$69d0-$69dc), which is then fed to LoadOnCourtCharTilesA ($1a:$6837).
wDebugCharViewerPage:: db

; [8-bit] Debug character viewer (Func_1a_67d4): cursor index 0-15 within the current page - LEFT/RIGHT step by 1 and wrap inside the current row of 8 ($1a:$691b-$692d, $1a:$6934-$6945), UP/DOWN step by 8 and roll into $cb62 ($1a:$694c, $1a:$6979). Selected character id = ($cb62 << 4) + $cb63 ($1a:$69d8). Also indexes the cursor-sprite position table at $1a:$6b0f ($1a:$6af9).
wDebugCharViewerIndex:: db
	ds 10

; [16-bit] Rules/briefing screens: base text id of the minigame's rules pages, taken from MinigameRulesTextIdBases_17 ($17:$6fdb) at $17:$6fc6. Each page offset from the minigame's MinigameRulesPageLists_17 row is added to it ($17:$70ef) and the result rendered through PrepareGlyphBuffer / RenderProportionalTextAt.
wRulesPageTextIdBase:: dw
	ds 6

; VRAM tile-data write pointer for the proportional-glyph renderer (bank $05 text engine)
wGlyphTileWritePtr:: dw
	ds 136

; [576 bytes] Debug text console tilemap buffer, DMAed to $9d00 rows when active
wDebugTextBuffer:: ds 576


SECTION "WRAMX $d100", WRAMX[$d100]

; Sound-engine WRAM (bank $07), used only by the bank-0 audio driver;
; scoped to the driver's code range so the same $d1xx/$d2xx offsets
; in other WRAM banks keep their numeric address.
UNION
; sound engine (bank 0)
; [192 bytes] Six 32-byte channel state blocks (channels 0-1 music, 2-5 SFX); the active channel's block is mirrored into HRAM $ffd0 each pass, first word = script pointer ($ffff = idle)
wSndChannels:: ds 192
; [72 bytes] Per-channel loop bookkeeping (counter + return pointer per loop level); base resolved by GetChannelLoopSlot
wSndLoopSlots:: ds 72
; [8-bit] Bitmask of channels already serviced/keyed this update pass (AbortIfChannelTriggered tests it; folded into rAUDTERM at the end)
wSndActiveMask:: db
; [8-bit] Shadow of rAUDTERM: per-channel left/right output enable bits accumulated across channels
wSndPanShadow:: db
; [8-bit] Current channel type (0=square1/sweep, 1=square2, 2=wave, 3=noise)
wSndChannelType:: db
; [8-bit] Current channel's stereo output bit-pair (ch1=$11 .. ch4=$88), used for active-channel tracking
wSndChannelBits:: db
; [8-bit] Same bit-pair as wSndChannelBits, masked against hSndPanMask to build wSndPanShadow
wSndChannelPanMask:: db
; [8-bit] Current channel's APU register offset (type*5); WriteChannelReg forms rAUD via $ff10+this+reg
wSndRegBase:: db
; [8-bit] Free-running update counter; low nibble supplies the vibrato phase in TickVibrato
wSndFrameCounter:: db
; [8-bit] Index (0-5) of the channel currently being updated
wSndChannelIndex:: db
	ds 2
; [8-bit] Pending channel-update request: mask of channels to reconfigure (SetChannelUpdateRequest)
wSndUpdateReqMask:: db
; [8-bit] Value applied by the pending channel-update request (low nibble)
wSndUpdateReqData:: db
; [8-bit] Accumulator of channels that have acknowledged the pending update request
wSndUpdateReqAck:: db
; [8-bit] Channel index the update pass starts from (normally 0)
wSndFirstChannel:: db
	ds 1
; [8-bit] Wave-pattern id currently loaded into wave RAM (change detection for the wave channel)
wSndLoadedWaveId:: db
; [8-bit] Global transpose added to note ids (cmd $a9 $fe/$f2/$f3)
wSndTranspose:: db
; [8-bit] Non-zero to force the wave channel to reload its pattern on the next note
wSndWaveReloadPending:: db
ENDU

	ds 1575

; WRAM5: frame counter for the text continue-arrow blink task (bit 4 selects tile)
wTextArrowBlinkCounter:: db
	ds 5

; WRAM5: write index into wTextArgStringQueue (max 16)
wTextArgStringWriteIndex:: db
	ds 1

; WRAM5: write index for the short-text-id arg queue
wTextArgShortTextWriteIndex:: db

; WRAM5: count of queued arg strings (mirrors wTextArgStringWriteIndex)
wTextArgStringCount:: db
	ds 5

; WRAM5: set by TextCmdWaitButtonPage; TextInterpreterLoop saves resume offset to $d84e/f and returns
wTextPageBreakRequest:: db
	ds 19

; WRAM5: current VRAM destination address for glyph tiles (lo/hi)
wGlyphVramDest:: dw
	ds 3

; WRAM5: current read pointer into the text byte stream
wTextStreamPtr:: dw
	ds 21

; Short string buffer (16 bytes); text-bank fetch routines copy here when called with a != 0
wShortTextBuffer:: db
	ds 47

; WRAM5: 16 x 2-byte string pointers queued by PushTextArgString (hi nibble = WRAM bank tag)
wTextArgStringQueue:: ds 32

; WRAM5: 16 x 2-byte values queued by PushTextArgNumber for TextCmdPrintArgNumber
wTextArgNumberQueue:: ds 32
	ds 1040

; Match ball-visuals history ring (WRAM bank 4 only); shared renderer
; state, so scoped by the selected WRAM bank plus the bank-$08 renderer.
UNION
; match ball history ring (WRAM bank 4)
; [36 bytes] Ball position-history ring (WRAM bank 4): six 6-byte records [projX word, projY word, tile+8, attr]; UpdateBallVisuals ($5153) shifts it down one record per frame and BuildBallSlot writes the newest at +$1e
wBallHistory:: ds 36
ENDU

	ds 220

; Match ball sprite slots (WRAM bank 4 only), alongside the per-character
; $df80+ slots; scoped by the selected WRAM bank plus the bank-$08 renderer.
UNION
; match ball sprite slots (WRAM bank 4)
; [4 bytes] Match sprite-slot record [tile, attr, screenY, screenX] (WRAM bank 4): ball-at-net marker (tile $4e), drawn after the point resolves when the ball rests within $1e0 of the net (BuildNetBallSlot)
wNetBallSlot:: ds 4
; [4 bytes] Match sprite-slot record (WRAM bank 4): the ball, tile picked by height band / off-screen state ($40/$42/$44), gated by wBallSpriteEnabled (BuildBallSlot)
wBallSlot:: ds 4
; [4 bytes] Match sprite-slot record (WRAM bank 4): ball ground shadow (tile $46) at the ball's height-0 projection, gated by wBallShadowEnabled (BuildBallShadowSlot)
wBallShadowSlot:: ds 4
; [20 bytes] Five match sprite-slot records (WRAM bank 4): ball-trail afterimages (tile = ball tile + 8) fed from the history ring; slots 3-5 only when wBallTrailColor is nonzero (BuildBallTrailSlots)
wBallTrailSlots:: ds 20
ENDU

	ds 224

; Match-engine per-character struct, replicated across WRAM banks 4-7
; (bank = character: 4 near-P1, 5 far-P1, 6 near-partner, 7 far-partner).
; Same field, different character per bank -- one name each. Scoped by the
; provably-selected WRAM bank, plus the match banks $07/$08 whose
; callback-reached (jp hl) accesses the dataflow can't prove. Only the
; named field offsets render; other $dfxx bytes stay numeric.
UNION
; text-arg fetch buffer (menu banks reuse the idle char struct)
; [bank 5] Scratch buffer that PushTextArgFetchedString fills (via FetchShortTextToBuffer) with a fetched short-text string, then pushes as a text argument; overlaps the idle far-P1 character struct at $df00
wTextArgFetchBuffer:: db
	ds 150
NEXTU
; match character struct (WRAM banks 4-7)
; [3 bytes] Per-character banked struct (WRAM4-7): lateral X position, 24-bit fixed point (fraction byte + signed 16-bit integer part)
wCharPosX:: ds 3
; [3 bytes] Per-character banked struct (WRAM4-7): depth position (toward/away from net), same 24-bit fixed-point format; the two court sides carry opposite signs
wCharPosDepth:: ds 3
; [3 bytes] Per-character banked struct (WRAM4-7): height above court, same 24-bit fixed-point format (zeroed by SetCharPosAndTarget)
wCharPosHeight:: ds 3
; [8-bit] Per-character banked struct (WRAM4-7): serve/side role code (court-position record byte 4-7); XORed with 2 on the per-point side swap, mapped through the $4fa0 table at point start
wCharServeRole:: db
; [8-bit] Per-character banked struct (WRAM4-7): court position code (court-position record byte 0-3; XORed with 3 on the tiebreak side-swap)
wCharCourtPos:: db
; [8-bit] Per-character banked struct (WRAM4-7): character index 0-3 (== WRAM bank - 4); bit 0 set = far side (used by CharPointEndReaction and the edge-arrow sprite)
wCharIndex:: db
	ds 1
; [8-bit] Per-character banked struct (WRAM4-7): desired facing direction, eased toward by wCharFacingShown
wCharFacingDesired:: db
; [8-bit] Per-character banked struct (WRAM4-7): displayed facing, eased toward wCharFacingDesired by at most wCharFacingEaseRate per frame ($75c0)
wCharFacingShown:: db
; [8-bit] Per-character banked struct (WRAM4-7): state flags; bit 2 = airborne (set on jump $6dd5, cleared on landing; selects the shadow slot drawn)
wCharFlags:: db
	ds 8
; [8-bit] Per-character banked struct (WRAM4-7): state-machine index (RST00 jumptable at $6a77; set via SetCharState)
wCharState:: db
	ds 2
; [3 bytes] Per-character banked struct (WRAM4-7): current sprite frame pointer (hi/lo) + h-flip flag, consumed by DrawCharSprite ($650a)
wCharSpriteFrame:: ds 3
	ds 4
; [8-bit] Per-character banked struct (WRAM4-7): active flag (UpdateChar exits when 0)
wCharActive:: db
	ds 29
; [16-bit] Per-character banked struct (WRAM4-7): X velocity (zeroed on placement and at point end)
wCharVelX:: dw
; [16-bit] Per-character banked struct (WRAM4-7): depth velocity
wCharVelDepth:: dw
; [16-bit] Per-character banked struct (WRAM4-7): height velocity
wCharVelHeight:: dw
; [16-bit] Per-character banked struct (WRAM4-7): walk-target X (integer part)
wCharWalkTargetX:: dw
; [16-bit] Per-character banked struct (WRAM4-7): walk-target depth; MoveCharTowardTarget ($7541) walks toward it, snapping when both deltas < $18 (CheckCharNearTarget $78be)
wCharWalkTargetDepth:: dw
	ds 9
; [8-bit] Per-character banked struct (WRAM4-7): last projected screen X (BuildCharSpriteSlots $7672)
wCharScreenX:: db
; [8-bit] Per-character banked struct (WRAM4-7): last projected screen Y
wCharScreenY:: db
	ds 2
; [8-bit] Per-character banked struct (WRAM4-7): point result from this character's perspective (signed wPointWinLoseFlag)
wCharPointResult:: db
	ds 16
; [8-bit] Per-character banked struct (WRAM4-7): max facing change per frame, easing wCharFacingShown toward wCharFacingDesired
wCharFacingEaseRate:: db
	ds 2
; [8-bit] Per-character banked struct (WRAM4-7): speed-row index (e) into the ShotPlacementData tables for ground strokes (topspin/slice/power variants/neutral); selects bytes 4-5 -> shot speed in LoadShotPlacementEntry
wGroundStrokeSpeedIndex:: db
; [8-bit] Per-character banked struct (WRAM4-7): speed-row index (e) into ShotPlacementData for the smash and all three serves
wSmashServeSpeedIndex:: db
; [8-bit] Per-character banked struct (WRAM4-7): speed-row index (e) into ShotPlacementData for the reach (smash-range) shot variants
wReachSpeedIndex:: db
; [8-bit] Per-character banked struct (WRAM4-7): placement-row index (d) into ShotPlacementData for topspin and serve-topspin; selects bytes 0-3 -> target offsets in LoadShotPlacementEntry
wTopspinPlacementIndex:: db
; [8-bit] Per-character banked struct (WRAM4-7): placement-row index (d) into ShotPlacementData for slice and serve-slice
wSlicePlacementIndex:: db
	ds 16
; [4 bytes] Per-character banked struct (WRAM4-7): sprite-slot record [tile, attr, screenY, screenX] for the character sprite
wCharSpriteSlot:: ds 4
	ds 4
; [4 bytes] Per-character banked struct (WRAM4-7): sprite-slot record for the airborne shadow (tiles $50/$52/$54/$56 shrink with jump height; drawn only while wCharFlags bit 2 set)
wCharAirShadowSlot:: ds 4
; [4 bytes] Per-character banked struct (WRAM4-7): sprite-slot record for the standing shadow (tile $58; flicker-transparency while grounded)
wCharGroundShadowSlot:: ds 4
	ds 2
; [8-bit] Per-character banked struct (WRAM4-7): placement-row index (d) into ShotPlacementDataLob (set from df91 bit 0)
wLobPlacementIndex:: db
; [8-bit] Per-character banked struct (WRAM4-7): placement-row index (d) into ShotPlacementDataDrop (set from df91 bit 1)
wDropPlacementIndex:: db
	ds 2
; [8-bit] Per-character banked struct (WRAM4-7): draw-order depth key ((depth*8)>>8 + $80); DrawActorsByDepth paints teammates back-to-front
wCharDepthKey:: db
ENDU
