"""Rendering the analysed ROM as per-bank RGBDS source.

The Emitter walks every bank byte by byte. At each offset exactly one thing is
true -- it is a $4000-table slot, a structural dw word, a jump-table entry, a
proven instruction, or unclassified data -- and the matching _emit_* method
appends source lines and returns the offset after it.

Data is the involved case. A run either carries a *mark* (a proven blob: a
label and usually an exact extent, from the analysis passes) or is
unclassified, in which case it is split into segments at constant-byte fills,
declared data tables and curated labels, and each segment is classified in
turn -- structured table, text, inline `db`, or an INCBIN of an extracted blob.

Nothing here decides *what* the bytes are; it only renders decisions the
analysis already made, so every path must reproduce the original bytes.
"""
import bisect
import re
from pathlib import Path

from extract import render_spec

from .constants import CHAR_ROSTER, is_splittable
from .datatables import (render_actor_list, render_actor_script,
                         render_drill_definition, render_enum_table,
                         render_flag_ids, render_save_flag_ids,
                         render_gfx_ptr_table, render_lz_ptr_table,
                         render_map_table, render_menu_def,
                         render_mugshot_ptr_table, render_object_header,
                         render_pointer_words, render_rect_pair,
                         render_rect_ptrs, render_rules_pages,
                         render_sprite_anim, render_text_ids,
                         render_slot_records, render_story_locations,
                         render_text_offsets,
                         render_tilemap_dispatch, render_tilemap_scripts)
from .idioms import match_launcher_seq, script_cmd_seq, wram_bank_seq
from .labels import LabelScopes
from .macros import MACROS_INC
from .operands import render_operand
from .rom import BANK_SIZE, offset_to_cpu, target_to_offset
from .seeds import FRAME_TASK_PTR_CALLS
from .textids import TEXT_IDS_USED

# Unclassified data runs this short (alignment padding, stray constants
# between code) render as inline `db` instead of a standalone blob file.
INLINE_DB_MAX = 2

# Declared specs that render ROM *values* rather than derived structure. These
# are generated into the gitignored data/ tree at setup and INCLUDEd, exactly
# like game text, so no such content is committed. Anything whose rows are
# label arithmetic or pointer symbols stays inline -- rgbasm recomputes those
# from the layout, so they reproduce nothing.
GENERATED_SPECS = {"palettes", "sound_index", "sound_data", "text_pool"}

_LABEL_LINE_RE = re.compile(r"^([A-Za-z_][\w.]*):$")
_CPU_COMMENT_RE = re.compile(r"; \$([0-9a-f]{4})\b")
_FLAG_OP_RE = re.compile(
    r"^\t(set_flag|clear_flag|test_flag) \$([0-9a-f]{2}), ([0-7])( ;.*)?$")
_PTR_LOAD_LINE_RE = re.compile(
    r"^(\tld (?:hl|de|bc), )\$[0-9a-f]{1,4}( ; \$([0-9a-f]{4}).*)$")

_FLAG_CONSTANTS_HEADER = [
    "; Auto-generated by tools/disasm.py from flags.json — do not edit.",
    "; FLAG_* = a bit of the per-story-slot wGameFlags array ($c9c0, 32 bytes).",
    "; The value is the flag number: byte * 8 + bit, where the handlers apply",
    "; mask $80 >> bit to wGameFlags[byte]. Pass it to `set_flag`/`clear_flag`/",
    "; `test_flag`/`flag_id` (one-argument form) or to *GameFlagByNumber.",
    "",
]

_TEXT_IDS_HEADER = [
    "; Auto-generated by tools/disasm.py — do not edit.",
    "; Text_<bank>_<index> = a dialogue text id, named by the (text bank :",
    "; string index) coordinate it decodes to. Read the string with",
    "; `tools/strings.py baserom.gbc --index --bank <bank>`.",
    "",
]


def resolve_pointer_loads(lines, base, ptr_sites):
    """Post-pass over an emitted bank's source lines: rewrite each vetted
    pointer-load (`ld reg, $imm`) to the label emit actually defines at its
    target. The emitted-label map is built by pairing every label line with the
    `; $cpu` of the following line, so it covers code, text (`Text_*`), blob
    (`Data_/Lz_`), and slot (`DataPtr_/FarPtr_`) labels alike -- a target with no
    emitted label is left as raw hex rather than an undefined symbol."""
    emitted = {}
    for i, line in enumerate(lines[:-1]):
        m = _LABEL_LINE_RE.match(line)
        if not m:
            continue
        c = _CPU_COMMENT_RE.search(lines[i + 1])
        if c:
            emitted[base + (int(c.group(1), 16) - 0x4000)] = m.group(1)
    for i, line in enumerate(lines):
        m = _PTR_LOAD_LINE_RE.match(line)
        if not m:
            continue
        site = base + (int(m.group(3), 16) - 0x4000)
        target = ptr_sites.get(site)
        if target is not None and target in emitted:
            lines[i] = f"{m.group(1)}{emitted[target]}{m.group(2)}"


_REGION_RE = re.compile(r'^\t(?:INCBIN|INCLUDE) "data/[^"]+" ; \$([0-9a-f]{4}), (\d+) bytes')
_SRC_LOAD_RE = re.compile(r"^\tld (?:hl|de), ([A-Za-z_][A-Za-z0-9_]*) ;")
_COUNT_RE = re.compile(r"^(\tld c, )\$([0-9a-f]{1,2})( ;.*)$")
# Helpers whose `c` is a count of 16-byte tiles, not a byte count.
_TILE_COUNT_CALLS = ("QueueVRAMCopy", "CopyMemoryFast")
_CALL_RE = re.compile(r"^\t(?:call|farcall) ([A-Za-z_][A-Za-z0-9_.]*)")


def resolve_copy_lengths(lines, base):
    """Post-pass: rewrite a copy count that equals its source blob's size into
    the difference of two labels. `ld hl, Tiles; ld c, $20; call QueueVRAMCopy`
    copies 32 tiles because the blob happens to be 512 bytes long -- edit the
    blob and the literal is silently wrong, while `(Next - Tiles) / 16` follows
    it. Only rewritten when a label already marks the blob's end, so this
    invents no symbols."""
    start, size, label_at = {}, {}, {}
    for i, line in enumerate(lines[:-1]):
        m = _LABEL_LINE_RE.match(line)
        if not m:
            continue
        r = _REGION_RE.match(lines[i + 1])
        c = _CPU_COMMENT_RE.search(lines[i + 1])
        if c:
            label_at.setdefault(int(c.group(1), 16), m.group(1))
        if r:
            start[m.group(1)] = int(r.group(1), 16)
            size[m.group(1)] = int(r.group(2))
    for i, line in enumerate(lines):
        m = _SRC_LOAD_RE.match(line)
        if not m or m.group(1) not in size:
            continue
        blob = m.group(1)
        end = label_at.get(start[blob] + size[blob])
        if not end:
            continue
        for k in range(i + 1, min(len(lines), i + 7)):
            n = _COUNT_RE.match(lines[k])
            if n and int(n.group(2), 16) * 16 == size[blob]:
                call = next((_CALL_RE.match(x) for x in lines[k:k + 3]
                             if _CALL_RE.match(x)), None)
                if call and call.group(1) in _TILE_COUNT_CALLS:
                    lines[k] = f"{n.group(1)}({end} - {blob}) / 16{n.group(3)}"
                break
            if _CALL_RE.match(lines[k]):
                break


_ADD_LO_RE = re.compile(r"^(\tadd a, )\$([0-9a-f]{2})( ;.*)$")
_ADC_HI_RE = re.compile(r"^(\tadc a, )\$([0-9a-f]{2})( ;.*)$")


def resolve_flag_names(lines, flag_names, raw_sites=(), base=0):
    """Post-pass: rewrite `set_flag $0a, 3` to `set_flag FLAG_NAME` for every
    flag flags.json names. The macro's one-argument form reassembles the same
    two operand bytes from the flag number (byte * 8 + bit). Sites listed in
    flags.json's `_raw_sites` keep the numeric form -- code that borrows a bit
    as scratch should not claim the name's meaning."""
    for i, line in enumerate(lines):
        m = _FLAG_OP_RE.match(line)
        if not m:
            continue
        cpu = _CPU_COMMENT_RE.search(m.group(4) or "")
        if cpu and base + (int(cpu.group(1), 16) - 0x4000) in raw_sites:
            continue
        name = flag_names.get(int(m.group(2), 16) * 8 + int(m.group(3)))
        if name:
            lines[i] = f"\t{m.group(1)} {name}{m.group(4)}"


def bank_end_fill(cpu, length):
    """Note the trailing $ff mastering fill a bank's section stops short of.

    Nothing is assembled: `rgblink -p 0xff` pads every byte no section covers,
    so carving at the end of a bank never has to restate a fill count. The
    comment keeps the unused tail visible in the source (and countable by
    tools/progress.py).
    """
    return f"\t; ${cpu:04x}, {length} bytes fill to bank end (linker-padded)"


def emit(dis, labels, hwregs, ramnames, srcdir, manifest_path, data_tables=None,
         curated=None, ramscoped=None, constants=None, const_defs=None,
         ptr_sites=None, ptr_data_targets=None, flag_names=None,
         flag_raw_sites=None):
    """Write srcdir/bank_*.asm, the generated include/*.inc, and the manifest."""
    Emitter(dis, labels, hwregs, ramnames, srcdir, manifest_path, data_tables,
            curated, ramscoped, constants, const_defs, ptr_sites,
            ptr_data_targets, flag_names, flag_raw_sites).run()


class Emitter:
    """One pass over the whole ROM, writing src/bank_*.asm.

    Construction resolves everything that is global to the output -- which
    offsets render as table slots, which blobs anchor labels, what each slot
    and blob is called -- and run() then renders bank by bank.
    """

    def __init__(self, dis, labels, hwregs, ramnames, srcdir, manifest_path,
                 data_tables=None, curated=None, ramscoped=None,
                 constants=None, const_defs=None, ptr_sites=None,
                 ptr_data_targets=None, flag_names=None,
                 flag_raw_sites=None):
        self.dis = dis
        self.rom = dis.rom
        # The cut points emit is about to name are globals like any other, so
        # LabelScopes has to see them before it decides which global each local
        # label binds to. Without this a cut landing between a curated local
        # and its parent re-parents it in the output while the reference is
        # still spelled with the old parent -- an undefined symbol at link time.
        labels = dict(labels)
        for t in ptr_data_targets or ():
            labels.setdefault(
                t, f"Data_{t // BANK_SIZE:02x}_{offset_to_cpu(t):04x}")
        # Definitions keep the curated spelling (`.loop:`); every reference
        # goes through the qualified table, which spells a local label
        # `Parent.loop` for anything outside its function.
        self.scopes = LabelScopes(labels)
        self.def_labels = labels
        self.labels = self.scopes.qualified
        self.hwregs = hwregs
        self.ramnames = ramnames
        self.srcdir = Path(srcdir)
        self.manifest_path = manifest_path
        self.data_tables = data_tables or {}
        self.curated = curated or set()
        self.ramscoped = ramscoped
        self.constants = constants or {}
        self.const_defs = const_defs or {}
        self.ptr_sites = ptr_sites
        self.ptr_data_targets = ptr_data_targets or set()
        self.ptr_cuts = sorted(self.ptr_data_targets)
        self.flag_names = flag_names or {}
        self.flag_raw_sites = flag_raw_sites or set()
        self.manifest = []   # (blob path, rom offset, length, render spec)
        self.lines = []      # source lines of the bank being rendered
        self.emitted_labels = set()   # every label name actually written
        self.truncated = []  # declared tables a curated label cut short

        self._classify_entries()
        self._mark_data_blobs()
        self._assign_slot_names()
        self._find_frame_task_loads()
        # Curated data labels (named non-code offsets) whose address an
        # immediate pointer load may reference by name.
        self.operand_labels = {o: n for o, n in labels.items()
                               if o not in dis.instrs}
        # Every name a pointer word can resolve to, including the auto names
        # the cut points below are about to define.
        self.ptr_names = dict(self.labels)
        self.ptr_names.update((t, self._auto_name(t))
                              for t in self.ptr_data_targets)

    # ---- setup ----------------------------------------------------------

    def _classify_entries(self):
        """Split the offsets that render as structured words into their kinds.

        Farcall pointer-table slots referenced by live call sites. A slot is
        emitted as a labeled dw only if nothing else already claimed its bytes
        as code; sites whose slot can't be emitted fall back to raw bytes.
        """
        dis = self.dis
        self.table_entries = {}  # entry_flat -> (bank, slot, target_flat)
        self.dirty_sites = set()
        for off, (bank, slot, entry, target) in dis.farcalls.items():
            if off not in dis.instrs:
                continue
            if entry in dis.code_bytes or entry + 1 in dis.code_bytes:
                self.dirty_sites.add(off)
            else:
                self.table_entries[entry] = (bank, slot, target)
        self.data_entries = {
            e: v for e, v in dis.data_slots.items()
            if e not in self.table_entries
            and e not in dis.code_bytes and e + 1 not in dis.code_bytes}
        for entry, (bank, slot, target) in list(dis.inferred_entries.items()) \
                + list(dis.static_code_entries.items()):
            if entry in self.data_entries:
                continue
            if entry not in dis.code_bytes and entry + 1 not in dis.code_bytes:
                self.table_entries.setdefault(entry, (bank, slot, target))
        self.jt_entries = {
            p: t for p, t in dis.jt_entries.items()
            if p not in dis.code_bytes and p + 1 not in dis.code_bytes
            and p not in self.table_entries and p not in self.data_entries}

    def _mark_data_blobs(self):
        """Blob labels/extents for data-slot targets. A mark can only anchor a
        label if it starts outside every other emitted structure; marks inside
        an earlier mark's exact extent are dropped (their dw falls back to a
        numeric operand)."""
        dis = self.dis
        self.data_marks = {}   # src_flat -> (length or None, label, kind)
        self.data_labels = {}  # src_flat -> label
        prev_end = -1
        for src in sorted(dis.data_blobs):
            length, kind = dis.data_blobs[src]
            if (src < prev_end or src in dis.code_bytes
                    or src in self.table_entries or src in self.data_entries
                    or src in self.jt_entries or src in dis.ptr_words):
                continue
            stem = {"lz": "Lz", "sprite": "SpriteTemplate"}.get(kind, "Data")
            # A pointer target that is $ff all the way to the bank end is an
            # unused table slot aimed at the mastering padding, not data. It
            # still needs a label for the dw to resolve, but calling it Data_
            # reads like content the disassembly has not got to yet.
            bank_end = (src // BANK_SIZE + 1) * BANK_SIZE
            if stem == "Data" and all(b == 0xFF for b in self.rom[src:bank_end]):
                stem = "Fill"
            label = self.labels.get(src) or \
                f"{stem}_{src // BANK_SIZE:02x}_{offset_to_cpu(src):04x}"
            self.data_marks[src] = (length, label, kind)
            self.data_labels[src] = label
            if length:
                prev_end = max(prev_end, src + length)

    def _assign_slot_names(self):
        """Semantic slot names: a $4000-table slot whose target carries a label
        is named after it, so call sites read `farcall FarPtr_DrawBox` instead
        of `farcall FarPtr_18_xx`. When several slots point at the same target
        (dual-purpose scene slots, defaulted fan-in ranges), the first is
        <Prefix>_<Target> and the rest are <Prefix>_<Target>Alias1, Alias2, ...
        so every duplicate reads back to its target instead of an opaque
        numeric slot. A singleton whose target isn't curated keeps its numeric
        name."""
        self.far_slot_names = {}   # (bank, slot) -> label
        self.data_slot_names = {}  # (bank, slot) -> label
        self._used_slot_names = set()
        self._name_slots(self.table_entries, self.labels.get, "FarPtr",
                         self.far_slot_names, name_singletons=True)
        self._name_slots(self.data_entries, self.data_labels.get, "DataPtr",
                         self.data_slot_names)

    def _name_slots(self, entries, label_of, prefix, out, name_singletons=False):
        groups = {}
        for entry in sorted(entries):
            groups.setdefault(entries[entry][2], []).append(entry)
        for target, ents in groups.items():
            label = label_of(target)
            if not label or "." in label or \
                    (len(ents) == 1 and label not in self.curated
                     and not name_singletons):
                continue
            base = f"{prefix}_{label}"
            for i, entry in enumerate(ents):
                name = base if i == 0 else f"{base}Alias{i}"
                while name in self._used_slot_names:
                    name += "_"
                self._used_slot_names.add(name)
                bank, slot = entries[entry][:2]
                out[(bank, slot)] = name

    def _slot_ref(self, w):
        """The emitted label of the $4000-table slot a (bank<<8|slot) word
        references, or None if that entry isn't a labeled dw."""
        entry = (w >> 8) * BANK_SIZE + (w & 0xFF)
        if entry in self.data_entries:
            b, s = self.data_entries[entry][:2]
            return self.data_slot_names.get((b, s), f"DataPtr_{b:02x}_{s:02x}")
        if entry in self.table_entries:
            b, s, _t = self.table_entries[entry]
            return self.far_slot_names.get((b, s), f"FarPtr_{b:02x}_{s:02x}")
        return None

    def _find_frame_task_loads(self):
        """`ld hl, n16` immediately before `call RegisterFrameTask` loads a code
        pointer (the task function), so resolve it to that function's label -
        the 400-odd registration sites then read `ld hl, UpdateActors` instead
        of raw hex. Gated on the following call so numeric constants aren't
        touched."""
        rom, dis = self.rom, self.dis
        calls = {o for o, n in self.labels.items() if n in FRAME_TASK_PTR_CALLS}
        self.frametask_ptr_sites = {}
        if not calls:
            return
        for o in dis.instrs:
            if rom[o] != 0x21 or o + 3 not in dis.instrs or rom[o + 3] != 0xCD:
                continue  # ld hl, n16 followed by `call nn`
            call_tgt = rom[o + 4] | (rom[o + 5] << 8)
            if target_to_offset(call_tgt, o + 3) not in calls:
                continue
            imm = rom[o + 1] | (rom[o + 2] << 8)
            b = (o // BANK_SIZE) * BANK_SIZE
            flat = imm if imm < 0x4000 else (b + imm - 0x4000 if b else None)
            if flat in self.labels:
                self.frametask_ptr_sites[o] = self.labels[flat]

    # ---- driver ---------------------------------------------------------

    def _check_local_scopes(self):
        """Every local label's owning global has to be a label the emitter
        actually wrote. A curated name at an offset that never emits (a wrong
        bank in labels.json, say) would otherwise leave `Parent.local`
        references pointing at a symbol rgbasm never sees."""
        emitted = self.emitted_labels
        for off, owner in sorted(self.scopes.parent.items()):
            name = self.def_labels[owner]
            if name not in emitted:
                raise SystemExit(
                    f"error: local {self.def_labels[off]} at ${off:06x} is "
                    f"scoped to {name} (${owner:06x}), which is never emitted "
                    f"-- check that offset in labels.json")

    def run(self):
        self._write_include("macros.inc", MACROS_INC)
        nbanks = len(self.rom) // BANK_SIZE
        for bank in range(nbanks):
            self._emit_bank(bank)
        # A pointer word renders as a name; whether that name gets *defined*
        # depends on where its target lands, which is only known once the bank
        # is laid out. Drop the ones nothing defined and lay the ROM out again
        # -- those words fall back to numeric. Dropping a name never changes
        # which labels are emitted, so one extra pass always settles it.
        undefined = {o for o, n in self.ptr_names.items()
                     if n not in self.emitted_labels}
        if undefined:
            for o in undefined:
                self.ptr_names.pop(o, None)
            self.manifest = []
            self.emitted_labels = set()
            for bank in range(nbanks):
                self._emit_bank(bank)
        self._check_local_scopes()
        self._report_truncations()
        self._write_text_ids()
        self._write_flag_constants()
        self._write_manifest()
        ncode = sum(i.size for i in self.dis.instrs.values())
        print(f"emitted {nbanks} banks: {len(self.dis.instrs)} instructions "
              f"({ncode} bytes code, {len(self.rom) - ncode} bytes data, "
              f"{len(self.manifest)} blobs)")

    def _resolve_split_base(self, lines, bank):
        """Rewrite the split-base table setup so its address is a symbol.

            add a, $bd      ->  add a, LOW(RestaurantNpc12TextIds)
            ld l, a
            adc a, $43      ->  adc a, HIGH(RestaurantNpc12TextIds)
            sub a, l
            ld h, a

        The two halves of the address are 8-bit immediates, so unlike a `ld hl,
        table` they do not move when the table does -- the one relocation hole
        the pointer work left. LOW/HIGH assemble to the same bytes. Gated the
        same way as a pointer load: the full five-instruction shape, an address
        that carries a label, and a dereference of hl afterwards. Addresses
        below $0100 are the vectors, where the pair is a small constant."""
        for i, line in enumerate(lines):
            m = _ADD_LO_RE.match(line)
            if not m:
                continue
            window = lines[i + 1:i + 5]
            hi = next(((k, _ADC_HI_RE.match(x)) for k, x in enumerate(window)
                       if _ADC_HI_RE.match(x)), None)
            if not hi or not any("ld l, a" in x for x in window) \
                    or not any("ld h, a" in x for x in window):
                continue
            k, adc = hi
            addr = int(adc.group(2), 16) << 8 | int(m.group(2), 16)
            # must be a ROM address in reach: below $0100 is the vector area,
            # and anything from $8000 up is VRAM/WRAM, so the pair is arithmetic
            # rather than an address (this caught a $c7xx pair whose bogus flat
            # offset still landed on a label).
            if not 0x0100 <= addr < 0x8000:
                continue
            if bank and addr < BANK_SIZE:
                flat = addr                      # ROM0, always mapped
            elif not bank and addr >= BANK_SIZE:
                continue                         # ROM0 code, no bank window
            else:
                flat = bank * BANK_SIZE + addr - BANK_SIZE if bank else addr
            name = self.labels.get(flat)
            # a qualified local (`Parent.loop`) names a point inside a routine,
            # never a table base
            if not name or "." in name:
                continue
            if not any("[hl" in x for x in lines[i + 3:i + 10]):
                continue
            lines[i] = f"{m.group(1)}LOW({name}){m.group(3)}"
            lines[i + 1 + k] = f"{adc.group(1)}HIGH({name}){adc.group(3)}"

    def _emit_bank(self, bank):
        base = bank * BANK_SIZE
        end = base + BANK_SIZE
        self.lines = lines = []
        if bank == 0:
            lines.append('SECTION "ROM Bank $00", ROM0[$0000]')
        else:
            lines.append(f'SECTION "ROM Bank ${bank:02x}", '
                         f'ROMX[$4000], BANK[${bank:02x}]')
        lines.append("")
        off = base
        while off < end:
            if off in self.table_entries:
                off = self._emit_farptr(off)
            elif off in self.dis.ptr_words:
                off = self._emit_ptr_word(off)
            elif off in self.data_entries:
                off = self._emit_data_ptr(off)
            elif off in self.jt_entries:
                off = self._emit_jumptable_word(off)
            elif off in self.dis.instrs:
                off = self._emit_instruction(off)
            else:
                off = self._emit_data_run(off, end, bank)
        lines.append("")
        if self.ptr_sites:
            resolve_pointer_loads(lines, base, self.ptr_sites)
        if self.flag_names:
            resolve_flag_names(lines, self.flag_names, self.flag_raw_sites,
                               base)
        resolve_copy_lengths(lines, base)
        self._resolve_split_base(lines, bank)
        # Several emitters declare a label for the same offset (the fill /
        # segment path that runs up to a blob, and the blob's own mark). Most
        # guard on lines[-1]; collapsing here covers the rest -- two identical
        # consecutive label lines are always an rgbasm redefinition error.
        lines[:] = [l for i, l in enumerate(lines)
                    if not (i and l == lines[i - 1] and _LABEL_LINE_RE.match(l))]
        self._check_truncated_tables(lines, bank)
        self.emitted_labels.update(
            m.group(1) for l in lines if (m := _LABEL_LINE_RE.match(l)))
        Path(self.srcdir, f"bank_{bank:03x}.asm").write_text("\n".join(lines))

    # ---- structured words -----------------------------------------------

    def _emit_farptr(self, off):
        bank, slot, target = self.table_entries[off]
        tl = self.labels.get(target, f"${offset_to_cpu(target):04x}")
        sl = self.far_slot_names.get((bank, slot),
                                     f"FarPtr_{bank:02x}_{slot:02x}")
        suffix = sl[len("FarPtr_"):]
        arg = suffix if tl == suffix else f"{suffix}, {tl}"
        self.lines.append(f"\tfarptr {arg} ; ${offset_to_cpu(off):04x}")
        return off + 2

    def _emit_ptr_word(self, off):
        """A dw the carving passes proved structural (frame/OAM/sound/launcher
        pointer arrays), rendered as its target's label."""
        target, note = self.dis.ptr_words[off]
        lbl = self.labels.get(off) or self.dis.ptr_labels.get(off)
        if lbl:
            self.lines.append(f"{lbl}:")
        if target is None and note == "snd_channel":
            v = self.rom[off] | (self.rom[off + 1] << 8)
            self.lines.append(f"\tsnd_channel {(v & 0xff) // 0x20}, "
                              f"${v >> 8:02x} ; ${offset_to_cpu(off):04x}")
            return off + 2
        if target is None:
            tl = f"${self.rom[off] | (self.rom[off + 1] << 8):04x}"
        else:
            tl = (self.labels.get(target) or self.dis.ptr_labels.get(target)
                  or self.data_labels.get(target)
                  or f"${offset_to_cpu(target):04x}")
        suffix = f" {note}" if note else ""
        self.lines.append(f"\tdw {tl} ; ${offset_to_cpu(off):04x}{suffix}")
        return off + 2

    def _emit_data_ptr(self, off):
        bank, slot, src, _kind = self.data_entries[off]
        tl = self.data_labels.get(src, f"${offset_to_cpu(src):04x}")
        sl = self.data_slot_names.get((bank, slot),
                                      f"DataPtr_{bank:02x}_{slot:02x}")
        self.lines.append(f"{sl}:")
        self.lines.append(f"\tdw {tl} ; ${offset_to_cpu(off):04x}")
        return off + 2

    def _emit_jumptable_word(self, off):
        self._label_line(off)
        target = self.jt_entries[off]
        tl = self.labels.get(target, f"${offset_to_cpu(target):04x}")
        self.lines.append(f"\tdw {tl} ; ${offset_to_cpu(off):04x} jumptable")
        return off + 2

    # ---- code -----------------------------------------------------------

    def _emit_instruction(self, off):
        dis, rom = self.dis, self.rom
        if off in self.def_labels:
            self.lines.append(f"{self.def_labels[off]}:")
        ins = dis.instrs[off]
        cpu = offset_to_cpu(off)
        idiom = self._collapse_idiom(off)
        if idiom:
            text, size = idiom
            self.lines.append(f"\t{text} ; ${cpu:04x}")
            return off + size
        if off in self.frametask_ptr_sites:
            self.lines.append(
                f"\tld hl, {self.frametask_ptr_sites[off]} ; ${cpu:04x}")
            return off + ins.size
        if off in dis.farcalls and ins.text == "farcall {far}":
            bank, slot, _entry, _target = dis.farcalls[off]
            if off in self.dirty_sites:
                self.lines.append(f"\trst Rst18 ; ${cpu:04x}")
                self.lines.append(f"\tdb ${slot:02x}, ${bank:02x} ; farcall "
                                  f"operands (slot bytes overlap code)")
            else:
                sl = self.far_slot_names.get((bank, slot),
                                             f"FarPtr_{bank:02x}_{slot:02x}")
                arg = sl[len("FarPtr_"):] if sl.startswith("FarPtr_") else sl
                self.lines.append(f"\tfarcall {arg} ; ${cpu:04x}")
        elif off in dis.inline_arg_calls and ins.size == 4:
            self.lines.append(f"\t{self._operand(ins, off)} ; ${cpu:04x}")
            self.lines.append(f"\tdb ${rom[off + 3]:02x} ; "
                              f"${offset_to_cpu(off + 3):04x} inline arg")
        else:
            note = dis.data_site_notes.get(off)
            suffix = ""
            if note:
                sl = self.data_slot_names.get(
                    note, f"DataPtr_{note[0]:02x}_{note[1]:02x}")
                suffix = f" -> {sl}"
            self.lines.append(f"\t{self._operand(ins, off)} ; ${cpu:04x}{suffix}")
        return off + ins.size

    def _collapse_idiom(self, off):
        """The macro a fixed instruction sequence at `off` collapses into, as
        (text, size), or None when it is not one (see idioms.py)."""
        if 0xFF96 in self.ramnames:
            wb = wram_bank_seq(self.dis, self.rom, off, self.labels)
            if wb:
                return wb
        return (match_launcher_seq(self.dis, self.rom, off, self.labels)
                or script_cmd_seq(self.dis, self.rom, off, self.labels,
                                  self.far_slot_names))

    def _operand(self, ins, off):
        return render_operand(ins, off, self.labels, self.hwregs, self.ramnames,
                              self.operand_labels, self.ramscoped,
                              self.constants, self.scopes)

    # ---- data runs ------------------------------------------------------

    def _emit_data_run(self, run_start, bank_end, bank):
        """Everything from run_start up to the next emitted structure. A run
        carrying a mark renders as that blob; otherwise it is split into
        segments (see _emit_unclassified)."""
        run_end = self._data_run_end(run_start, bank_end)
        length = run_end - run_start
        cpu = offset_to_cpu(run_start)
        mark = self.data_marks.get(run_start)
        prefix = "d"
        if mark:
            mlen, mlabel, kind = mark
            self.lines.append(f"{mlabel}:")
            if mlen and mlen <= length:
                run_end = run_start + mlen
                length = mlen
            if kind == "lz":
                prefix = "lz"
        if run_start in self.dis.object_headers:
            self.lines.extend(render_object_header(
                self.rom, run_start, self.data_labels, self.dis.ptr_labels))
        elif run_start in self.dis.sprite_templates and mark and mark[0]:
            self.lines.append(f"\t; ${cpu:04x}, {length} bytes (sprite_template)")
            self._extend_spec(self.rom[run_start:run_end], "sprite_template")
        elif mark and mark[0]:
            self._emit_marked_blob(run_start, run_end, bank_end, bank, prefix)
        else:
            self._emit_unclassified(run_start, run_end, bank_end, bank)
        return run_end

    def _data_run_end(self, run_start, bank_end):
        """The run ends at the next emitted structure. A curated label inside a
        data run splits the run so the symbol anchors its own blob/segment --
        unless the run renders itself in pieces, which places the label without
        losing the spec for the bytes after it."""
        natural = self._scan_run_end(run_start, bank_end, False)
        if self._splits_itself(run_start, natural):
            return natural
        return self._scan_run_end(run_start, bank_end, True)

    def _scan_run_end(self, run_start, bank_end, stop_at_cuts):
        off = run_start + 1
        while off < bank_end and off not in self.dis.instrs \
                and off not in self.table_entries \
                and off not in self.data_entries \
                and off not in self.jt_entries and off not in self.data_marks \
                and off not in self.dis.ptr_words \
                and not (off in self.labels
                         and self.labels[off] in self.curated) \
                and not (stop_at_cuts and off in self.ptr_data_targets):
            off += 1
        return off

    def _emit_marked_blob(self, start, end, bank_end, bank, prefix):
        """A proven blob of known extent: a declared table renders inline,
        pure mastering fill renders as `ds`, anything else is extracted."""
        cpu = offset_to_cpu(start)
        length = end - start
        if start in self.data_tables:
            self._emit_spec_pieces(start, end, bank, self.data_tables[start])
            return
        if all(b == 0xFF for b in self.rom[start:end]):
            # Pointer-targeted but pure mastering fill (unused trailing
            # $4000-table slots in the scene banks). The label still has to
            # resolve, but fill that runs to the bank end is left to the
            # linker's $ff padding.
            if end < bank_end:
                self.lines.append(f"\tds {length}, $ff ; ${cpu:04x}, fill")
            else:
                self.lines.append(bank_end_fill(cpu, length))
            return
        for a, b in self._pieces(start, end):
            if a != start:
                self.lines.append(f"{self._auto_name(a)}:")
            self.lines.append(self._incbin(a, b - a, bank, prefix))

    def _emit_unclassified(self, run_start, run_end, bank_end, bank):
        """Split an unclassified run into constant-byte fills ($ff is the
        mastering fill; $00 needs a longer run since zero arrays can be real
        data) and the data segments between them, and emit each."""
        seg = run_start
        while seg < run_end:
            b = self.rom[seg]
            j = seg
            while j < run_end and self.rom[j] == b:
                j += 1
            # A curated label inside a constant-byte run starts its own
            # segment: never let fill collapse (or the run scan) swallow it, or
            # the label is dropped and any dw referencing it goes undefined
            # (e.g. empty $ff map-script lists in $0e/$0f).
            clab = min((t for t in self.labels if seg < t < j), default=0)
            if clab:
                j = clab
            if not self._is_fill(b, seg, j, run_start, run_end, bank_end):
                seg = self._emit_data_segment(seg, run_end, bank_end, bank)
            elif self._emit_fill(seg, j, bank_end, bank):
                seg = j
            else:
                return  # fill to the bank end: the linker pads the rest

    @staticmethod
    def _is_fill(b, seg, j, run_start, run_end, bank_end):
        """Any $ff run that reaches the bank end is trailing fill regardless of
        length, and a run that is entirely $ff is padding whatever its length
        (e.g. the 5-byte gaps between the rst/interrupt vectors)."""
        return ((b == 0xFF and (j - seg >= 64 or j == bank_end
                                or (seg == run_start and j == run_end)))
                or (b == 0x00 and j - seg >= 256))

    def _emit_fill(self, seg, j, bank_end, bank):
        """A constant-byte run as a `ds`. Returns False when it was the bank's
        trailing fill, which needs no directive at all: rgblink pads every byte
        no section covers with $ff (`-p 0xff`)."""
        b = self.rom[seg]
        cpu = offset_to_cpu(seg)
        if b == 0xFF and j == bank_end and seg not in self.labels \
                and seg not in self.ptr_data_targets:
            self.lines.append(bank_end_fill(cpu, j - seg))
            return False
        if (seg in self.labels or seg in self.ptr_data_targets) \
                and self.lines[-1] != f"{self._auto_name(seg)}:":
            self.lines.append(f"{self._auto_name(seg)}:")
        self.lines.append(f"\tds {j - seg}, ${b:02x} ; ${cpu:04x}, fill")
        return True

    def _emit_data_segment(self, seg, run_end, bank_end, bank):
        """One non-fill segment of an unclassified run: a slot-record table, a
        declared data table, or raw bytes. Returns the offset after it."""
        j = self._segment_end(seg, run_end, bank_end)
        if seg in self.dis.slot_record_tables:
            self._emit_slot_record_table(seg, j)
        elif seg in self.data_tables:
            self._emit_declared_table(seg, j, bank)
        else:
            self._emit_raw_segment(seg, j, bank)
        return j

    def _segment_end(self, seg, run_end, bank_end):
        """The segment runs to the next constant-byte fill, or to whatever
        starts its own segment first: a declared data table or a curated label
        (so a region can hold several back-to-back tables, e.g. a dw pointer
        table followed by its payload) or a pointer target in raw data (so
        named streams reached only through non-slot pointers still carve out of
        anonymous blobs)."""
        j = seg + 1
        while j < run_end:
            b = self.rom[j]
            k = j
            while k < run_end and self.rom[k] == b:
                k += 1
            if (b == 0xFF and (k - j >= 64 or k == bank_end)) \
                    or (b == 0x00 and k - j >= 256):
                break
            j = k
        # A declared table cuts itself at its interior labels and pointer
        # targets (see _emit_spec_pieces), so ending the segment at one would
        # truncate the table and leave the remainder without its spec.
        sources = [self.data_tables, self.labels]
        if not self._splits_itself(seg, j):
            sources.append(self.ptr_data_targets)
        stops = [min((t for t in src if seg < t < j), default=0)
                 for src in sources]
        stops = [s for s in stops if s]
        return min(stops) if stops else j

    def _emit_slot_record_table(self, seg, j):
        nwords = self.dis.slot_record_tables[seg]
        self._label_line(seg)
        self.lines.append(f"\t; ${offset_to_cpu(seg):04x}, {j - seg} bytes "
                          f"({(j - seg) // (2 * nwords)} records x "
                          f"{nwords} slot words)")
        self.lines.extend(render_slot_records(self.rom, seg, j, nwords,
                                              self._slot_ref))

    def _emit_declared_table(self, seg, j, bank):
        """A declared data table renders as structured source inline, using the
        same renderers extract.py applies to blobs."""
        self._label_line(seg)
        self._emit_spec_pieces(seg, j, bank, self.data_tables[seg],
                               records=True)

    def _emit_spec_pieces(self, start, end, bank, spec, records=False):
        """Render [start, end) under `spec`, one piece per cut point, so a
        pointer into the middle of a table anchors a label there instead of
        staying a bare address."""
        for a, b in self._pieces(start, end, spec):
            if a != start:
                self.lines.append(f"{self._auto_name(a)}:")
            self._emit_spec_piece(a, b, bank, spec, records)

    def _emit_spec_piece(self, start, end, bank, spec, records):
        """One piece of a declared table. `records` selects the record-table
        renderers, which apply to a table declared in an unclassified run but
        not to a proven blob of the same shape (that keeps extract.py's plain
        rendering)."""
        if spec in GENERATED_SPECS:
            self._emit_generated_spec(start, end - start, bank, spec)
            return
        self.lines.append(
            f"\t; ${offset_to_cpu(start):04x}, {end - start} bytes ({spec})")
        if spec == "actor_script":
            if self._emit_actor_script(start, end, bank):
                return
            if records:
                self.lines.append("\tdb " + ", ".join(
                    f"${x:02x}" for x in self.rom[start:end]))
                return
        rows = self._render_record_spec(spec, start, end, bank) \
            if records else None
        if rows is None:
            rows = self._render_table_spec(spec, start, end, bank)
        if rows is None:
            self._extend_spec(self.rom[start:end], spec)
        else:
            self.lines.extend(rows)

    def _emit_raw_segment(self, seg, j, bank):
        """A segment with no declared structure: game text, a couple of loose
        bytes, or an extracted blob."""
        cpu = offset_to_cpu(seg)
        n = j - seg
        if self._looks_like_text(seg, j):
            # text renders as generated db source (still under gitignored
            # data/, so no ROM content lands in the repository)
            blob = f"bank_{bank:03x}/text_{cpu:04x}.asm"
            self.lines.append(
                f"{self.labels.get(seg, f'Text_{bank:02x}_{cpu:04x}')}:")
            self.lines.append(f'\tINCLUDE "data/{blob}" ; ${cpu:04x}, {n} bytes')
            self.manifest.append((blob, seg, n, None))
            return
        if seg in self.labels or seg in self.ptr_data_targets:
            self.lines.append(f"{self._auto_name(seg)}:")
        if n <= INLINE_DB_MAX:
            # A tiny inter-code run (alignment padding, a stray constant, or a
            # stranded ret) renders inline rather than as a standalone one/two-
            # byte blob file. A lone $c9 wedged between code is a `ret` descent
            # never reached (its function is entered through a computed
            # jump/call), so emit it as the ret it is.
            for k in range(n):
                b = self.rom[seg + k]
                mn = "ret" if b == 0xC9 else f"db ${b:02x}"
                self.lines.append(f"\t{mn} ; ${offset_to_cpu(seg + k):04x}")
        else:
            self.lines.append(self._incbin(seg, n, bank))

    def _looks_like_text(self, seg, j):
        """ASCII dominance (plus the $00-$03 text control codes) marks a text
        region; a leading string offset table (header word + ascending dw run)
        is binary, so skip it before measuring. A word-space floor rejects
        glyph/tile tables that fall in the printable range but hold no prose
        (real game text runs 12-33% spaces; such tables hold ~0)."""
        rom = self.rom
        n = j - seg
        p, prev = seg + 2, -1
        while p + 1 < j:
            w = rom[p] | (rom[p + 1] << 8)
            if w < prev:
                break
            prev, p = w, p + 2
        body = seg if p - seg < 18 else p
        m = j - body
        txt = sum(1 for b in rom[body:j] if 0x20 <= b < 0x7F or b <= 3)
        letters = sum(1 for b in rom[body:j] if 0x61 <= (b | 0x20) <= 0x7A)
        spaces = rom[body:j].count(0x20)
        # A short run splits out of a string pool only when a curated label
        # names it, so one label per string can make a pointer table symbolic;
        # the size floors still guard the unlabeled auto-detection. It must
        # still look like a *string*: terminated, and more than one letter --
        # otherwise naming a 5-byte row of tile ids (`bbebb`) turns a record
        # table into prose.
        named_string = (seg in self.labels and 3 <= n < 32 and txt == n
                        and letters >= 2 and self.rom[j - 1] == 0)
        return bool(named_string or (n >= 32 and m >= 32 and txt >= m * 0.95
                                     and letters >= m // 3 and spaces >= m // 20))

    # ---- data-table specs ------------------------------------------------

    def _render_table_spec(self, spec, start, end, bank):
        """The renderers a table can use wherever it appears -- inside a proven
        blob or in an unclassified run. Returns lines, or None if `spec` is not
        one of them."""
        if spec.startswith("map_"):
            return render_map_table(spec, self.rom, start, end, bank, self.labels)
        if spec == "tilemap_scripts":
            return render_tilemap_scripts(self.rom, start, end)
        if spec == "flag_ids":
            return render_flag_ids(self.rom, start, end, self.flag_names)
        if spec == "save_flag_ids":
            return render_save_flag_ids(self.rom, start, end,
                                        self._save_flag_names())
        if spec == "tilemap_dispatch":
            return render_tilemap_dispatch(self.rom, start, end)
        if spec == "sprite_anim":
            return render_sprite_anim(self.rom, start, end)
        if spec == "text_ids":
            return render_text_ids(self.rom, start, end)
        if spec == "text_offsets":
            # the pool the offsets are relative to starts where the table ends
            label = self.labels.get(end)
            if label:
                return render_text_offsets(self.rom, start, end, end, label)
            return None
        if spec == "gfx_ptr_table":
            return render_gfx_ptr_table(self.rom, start, end, bank,
                                        self.data_labels)
        if spec == "lz_ptr_table":
            return render_lz_ptr_table(self.rom, start, end, bank,
                                       self.data_labels)
        if spec == "char_lz_ptr_table":
            return render_lz_ptr_table(self.rom, start, end, bank,
                                       self.data_labels, CHAR_ROSTER)
        if spec == "mugshot_ptr_table":
            return render_mugshot_ptr_table(self.rom, start, end, bank,
                                            self.data_labels)
        if spec.startswith("enum:"):
            _, prefix, cols = spec.split(":")
            return render_enum_table(self.rom[start:end],
                                     self._enum_values(prefix), int(cols))
        return None

    def _render_record_spec(self, spec, start, end, bank):
        """Record-table renderers, which only apply to a table declared in an
        unclassified run (a proven blob of the same shape keeps extract.py's
        plain rendering). Returns lines, or None if `spec` is not one."""
        if spec in ("records:2", "mode_hooks", "minigame_configs"):
            return render_pointer_words(self.rom, start, end, bank,
                                        self.ptr_names, spec)
        if spec == "story_locations":
            return render_story_locations(self.rom, start, end, self._slot_ref)
        if spec.startswith("rules_pages:"):
            return render_rules_pages(self.rom, start, end,
                                      int(spec.split(":")[1]))
        if spec.startswith("menu_def:"):
            return render_menu_def(self.rom, start, end,
                                   self._enum_values(spec.split(":")[1]))
        if spec == "drill_definition":
            return render_drill_definition(self.rom, start, end, bank, self.labels)
        if spec == "actor_list":
            return render_actor_list(self.rom, start, end, bank, self.labels)
        if spec == "rect_ptrs":
            return render_rect_ptrs(self.rom, start, end, bank, self.labels)
        if spec == "rect_pair":
            return render_rect_pair(self.rom, start, end, bank, self.labels)
        return None

    def _emit_actor_script(self, start, end, bank):
        """Actor-script bytecode, plus any unclassified tail after the decoded
        prefix. Returns False (emitting nothing) if the region doesn't decode,
        which leaves the caller to render it as plain data."""
        result = render_actor_script(self.rom, start, end, bank, self.labels)
        if result is None:
            return False
        rows, used = result
        self.lines.extend(rows)
        if used < end - start:
            tail, tcpu, tlen = start + used, offset_to_cpu(start + used), \
                (end - start) - used
            if all(b == 0xFF for b in self.rom[tail:end]):
                self.lines.append(f"\tds {tlen}, $ff ; ${tcpu:04x}, fill")
            else:
                self.lines.append(self._incbin(tail, tlen, bank,
                                               note=" (unclassified tail)"))
        return True

    def _enum_values(self, prefix):
        """{value: name} for the constants.inc names starting with `prefix`_."""
        return {v: n for n, v in self.const_defs.items()
                if n.startswith(prefix + "_")}

    # ---- output helpers --------------------------------------------------

    def _label_line(self, off):
        """The offset's label, unless the previous line already declared it."""
        if off in self.labels and self.lines[-1] != f"{self.labels[off]}:":
            self.lines.append(f"{self.labels[off]}:")

    def _auto_name(self, off):
        """The name a pointer target carries: its curated label if it has one,
        otherwise the generated Data_ name every cut point gets."""
        return self.labels.get(
            off, f"Data_{off // BANK_SIZE:02x}_{offset_to_cpu(off):04x}")

    @staticmethod
    def _between(sorted_offsets, start, end):
        i = bisect.bisect_right(sorted_offsets, start)
        out = []
        while i < len(sorted_offsets) and sorted_offsets[i] < end:
            out.append(sorted_offsets[i])
            i += 1
        return out

    def _pieces(self, start, end, spec=None):
        """[start, end) as (from, to) pairs cut at every interior pointer
        target, so each one can anchor a label. A region whose rendering does
        not survive being cut (see is_splittable) stays in one piece."""
        if spec is not None and not is_splittable(spec):
            return [(start, end)]
        cuts = set(self._between(self.ptr_cuts, start, end))
        if spec is not None:
            # A cut that is not on a row boundary means the pointer it came
            # from falls back to a numeric operand (see run()).
            cuts = self._valid_cuts(spec, start, end, cuts)
        bounds = [start] + sorted(cuts) + [end]
        return list(zip(bounds, bounds[1:]))

    # The row size a spec's rendering repeats at. A cut that does not land on
    # one is not a row boundary, which means the declaration does not really
    # reach that far -- an over-running `palettes` run cut every 5 bytes would
    # otherwise render 5-byte "palettes".
    _STRIDES = {"palettes": 8, "text_ids": 2, "flag_ids": 2}

    def _stride(self, spec):
        # `bytes:N`/`tilemap:N` count display columns, not records -- their rows
        # regroup around a cut -- so only a real record size constrains one.
        kind, _, param = (spec or "").partition(":")
        if kind == "records" and param.isdigit():
            return int(param)
        return self._STRIDES.get(kind)

    def _actor_list_starts(self, start, end):
        """Where a new actor list begins inside a `map_actors` run. A slot can
        hold several back-to-back lists (runtime-selected variants), each 14-byte
        record run ended by the 9x$00 + $ff sentinel SpawnActorsFromList stops
        on, and a pointer into the run selects one of them. Mirrors
        render_map_table's walk so a cut always lands where it starts a list."""
        rom, out, p = self.rom, set(), start
        while True:
            while p + 14 <= end and rom[p + 9] != 0xFF:
                p += 14
            if p + 10 > end or rom[p:p + 10] != b"\x00" * 9 + b"\xff":
                return out
            p += 10
            if p >= end:
                return out
            out.add(p)

    def _valid_cuts(self, spec, start, end, cuts):
        """The subset of `cuts` a piece boundary may land on for this spec."""
        if spec.partition(":")[0] == "map_actors":
            return cuts & self._actor_list_starts(start, end)
        stride = self._stride(spec)
        if not stride:
            return set(cuts)
        return {o for o in cuts if (o - start) % stride == 0}

    def _report_truncations(self):
        seen = sorted(set(self.truncated))
        if not seen:
            return
        import os
        if os.environ.get("SHOW_TRUNCATIONS"):
            for off, name, spec in seen:
                print(f"  0x{off:x} {name} (inside {spec})")
        head = ", ".join(n for _o, n, _s in seen[:3])
        more = f", +{len(seen) - 3} more" if len(seen) > 3 else ""
        print(f"note: {len(seen)} pointer targets are named at the end of a "
              f"declared table, so what they point at renders as an anonymous "
              f"blob ({head}{more}); declaring them in data_tables.json keeps "
              f"the structure.")

    _SPEC_LINE_RE = re.compile(r"^\t; \$([0-9a-f]{4}), (\d+) bytes \(([^)]+)\)$")
    _BLOB_LINE_RE = re.compile(r'^\tINCBIN "data/[^"]*/d_[0-9a-f]{4}\.bin" ; \$([0-9a-f]{4})')

    def _check_truncated_tables(self, lines, bank):
        """Flag a named offset that ends a declared table. Naming a cut point is
        how a payload gets a symbol, but the name also ends the region, so the
        bytes after it lose the table's spec and fall out as an anonymous blob
        unless they are declared too. The build stays byte-perfect either way,
        so this would otherwise be silent."""
        run = None   # (start cpu, end cpu, spec) of the last declared region
        for i, line in enumerate(lines[:-1]):
            m = self._SPEC_LINE_RE.match(line)
            if m:
                start, n = int(m.group(1), 16), int(m.group(2))
                run = (start, start + n, m.group(3))
                continue
            if not _LABEL_LINE_RE.match(line):
                continue
            b = self._BLOB_LINE_RE.match(lines[i + 1])
            if not b or not run:
                continue
            off = bank * BANK_SIZE + run[1] - BANK_SIZE if bank else run[1]
            # Only a *cut point* -- an offset something in the bank points at,
            # which is why it got a name -- signals a truncated table. A name at
            # a table's natural end is just the next thing starting. (A named
            # target is not in ptr_data_targets, so ask the source instead.)
            name = line[:-1]
            if int(b.group(1), 16) == run[1] and is_splittable(run[2]) \
                    and any(l.strip().startswith(("dw " + name, "ld hl, " + name,
                                                  "ld de, " + name, "ld bc, " + name))
                            for l in lines):
                self.truncated.append((off, name, run[2]))

    def _splits_itself(self, start, end):
        """True if the region [start, end) renders in pieces, so the run and
        segment scans must not end at a label or pointer target inside it.
        False when a cut would fall mid-row: the spec is then wrong about its
        own extent, and ending the run there is right. A *curated* label always
        ends the region -- a human naming an offset is the strongest available
        statement that a new structure starts there, and carrying a spec past
        one turned bank $1b's coordinate arrays into `records:2` pointers."""
        spec = self.data_tables.get(start)
        if not is_splittable(spec):
            return False
        cuts = set(self._between(self.ptr_cuts, start, end))
        return self._valid_cuts(spec, start, end, cuts) == cuts

    def _incbin(self, start, length, bank, prefix="d", note=""):
        """Register a blob in the manifest and return its INCBIN line."""
        cpu = offset_to_cpu(start)
        blob = f"bank_{bank:03x}/{prefix}_{cpu:04x}.bin"
        self.manifest.append((blob, start, length, None))
        return f'\tINCBIN "data/{blob}" ; ${cpu:04x}, {length} bytes{note}'

    def _emit_generated_spec(self, start, length, bank, spec):
        """A spec whose rows are ROM values rather than derived structure:
        generate it into gitignored data/ at setup and INCLUDE it, the same way
        game text is handled, so the repository carries no such content."""
        cpu = offset_to_cpu(start)
        blob = f"bank_{bank:03x}/{spec}_{cpu:04x}.asm"
        self.manifest.append((blob, start, length, spec))
        self.lines.append(
            f'\tINCLUDE "data/{blob}" ; ${cpu:04x}, {length} bytes ({spec})')

    def _extend_spec(self, data, spec):
        """Render bytes with extract.py's renderer for `spec`."""
        self.lines.extend(render_spec(data, spec).rstrip("\n").split("\n"))

    def _write_include(self, name, text):
        self.srcdir.parent.joinpath("include", name).write_text(text)

    def _write_text_ids(self):
        """Dialogue text-id constants collected while rendering (script_set_text
        operands and map_script text-id handlers). Name = the string's
        bank:index coordinate; value = the raw id, so the assembled bytes are
        unchanged. Look a string up with
        `tools/strings.py --index --bank <bank>`."""
        lines = list(_TEXT_IDS_HEADER)
        lines += [f"def {name} equ ${idv:04x}"
                  for idv, name in sorted(TEXT_IDS_USED.items())]
        lines.append("")
        self._write_include("text_ids.inc", "\n".join(lines))

    def _save_flag_names(self):
        """{id word: SAVEFLAG_* name} inverted from constants.inc."""
        return {v: k for k, v in self.const_defs.items()
                if k.startswith("SAVEFLAG_")}

    def _write_flag_constants(self):
        """wGameFlags bit names from flags.json. Value = the flag number
        (byte * 8 + bit), which is what the one-argument set_flag/clear_flag/
        test_flag and flag_id macro forms take, and what the
        *GameFlagByNumber helpers ($00:$24ef) are passed directly."""
        lines = list(_FLAG_CONSTANTS_HEADER)
        prev = None
        for num, name in sorted(self.flag_names.items()):
            if prev is not None and num // 8 != prev // 8:
                lines.append("")
            lines.append(f"def {name} equ {num}"
                         f" ; wGameFlags byte ${num // 8:02x} bit {num % 8}")
            prev = num
        lines.append("")
        self._write_include("flag_constants.inc", "\n".join(lines))

    def _write_manifest(self):
        with open(self.manifest_path, "w") as f:
            f.write("# path  rom_offset(hex)  length(hex)  [render-spec] "
                    "— consumed by tools/extract.py\n")
            for blob, off, length, spec in self.manifest:
                f.write(f"{blob} {off:06x} {length:x}"
                        + (f" {spec}\n" if spec else "\n"))
