"""RAM symbols: naming operands and generating the RAM layout source.

ram_map.json gives one name per address; ram_unions.json describes the ranges
several subsystems reuse, where the name depends on the referencing site (its
ROM location and/or the WRAM bank selected there -- see compute_wram_bank).
Both feed operand rendering and the generated ram.asm + ram/*.asm layout.
"""
import json
import re
import sys
from collections import deque
from pathlib import Path

from .rom import BANK_SIZE, target_to_offset


def region_prefix(addr):
    """Expected name prefix for a RAM address, by memory region."""
    if 0x8000 <= addr < 0xa000:
        return "v"
    if 0xa000 <= addr < 0xc000:
        return "s"
    if 0xc000 <= addr < 0xe000:
        return "w"
    if addr >= 0xff80:
        return "h"
    return None


# RAM regions in memory order: (start, end, rgbds memory type, layout file).
# One fixed-address SECTION per region holds its named symbols and ds gaps, so
# every symbol is defined once and exported (::) for the linker to resolve
# across bank objects.
RAM_REGIONS = [
    (0xa000, 0xc000, "SRAM", "ram/sram.asm"),
    (0xc000, 0xd000, "WRAM0", "ram/wram.asm"),
    (0xd000, 0xe000, "WRAMX", "ram/wram.asm"),
    (0xff80, 0xffff, "HRAM", "ram/hram.asm"),
]

_GENERATED_HDR = (
    "; RAM layout from ram_map.json (RetroAchievements Code Notes).\n"
    "; Regenerated by tools/disasm.py; do not edit by hand.\n"
)


def ram_field_size(e):
    """Byte width of a RAM symbol, from its Code Note tag or size field."""
    note = e.get("note", "") or ""
    m = re.match(r"\s*\[(\d+)\s*byte", note, re.IGNORECASE)
    if m:
        return int(m.group(1))
    if re.match(r"\s*\[16-bit", note, re.IGNORECASE):
        return 2
    if re.match(r"\s*\[32-bit", note, re.IGNORECASE):
        return 4
    return e.get("size", 1) or 1


def _ds_directive(size):
    return {1: "db", 2: "dw"}.get(size, f"ds {size}")


def _scope_to_flat(s):
    """Convert a union-variant scope ({bank[, start, end] in CPU addresses})
    to a flat-offset half-open range."""
    bank = int(s["bank"], 0)
    if "start" in s:
        st, en = int(s["start"], 0), int(s["end"], 0)
        if bank == 0:
            return (st, en)
        return (bank * BANK_SIZE + st - 0x4000, bank * BANK_SIZE + en - 0x4000)
    return (bank * BANK_SIZE, (bank + 1) * BANK_SIZE)


def _scope_to_matcher(s):
    """A union-variant scope -> (flat_range_or_None, wram_bank_or_None). `bank`
    (with optional start/end) constrains the *referencing code's* ROM location;
    `wram_bank` constrains the WRAM bank provably selected there (see
    compute_wram_bank). Either may be given; a site matches when every present
    constraint holds. A scope with neither would match everywhere -- rejected by
    load_ram_unions."""
    rng = _scope_to_flat(s) if "bank" in s else None
    wb = int(s["wram_bank"], 0) if "wram_bank" in s else None
    return (rng, wb)


class ScopedRamNames:
    """RAM symbols whose name depends on the referencing site -- its ROM
    location and/or the WRAM bank selected there (union variants). resolve()
    picks the variant whose scope matches; a default variant applies only
    outside every scoped variant's ROM ranges, so unknown consumers inside a
    scoped engine stay numeric. `bank_at` (a rom-offset -> WRAM bank map from
    compute_wram_bank) is supplied before rendering; a wram_bank constraint
    fails wherever the bank is not provably known."""

    def __init__(self):
        self.by_addr = {}
        self.sized = []   # (base, size, matchers, name) for interior expansion
        self.bank_at = {}

    def add(self, addr, name, matchers, size=1, default_mask=None):
        e = self.by_addr.setdefault(addr, {"scoped": [], "default": None,
                                           "mask": []})
        if default_mask is not None:
            e["default"] = name
            e["mask"] = default_mask
        else:
            e["scoped"].append((matchers, name))
            if size > 1:
                self.sized.append((addr, size, matchers, name))

    def _match(self, matchers, off):
        for rng, wb in matchers:
            if rng is not None and not (rng[0] <= off < rng[1]):
                continue
            if wb is not None and self.bank_at.get(off) != wb:
                continue
            return True
        return False

    def resolve(self, addr, off):
        e = self.by_addr.get(addr)
        if e:
            for matchers, name in e["scoped"]:
                if self._match(matchers, off):
                    return name
            if e["default"] and not any(lo <= off < hi for lo, hi in e["mask"]):
                return e["default"]
        # interior byte of a multi-byte scoped field -> `name + k` (mirrors the
        # ram_map.json expansion; an interior byte that is itself an explicit
        # symbol matched above and returned before reaching here)
        for base, size, matchers, name in self.sized:
            if base < addr < base + size and self._match(matchers, off):
                return f"{name} + {addr - base}"
        return None


def compute_wram_bank(dis):
    """Forward CFG dataflow computing, per instruction, the WRAM bank
    ($ff70/rSVBK) provably selected on entry -- or absent when unknown or
    conflicting. `a` is tracked so the `ld a,N; ldh [rWBK],a` idiom (the
    wram_bank macro) resolves; any other write to `a` marks it unknown, which
    keeps the analysis conservative. Calls are assumed to preserve the bank:
    the return edge carries the pre-call bank (clobbering `a`), and the caller's
    bank also flows into the callee so a helper reached from a single banked
    context inherits it. Purely informative -- RAM operand names are text, so a
    wrong result can only mislabel, never change an assembled byte."""
    rom, instrs, farcalls = dis.rom, dis.instrs, dis.farcalls
    UNK, NOINFO = None, "?"

    def meet(x, y):
        if x is NOINFO:
            return y
        if y is NOINFO:
            return x
        return x if x == y else UNK

    def transfer(off, st):
        bank, a = st
        op = rom[off]
        if op == 0x3E:                                   # ld a, imm8
            return (bank, rom[off + 1])
        if op == 0xE0:                                   # ldh [n8], a
            if rom[off + 1] == 0x70:                     # rWBK <- a
                return (a if a is not NOINFO else UNK, a)
            return (bank, a)                             # e.g. hWramBank shadow
        if op == 0xEA and rom[off + 1] == 0x70 and rom[off + 2] == 0xff:
            return (a if a is not NOINFO else UNK, a)    # ld [$ff70], a
        return (bank, UNK)                               # any other op clobbers a

    IN = {}
    work = deque(instrs)
    inq = set(instrs)
    while work:
        off = work.popleft()
        inq.discard(off)
        out = transfer(off, IN.get(off, (NOINFO, NOINFO)))
        ins = instrs[off]
        edges = []
        if ins.is_call:
            tgt = (farcalls[off][3] if off in farcalls
                   else target_to_offset(ins.target, off)
                   if ins.target is not None else None)
            if tgt in instrs:
                edges.append((tgt, out))
            if not ins.ends_flow:                        # return: bank kept, a lost
                edges.append((off + ins.size, (out[0], UNK)))
        else:
            if not ins.ends_flow:
                edges.append((off + ins.size, out))
            if ins.is_jump and ins.target is not None:
                t = target_to_offset(ins.target, off)
                if t in instrs:
                    edges.append((t, out))
        for s, es in edges:
            if s not in instrs:
                continue
            cur = IN.get(s, (NOINFO, NOINFO))
            new = (meet(cur[0], es[0]), meet(cur[1], es[1]))
            if new != cur:
                IN[s] = new
                if s not in inq:
                    work.append(s)
                    inq.add(s)
    return {o: st[0] for o, st in IN.items() if isinstance(st[0], int)}


def load_ram_unions(path):
    """Load ram_unions.json: address ranges reused by several subsystems
    (RGBDS UNION/NEXTU overlays). Returns (unions_by_region, ScopedRamNames)."""
    unions_by_region, scoped = {}, ScopedRamNames()
    if not Path(path).exists():
        return unions_by_region, scoped
    data = json.loads(Path(path).read_text())
    for u in data.get("unions", []):
        start, end = int(u["start"], 0), int(u["end"], 0)
        for v in u["variants"]:
            for s in v.get("scopes", []):
                if "bank" not in s and "wram_bank" not in s:
                    print(f"warning: {path}: union {u['start']} scope {s} has "
                          f"neither bank nor wram_bank (matches everywhere)",
                          file=sys.stderr)
        # default variant applies outside every scoped variant's ROM ranges
        # (wram_bank-only scopes contribute no ROM mask)
        mask = [m[0] for v in u["variants"]
                for m in (_scope_to_matcher(s) for s in v.get("scopes", []))
                if m[0] is not None]
        variants = []
        for v in u["variants"]:
            matchers = [_scope_to_matcher(s) for s in v.get("scopes", [])]
            syms = []
            for addr_s, e in sorted(v["symbols"].items(),
                                    key=lambda kv: int(kv[0], 0)):
                addr, name = int(addr_s, 0), e["name"]
                exp = region_prefix(addr)
                if exp and not (name.startswith(exp) and name[1:2].isupper()):
                    print(f"warning: {path}: {addr_s} name {name!r} should be "
                          f"{exp}PascalCase", file=sys.stderr)
                if not start <= addr < end:
                    print(f"warning: {path}: {addr_s} outside union "
                          f"${start:04x}-${end:04x}", file=sys.stderr)
                syms.append((addr, name, ram_field_size(e), e.get("note", "")))
                if v.get("default"):
                    scoped.add(addr, name, None, default_mask=mask)
                else:
                    scoped.add(addr, name, matchers, ram_field_size(e))
            variants.append((v.get("context", ""), syms))
        for ri, (rs, re_, _mem, _path) in enumerate(RAM_REGIONS):
            if rs <= start < re_:
                unions_by_region.setdefault(ri, []).append(
                    (start, end, u.get("comment", ""), variants))
                break
        else:
            print(f"warning: {path}: union {u['start']} outside known RAM "
                  f"regions", file=sys.stderr)
    return unions_by_region, scoped


def _emit_union_block(out, start, end, comment, variants):
    for ln in comment.split("\n"):
        out.append(f"; {ln}".rstrip() if ln.strip() else ";")
    out.append("UNION")
    for vi, (context, syms) in enumerate(variants):
        if vi:
            out.append("NEXTU")
        if context:
            out.append(f"; {context}")
        cursor = start
        for addr, name, size, note in syms:
            if addr > cursor:
                out.append(f"\tds {addr - cursor}")
            for ln in (note or "").split("\n"):
                out.append(f"; {ln}".rstrip() if ln.strip() else ";")
            out.append(f"{name}:: {_ds_directive(size)}")
            cursor = addr + size
        if vi == 0 and cursor < end:
            out.append(f"\tds {end - cursor}")
    out.append("ENDU")
    out.append("")


def write_ram_layout(regions, unions_by_region=None):
    """Emit ram.asm + ram/*.asm from {region_index: [(addr, name, size, note)]}.
    Each region becomes one fixed-address SECTION; ds fills the gaps between
    named symbols so every symbol lands at its exact hardware address."""
    files = {}  # layout file -> list of section text blocks
    unions_by_region = unions_by_region or {}
    for ri, (start, end, mem, path) in enumerate(RAM_REGIONS):
        items = [("sym", addr, name, size, note)
                 for addr, name, size, note in regions.get(ri, [])]
        for ustart, uend, comment, variants in unions_by_region.get(ri, []):
            for addr, *_rest in regions.get(ri, []):
                if ustart <= addr < uend:
                    raise SystemExit(
                        f"ram_map/ram_unions conflict: ${addr:04x} inside "
                        f"union ${ustart:04x}-${uend:04x}")
            items.append(("union", ustart, uend, comment, variants))
        if not items:
            continue
        items.sort(key=lambda t: t[1])
        base = items[0][1]
        out = [f'SECTION "{mem} ${base:04x}", {mem}[${base:04x}]', ""]
        for i, item in enumerate(items):
            nxt = items[i + 1][1] if i + 1 < len(items) else end
            if item[0] == "union":
                _tag, ustart, uend, comment, variants = item
                _emit_union_block(out, ustart, uend, comment, variants)
                gap = nxt - uend
                if gap > 0 and i + 1 < len(items):
                    out.append(f"\tds {gap}")
                    out.append("")
                continue
            _tag, addr, name, size, note = item
            span = nxt - addr
            emitted = max(1, min(size, span))
            for ln in (note or "").split("\n"):
                out.append(f"; {ln}".rstrip() if ln.strip() else ";")
            out.append(f"{name}:: {_ds_directive(emitted)}")
            gap = span - emitted
            if gap > 0 and i + 1 < len(items):
                out.append(f"\tds {gap}")
            out.append("")
        files.setdefault(path, []).append("\n".join(out).rstrip() + "\n")

    for path, blocks in files.items():
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(_GENERATED_HDR + "\n" + "\n\n".join(blocks))

    includes = []
    for _ri, (_s, _e, _m, path) in enumerate(RAM_REGIONS):
        if path in files and f'INCLUDE "{path}"' not in includes:
            includes.append(f'INCLUDE "{path}"')
    Path("ram.asm").write_text(_GENERATED_HDR + "\n" + "\n".join(includes) + "\n")


def load_ram_map(path, unions_by_region=None):
    """Map RAM addresses to names from ram_map.json (for operand rendering) and
    emit the RAM layout files (ram.asm + ram/*.asm)."""
    if not Path(path).exists():
        return {}
    entries = json.loads(Path(path).read_text())
    names = {}
    regions = {}
    extents = []
    for addr_s, e in sorted(entries.items(), key=lambda kv: int(kv[0], 0)):
        name = e.get("name")
        if not name:
            continue
        addr = int(addr_s, 0)
        exp = region_prefix(addr)
        if exp and not (name.startswith(exp) and name[1:2].isupper()):
            print(f"warning: {path}: {addr_s} name {name!r} should be "
                  f"{exp}PascalCase", file=sys.stderr)
        names[addr] = name
        size = ram_field_size(e)
        extents.append((addr, size, name))
        for ri, (start, end, _mem, _path) in enumerate(RAM_REGIONS):
            if start <= addr < end:
                regions.setdefault(ri, []).append(
                    (addr, name, size, e.get("note", "")))
                break
        else:
            print(f"warning: {path}: {addr_s} outside known RAM regions",
                  file=sys.stderr)
    # A reference to an interior byte of a multi-byte variable (e.g. the low
    # byte of the 16-bit wCurrentMinigameStoryMatch) renders as `name + k`
    # rather than a raw address. An interior byte that is itself a named symbol
    # keeps its own name (the explicit entry, added above, is never overwritten).
    for base, size, name in extents:
        for k in range(1, size):
            names.setdefault(base + k, f"{name} + {k}")
    write_ram_layout(regions, unions_by_region)
    return names
