"""RAM symbols: naming operands and generating the RAM layout source.

ram_map.json gives one name per address; ram_unions.json describes the ranges
several subsystems reuse, where the name depends on the referencing site (its
ROM location and/or the WRAM bank selected there -- see compute_wram_bank).
Both feed operand rendering and the generated ram.asm + ram/*.asm layout.
"""
import json
import re
import sys
from collections import deque
from pathlib import Path

from .rom import BANK_SIZE, target_to_offset


def region_prefix(addr):
    """Expected name prefix for a RAM address, by memory region."""
    if 0x8000 <= addr < 0xa000:
        return "v"
    if 0xa000 <= addr < 0xc000:
        return "s"
    if 0xc000 <= addr < 0xe000:
        return "w"
    if addr >= 0xff80:
        return "h"
    return None


# RAM regions in memory order: (start, end, rgbds memory type, layout file).
# One fixed-address SECTION per region holds its named symbols and ds gaps, so
# every symbol is defined once and exported (::) for the linker to resolve
# across bank objects.
RAM_REGIONS = [
    (0xa000, 0xc000, "SRAM", "ram/sram.asm"),
    (0xc000, 0xd000, "WRAM0", "ram/wram.asm"),
    (0xd000, 0xe000, "WRAMX", "ram/wram.asm"),
    (0xff80, 0xffff, "HRAM", "ram/hram.asm"),
]

# Bank-switched regions get one SECTION per bank rather than one per region:
# WRAMX is 7 banks at $d000 (rWBK), SRAM is 4 x 8 KiB at $a000 (the MBC
# RAM-bank register at $4000, shadowed in hSramBank). The same address means a
# different variable in each, so the layout has to say which one. The json key
# naming a symbol's bank, per region:
BANK_KEY = {"WRAMX": "wram_bank", "SRAM": "sram_bank"}

_GENERATED_HDR = (
    "; RAM layout from ram_map.json (RetroAchievements Code Notes).\n"
    "; Regenerated by tools/disasm.py; do not edit by hand.\n"
)


def ram_field_size(e):
    """Byte width of a RAM symbol, from its Code Note tag or size field."""
    note = e.get("note", "") or ""
    m = re.match(r"\s*\[(\d+)\s*byte", note, re.IGNORECASE)
    if m:
        return int(m.group(1))
    if re.match(r"\s*\[16-bit", note, re.IGNORECASE):
        return 2
    if re.match(r"\s*\[32-bit", note, re.IGNORECASE):
        return 4
    return e.get("size", 1) or 1


def _ds_directive(size):
    return {1: "db", 2: "dw"}.get(size, f"ds {size}")


def _stride(e):
    """A symbol's `stride` entry: ["CONSTANT", value]. The constant is what the
    rendered expression multiplies by, the value is what this generator divides
    by -- both are stated so a wrong pairing cannot hide."""
    s = e.get("stride")
    return (s[0], int(s[1], 0) if isinstance(s[1], str) else s[1]) if s else None


def grid_offset(name, k, stride):
    """Render an offset into a symbol. A `stride` entry (the tilemap buffers,
    whose rows are TILEMAP_WIDTH apart) makes the row and column visible:
    `wShadowTilemap + 10 * TILEMAP_WIDTH + 17` instead of `+ 337`. rgbasm folds
    it to the same word, so `make compare` still checks the arithmetic.

    A statement macro (pokecrystal's `hlcoord`) cannot serve here: these
    addresses appear as `ld [addr], a` and inside `dw` rows as well as `ld rr,
    addr`, and RGBDS has no expression-returning macro. An expression is the one
    form every position accepts."""
    if not k:
        return name
    if not stride:
        return f"{name} + {k}"
    row, col = divmod(k, stride[1])
    parts = [name]
    if row:
        parts.append(f"{row} * {stride[0]}")
    if col:
        parts.append(str(col))
    return " + ".join(parts)


def _scope_to_flat(s):
    """Convert a union-variant scope ({bank[, start, end] in CPU addresses})
    to a flat-offset half-open range."""
    bank = int(s["bank"], 0)
    if "start" in s:
        st, en = int(s["start"], 0), int(s["end"], 0)
        if bank == 0:
            return (st, en)
        return (bank * BANK_SIZE + st - 0x4000, bank * BANK_SIZE + en - 0x4000)
    return (bank * BANK_SIZE, (bank + 1) * BANK_SIZE)


def _scope_to_matcher(s):
    """A union-variant scope -> (flat_range_or_None, wram_bank_or_None). `bank`
    (with optional start/end) constrains the *referencing code's* ROM location;
    `wram_bank` constrains the WRAM bank provably selected there (see
    compute_wram_bank). Either may be given; a site matches when every present
    constraint holds. A scope with neither would match everywhere -- rejected by
    load_ram_unions."""
    rng = _scope_to_flat(s) if "bank" in s else None
    wb = int(s["wram_bank"], 0) if "wram_bank" in s else None
    return (rng, wb)


class ScopedRamNames:
    """RAM symbols whose name depends on the referencing site -- its ROM
    location and/or the WRAM bank selected there (union variants). resolve()
    picks the variant whose scope matches; a default variant applies only
    outside every scoped variant's ROM ranges, so unknown consumers inside a
    scoped engine stay numeric. `bank_at` (a rom-offset -> WRAM bank map from
    compute_wram_bank) is supplied before rendering; a wram_bank constraint
    fails wherever the bank is not provably known."""

    def __init__(self):
        self.by_addr = {}
        self.sized = []   # (base, size, matchers, name, stride) for interiors
        self.sized_default = []   # the same, for a default variant's fields
        self.bank_at = {}

    def add(self, addr, name, matchers, size=1, default_mask=None,
            stride=None):
        e = self.by_addr.setdefault(addr, {"scoped": [], "default": None,
                                           "mask": []})
        if default_mask is not None:
            e["default"] = name
            e["mask"] = default_mask
            # A default variant's multi-byte field expands like any other; it
            # just has to respect the same mask its base does, so the interior
            # of a 16-bit default field does not claim an address inside a
            # scoped variant's range.
            if size > 1:
                self.sized_default.append((addr, size, default_mask, name,
                                           stride))
        else:
            e["scoped"].append((matchers, name))
            if size > 1:
                self.sized.append((addr, size, matchers, name, stride))

    def _match(self, matchers, off, wram_bank=None):
        at = self.bank_at.get(off) if wram_bank is None else wram_bank
        for rng, wb in matchers:
            if rng is not None and not (rng[0] <= off < rng[1]):
                continue
            if wb is not None and at != wb:
                continue
            return True
        return False

    def resolve(self, addr, off, wram_bank=None):
        """`wram_bank` asserts the bank instead of asking compute_wram_bank.
        A data word has no dataflow to read, so a table that holds RAM
        addresses states its bank in its render spec (see render_ram_ptrs)."""
        e = self.by_addr.get(addr)
        if e:
            for matchers, name in e["scoped"]:
                if self._match(matchers, off, wram_bank):
                    return name
            if e["default"] and not any(lo <= off < hi for lo, hi in e["mask"]):
                return e["default"]
        # interior byte of a multi-byte scoped field -> `name + k` (mirrors the
        # ram_map.json expansion; an interior byte that is itself an explicit
        # symbol matched above and returned before reaching here)
        for base, size, matchers, name, stride in self.sized:
            if base < addr < base + size \
                    and self._match(matchers, off, wram_bank):
                return grid_offset(name, addr - base, stride)
        for base, size, mask, name, stride in self.sized_default:
            if base < addr < base + size \
                    and not any(lo <= off < hi for lo, hi in mask):
                return grid_offset(name, addr - base, stride)
        return None


BANKED_WRAM_RE = re.compile(r"\[\$(d[0-9a-f]{3})\]")


def auto_banked_wram_names(dis, scoped, covered, covered_banks=None):
    """Name still-unidentified banked-WRAM addresses `w<bank>_<addr>` (the
    pokecrystal convention) where every site that references them provably
    selects the same WRAM bank. The address alone is ambiguous -- $d000 is
    eight different variables -- so the bank belongs in the name even when the
    purpose is unknown; a curated name in ram_map.json/ram_unions.json always
    wins, since `covered` addresses are skipped here.

    `covered_banks` blocks a span only for the WRAM banks a union claims: a
    union in bank $07 says nothing about bank $03's use of the same addresses,
    and the two land in different SECTIONs, so there is no layout to collide.

    Only the `[$dxxx]` operand form is considered: a word immediate equal to a
    RAM address is more often arithmetic (see RAM_IMM_IS_CONSTANT). Addresses
    whose sites disagree stay numeric -- they are either genuinely per-bank
    copies of one struct or a limit of the dataflow, and both want a human.
    Registered scoped, so a site whose bank is not provable still renders the
    bare address rather than claiming a bank it cannot show."""
    covered_banks = covered_banks or {}
    refs = {}
    for off, ins in dis.instrs.items():
        if "[$d" not in ins.text:
            continue
        for m in BANKED_WRAM_RE.finditer(ins.text):
            addr = int(m.group(1), 16)
            if addr in covered:
                continue
            bank = scoped.bank_at.get(off)
            refs.setdefault(addr, set()).add(
                bank if isinstance(bank, int) else None)
    named = []
    for addr, banks in sorted(refs.items()):
        known = {b for b in banks if b is not None}
        if len(known) != 1:
            continue
        bank = known.pop()
        if bank in covered_banks.get(addr, ()):
            continue
        name = f"w{bank}_{addr:04x}"
        scoped.add(addr, name, [(None, bank)])
        named.append((addr, name, bank))
    return named


def union_banks(variants, ubank):
    """The WRAM banks a union occupies: the banks its variants are scoped to,
    falling back to the bank declared on the union itself. Empty when neither
    says -- an unbanked region, or a union scoped only by referencing ROM bank,
    where the span has to be treated as claiming every bank."""
    banks = set()
    for v in variants:
        banks |= (v[2] or ({ubank} if ubank is not None else set()))
    return banks


def compute_wram_bank(dis):
    """Forward CFG dataflow computing, per instruction, the WRAM bank
    ($ff70/rSVBK) provably selected on entry -- or absent when unknown or
    conflicting. `a` is tracked so the `ld a,N; ldh [rWBK],a` idiom (the
    wram_bank macro) resolves; any other write to `a` marks it unknown, which
    keeps the analysis conservative. Calls are assumed to preserve the bank:
    the return edge carries the pre-call bank (clobbering `a`), and the caller's
    bank also flows into the callee so a helper reached from a single banked
    context inherits it. Purely informative -- RAM operand names are text, so a
    wrong result can only mislabel, never change an assembled byte."""
    rom, instrs, farcalls = dis.rom, dis.instrs, dis.farcalls
    UNK, NOINFO = None, "?"

    def meet(x, y):
        if x is NOINFO:
            return y
        if y is NOINFO:
            return x
        return x if x == y else UNK

    def transfer(off, st):
        bank, a = st
        op = rom[off]
        if op == 0x3E:                                   # ld a, imm8
            return (bank, rom[off + 1])
        if op == 0xE0:                                   # ldh [n8], a
            if rom[off + 1] == 0x70:                     # rWBK <- a
                return (a if a is not NOINFO else UNK, a)
            return (bank, a)                             # e.g. hWramBank shadow
        if op == 0xEA and rom[off + 1] == 0x70 and rom[off + 2] == 0xff:
            return (a if a is not NOINFO else UNK, a)    # ld [$ff70], a
        return (bank, UNK)                               # any other op clobbers a

    IN = {}
    work = deque(instrs)
    inq = set(instrs)
    while work:
        off = work.popleft()
        inq.discard(off)
        out = transfer(off, IN.get(off, (NOINFO, NOINFO)))
        ins = instrs[off]
        edges = []
        if ins.is_call:
            tgt = (farcalls[off][3] if off in farcalls
                   else target_to_offset(ins.target, off)
                   if ins.target is not None else None)
            if tgt in instrs:
                edges.append((tgt, out))
            if not ins.ends_flow:                        # return: bank kept, a lost
                edges.append((off + ins.size, (out[0], UNK)))
        else:
            if not ins.ends_flow:
                edges.append((off + ins.size, out))
            if ins.is_jump and ins.target is not None:
                t = target_to_offset(ins.target, off)
                if t in instrs:
                    edges.append((t, out))
        for s, es in edges:
            if s not in instrs:
                continue
            cur = IN.get(s, (NOINFO, NOINFO))
            new = (meet(cur[0], es[0]), meet(cur[1], es[1]))
            if new != cur:
                IN[s] = new
                if s not in inq:
                    work.append(s)
                    inq.add(s)
    return {o: st[0] for o, st in IN.items() if isinstance(st[0], int)}


def load_ram_unions(path):
    """Load ram_unions.json: address ranges reused by several subsystems
    (RGBDS UNION/NEXTU overlays). Returns (unions_by_region, ScopedRamNames)."""
    unions_by_region, scoped = {}, ScopedRamNames()
    if not Path(path).exists():
        return unions_by_region, scoped
    data = json.loads(Path(path).read_text())
    for u in data.get("unions", []):
        start, end = int(u["start"], 0), int(u["end"], 0)
        for v in u["variants"]:
            for s in v.get("scopes", []):
                if "bank" not in s and "wram_bank" not in s:
                    print(f"warning: {path}: union {u['start']} scope {s} has "
                          f"neither bank nor wram_bank (matches everywhere)",
                          file=sys.stderr)
        # default variant applies outside every scoped variant's ROM ranges
        # (wram_bank-only scopes contribute no ROM mask)
        mask = [m[0] for v in u["variants"]
                for m in (_scope_to_matcher(s) for s in v.get("scopes", []))
                if m[0] is not None]
        variants = []
        for v in u["variants"]:
            matchers = [_scope_to_matcher(s) for s in v.get("scopes", [])]
            syms = []
            for addr_s, e in sorted(v["symbols"].items(),
                                    key=lambda kv: int(kv[0], 0)):
                addr, name = int(addr_s, 0), e["name"]
                exp = region_prefix(addr)
                if exp and not (name.startswith(exp) and name[1:2].isupper()):
                    print(f"warning: {path}: {addr_s} name {name!r} should be "
                          f"{exp}PascalCase", file=sys.stderr)
                if not start <= addr < end:
                    print(f"warning: {path}: {addr_s} outside union "
                          f"${start:04x}-${end:04x}", file=sys.stderr)
                syms.append((addr, name, ram_field_size(e), e.get("note", "")))
                if v.get("default"):
                    scoped.add(addr, name, None, ram_field_size(e),
                               default_mask=mask, stride=_stride(e))
                else:
                    scoped.add(addr, name, matchers, ram_field_size(e),
                               stride=_stride(e))
            wbanks = frozenset(int(s["wram_bank"], 0) for s in v.get("scopes", [])
                               if "wram_bank" in s)
            variants.append((v.get("context", ""), syms, wbanks))
        for ri, (rs, re_, mem, _path) in enumerate(RAM_REGIONS):
            if rs <= start < re_:
                # SRAM's bank is a property of the range, not of a scope: the
                # save engine selects it by hand and no dataflow proves it per
                # site, so it names the section without narrowing any name.
                key = BANK_KEY.get(mem)
                ubank = int(u[key], 0) if key and key in u else None
                if key and ubank is None and not any(v[2] for v in variants):
                    print(f"warning: {path}: union {u['start']} is in banked "
                          f"{mem} but no variant gives a bank", file=sys.stderr)
                unions_by_region.setdefault(ri, []).append(
                    (start, end, u.get("comment", ""), variants, ubank))
                break
        else:
            print(f"warning: {path}: union {u['start']} outside known RAM "
                  f"regions", file=sys.stderr)
    return unions_by_region, scoped


def _emit_union_block(out, start, end, comment, variants):
    """A scoped range from ram_unions.json. UNION/NEXTU is only how *overlapping*
    variants share addresses, so a range left with one variant -- either it
    always had one, or splitting by WRAM bank gave each bank its own -- emits
    its symbols plainly. The scoping itself is unaffected: it lives in
    ScopedRamNames and decides which name renders at a site, not the layout."""
    for ln in comment.split("\n"):
        out.append(f"; {ln}".rstrip() if ln.strip() else ";")
    overlay = len(variants) > 1
    if overlay:
        out.append("UNION")
    for vi, (context, syms, _wbanks) in enumerate(variants):
        if vi:
            out.append("NEXTU")
        if context:
            out.append(f"; {context}")
        cursor = start
        for addr, name, size, note in syms:
            if addr > cursor:
                out.append(f"\tds {addr - cursor}")
            for ln in (note or "").split("\n"):
                out.append(f"; {ln}".rstrip() if ln.strip() else ";")
            out.append(f"{name}:: {_ds_directive(size)}")
            cursor = addr + size
        if vi == 0 and cursor < end:
            out.append(f"\tds {end - cursor}")
    if overlay:
        out.append("ENDU")
    out.append("")


SHARED = "shared"   # WRAMX group key for symbols that are not one bank's


def _group_by_bank(items):
    """Bucket a bank-switched region's items by the bank they live in, so each
    bank reads as its own SECTION instead of one address-ordered list mixing
    all of them. A union whose variants sit in different banks is split across
    those banks' sections -- once the banks separate them the addresses no
    longer collide, so each side keeps only its own variants. Anything not
    attributable to a single bank (the per-character struct, which is one copy
    in each of WRAM banks 4-7, and any ROM-scoped variant) goes to SHARED."""
    groups = {}
    for item in items:
        if item[0] == "union":
            _tag, ustart, uend, comment, variants, ubank = item
            by_bank = {}
            for v in variants:
                banks = v[2] or ({ubank} if ubank is not None else set())
                if len(banks) != 1:
                    by_bank = None
                    break
                by_bank.setdefault(next(iter(banks)), []).append(v)
            if by_bank is None:
                groups.setdefault(SHARED, []).append(item[:5])
                continue
            for bank, vs in by_bank.items():
                groups.setdefault(bank, []).append(
                    ("union", ustart, uend, comment, vs))
            continue
        _tag, addr, name, size, note, bank = item
        groups.setdefault(SHARED if bank is None else bank, []).append(
            ("sym", addr, name, size, note))
    return groups


def _bank_list(banks):
    xs = sorted(banks)
    if len(xs) > 2 and xs == list(range(xs[0], xs[-1] + 1)):
        return f"{xs[0]}-{xs[-1]}"
    return ",".join(str(x) for x in xs)


def _emit_section(out, mem, base, bank, items, end, title=None, note=None):
    """One fixed-address SECTION: ds fills the leading gap and the gaps between
    named symbols, so every symbol lands at its exact hardware address."""
    banked = "" if bank is None else f", BANK[{bank}]"
    title = title or (f"{mem} ${base:04x}" if bank is None
                      else f"{mem} bank {bank}")
    out.append(f'SECTION "{title}", {mem}[${base:04x}]{banked}')
    out.append("")
    if note:
        for ln in note.split("\n"):
            out.append(f"; {ln}".rstrip() if ln.strip() else ";")
        out.append("")
    lead = items[0][1] - base
    if lead > 0:
        out.append(f"\tds {lead}")
        out.append("")
    for i, item in enumerate(items):
        nxt = items[i + 1][1] if i + 1 < len(items) else end
        if item[0] == "union":
            _tag, ustart, uend, comment, variants = item
            _emit_union_block(out, ustart, uend, comment, variants)
            gap = nxt - uend
            if gap > 0 and i + 1 < len(items):
                out.append(f"\tds {gap}")
                out.append("")
            continue
        _tag, addr, name, size, note = item
        span = nxt - addr
        emitted = max(1, min(size, span))
        for ln in (note.split("\n") if note else []):
            out.append(f"; {ln}".rstrip() if ln.strip() else ";")
        out.append(f"{name}:: {_ds_directive(emitted)}")
        gap = span - emitted
        if gap > 0 and i + 1 < len(items):
            out.append(f"\tds {gap}")
        out.append("")


def write_ram_layout(regions, unions_by_region=None):
    """Emit ram.asm + ram/*.asm from
    {region_index: [(addr, name, size, note, bank)]}. Every region opens at its
    own base address, not at its first named symbol, so naming a lower address
    does not move the SECTION. A bank-switched region (see BANK_KEY) is emitted
    one SECTION per bank (see _group_by_bank); the others are one SECTION."""
    files = {}  # layout file -> list of section text blocks
    unions_by_region = unions_by_region or {}
    for ri, (start, end, mem, path) in enumerate(RAM_REGIONS):
        items = [("sym", addr, name, size, note, bank)
                 for addr, name, size, note, bank in regions.get(ri, [])]
        seen_unions = []
        for ustart, uend, comment, variants, ubank in unions_by_region.get(ri, []):
            banks = union_banks(variants, ubank)
            for addr, _name, _size, _note, bank in regions.get(ri, []):
                if ustart <= addr < uend and (not banks or bank in banks):
                    raise SystemExit(
                        f"ram_map/ram_unions conflict: ${addr:04x} inside "
                        f"union ${ustart:04x}-${uend:04x}")
            # Two unions over the same bytes in the same bank would both be
            # emitted, one after the other, and the section would silently grow
            # past the end of the bank -- rgbasm catches that, but only as a
            # size error a long way from the cause. Overlapping variants belong
            # in one union.
            for ostart, oend, obanks in seen_unions:
                if ustart < oend and ostart < uend \
                        and (not banks or not obanks or (banks & obanks)):
                    raise SystemExit(
                        f"ram_unions overlap: ${ustart:04x}-${uend:04x} and "
                        f"${ostart:04x}-${oend:04x} cover the same bytes; "
                        f"make them variants of one union")
            seen_unions.append((ustart, uend, banks))
            items.append(("union", ustart, uend, comment, variants, ubank))
        if not items:
            continue
        if mem in BANK_KEY:
            groups = _group_by_bank(items)
        else:
            groups = {None: [it[:5] for it in items]}   # drop the bank field
        for key in sorted(groups, key=lambda k: (k == SHARED, k)):
            gitems = sorted(groups[key], key=lambda t: t[1])
            bank = None if key is SHARED else key
            # A bank's section owns the whole region, so it opens at the base;
            # SHARED must fit alongside one of them, so it opens at its first
            # symbol and stays out of the banked sections' way.
            base = gitems[0][1] if bank is None and mem in BANK_KEY else start
            title = note = None
            if key is SHARED:
                banks = sorted({b for it in gitems if it[0] == "union"
                                for v in it[4] for b in v[2]})
                title = f"{mem} banks {_bank_list(banks)}"
                note = (f"Not one bank's: these addresses hold the same field in "
                        f"WRAM banks {_bank_list(banks)}\n"
                        f"at once (one copy per character), so the section "
                        f"declares no BANK -- the\nlinker parks it in a free "
                        f"one. The name resolves by the bank selected at\nthe "
                        f"referencing site, which is what makes one name work "
                        f"for all of them.")
            out = []
            _emit_section(out, mem, base, bank, gitems, end, title, note)
            files.setdefault(path, []).append("\n".join(out).rstrip() + "\n")

    for path, blocks in files.items():
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(_GENERATED_HDR + "\n" + "\n\n".join(blocks))

    includes = []
    for _ri, (_s, _e, _m, path) in enumerate(RAM_REGIONS):
        if path in files and f'INCLUDE "{path}"' not in includes:
            includes.append(f'INCLUDE "{path}"')
    Path("ram.asm").write_text(_GENERATED_HDR + "\n" + "\n".join(includes) + "\n")


def load_ram_map(path, unions_by_region=None, scoped=None, dis=None):
    """Map RAM addresses to names from ram_map.json (for operand rendering) and
    emit the RAM layout files (ram.asm + ram/*.asm). With `scoped` (its bank_at
    already filled in) and `dis`, banked-WRAM addresses no curated entry claims
    are additionally auto-named on `scoped` -- see auto_banked_wram_names."""
    if not Path(path).exists():
        return {}
    entries = json.loads(Path(path).read_text())
    names = {}
    regions = {}
    extents = []
    for addr_s, e in sorted(entries.items(), key=lambda kv: int(kv[0], 0)):
        name = e.get("name")
        if not name:
            continue
        addr = int(addr_s, 0)
        exp = region_prefix(addr)
        if exp and not (name.startswith(exp) and name[1:2].isupper()):
            print(f"warning: {path}: {addr_s} name {name!r} should be "
                  f"{exp}PascalCase", file=sys.stderr)
        names[addr] = name
        size = ram_field_size(e)
        extents.append((addr, size, name))
        for ri, (start, end, mem, _path) in enumerate(RAM_REGIONS):
            if start <= addr < end:
                key = BANK_KEY.get(mem)
                bank = int(e[key], 0) if key and key in e else None
                if key and bank is None:
                    print(f"warning: {path}: {addr_s} {name} is in banked "
                          f"{mem} but has no {key}", file=sys.stderr)
                regions.setdefault(ri, []).append(
                    (addr, name, size, e.get("note", ""), bank))
                break
        else:
            print(f"warning: {path}: {addr_s} outside known RAM regions",
                  file=sys.stderr)
    # A reference to an interior byte of a multi-byte variable (e.g. the low
    # byte of the 16-bit wCurrentMinigameStoryMatch) renders as `name + k`
    # rather than a raw address. An interior byte that is itself a named symbol
    # keeps its own name (the explicit entry, added above, is never overwritten).
    for base, size, name in extents:
        for k in range(1, size):
            names.setdefault(base + k, f"{name} + {k}")
    if dis is not None and scoped is not None:
        # A union's whole span is off limits, not just its named bytes: an
        # auto symbol inside one would have to be emitted inside the UNION
        # block, where it belongs to a single variant rather than all of them.
        # That only holds within the union's own WRAM bank, though -- another
        # bank's copy of the same addresses is a different SECTION.
        covered = set(names)
        covered_banks = {}
        for ulist in (unions_by_region or {}).values():
            for ustart, uend, _comment, variants, ubank in ulist:
                banks = union_banks(variants, ubank)
                if not banks:
                    covered.update(range(ustart, uend))
                    continue
                for a in range(ustart, uend):
                    covered_banks.setdefault(a, set()).update(banks)
        autos = auto_banked_wram_names(dis, scoped, covered, covered_banks)
        for addr, name, bank in autos:
            for ri, (rs, re_, _mem, _p) in enumerate(RAM_REGIONS):
                if rs <= addr < re_:
                    regions.setdefault(ri, []).append((addr, name, 1, "", bank))
                    break
        by_bank = {}
        for _addr, _name, bank in autos:
            by_bank[bank] = by_bank.get(bank, 0) + 1
        print(f"banked wram: {len(autos)} addresses auto-named w<bank>_<addr> "
              f"({', '.join(f'bank {b}: {n}' for b, n in sorted(by_bank.items()))})")
    write_ram_layout(regions, unions_by_region)
    return names
