"""Generated by tools/ap_export.py from the disassembly's archipelago branch; do not edit."""

BASEPATCH_ID = bytes.fromhex("9a710715")

# file offsets
rom_addresses = {
    "ApOptSkipIntro": 0x03fc8,
    "ApOptStoryArcs": 0x03fc9,
    "ApOptMinigames": 0x03fca,
    "ApOptRemoteItems": 0x03fcb,
    "ApOptGoal": 0x03fcc,
    "ApOptMatchSets": 0x03fcd,
    "ApOptMatchGames": 0x03fce,
    "ApOptSwingLow": 0x03fcf,
    "ApOptSwingHigh": 0x03fd0,
    "ApOptLocationCount": 0x03fd1,
    "ApBasepatchId": 0x03ff8,
    "ApCode": 0xb6000,
    "ApSlotAuth": 0xb6000,
    "ApStartInventory": 0xb6010,
}

# (memory domain, offset)
ram_addresses = {
}
