	farptr BeginCutsceneScriptMode ; $4000
	farptr EndCutsceneScriptMode ; $4002
	farptr WaitScriptFrames ; $4004
	farptr ScriptRespawnLocationActors ; $4006
	farptr ScriptShowSpeakerDialogue ; $4008
	farptr ScriptShowSpeakerDialogueRestoreBG ; $400a
	farptr ScriptCloseDialogueWindow ; $400c
	farptr InitDialogueTextCursor ; $400e
	farptr AdvanceDialogueTextCursor ; $4010
	farptr RunDialogueYesNoPrompt ; $4012
	farptr Unused_0a_ScriptSkipSpeakerDialogue ; $4014
	farptr GetActorStateAddr ; $4016
	farptr ScriptSetActorMoveSpeed ; $4018
	farptr ScriptSetActorScript ; $401a
	farptr SetActorNullScript ; $401c
	farptr WaitActorScriptDone ; $401e
	farptr ScriptWaitActorMoveDone ; $4020
	farptr ScriptSetActorPosition ; $4022
	farptr ScriptSetActorMoveTarget ; $4024
	farptr Unused_0a_MoveActorTowardPoint ; $4026
	farptr MoveActorByDelta ; $4028
	farptr MoveActorByAngle ; $402a
	farptr ScriptSetActorFacingLock ; $402c
	farptr SetActorFacing ; $402e
	farptr FaceActorTowardActor ; $4030
	farptr FaceActorsTowardEachOther ; $4032
	farptr ScriptSetActorAnimation ; $4034
	farptr ScriptWaitActorIdle ; $4036
	farptr SetPlayerMoveSpeed ; $4038
	farptr MovePlayerToPosition ; $403a
	farptr MovePlayerToActor ; $403c
	farptr WaitPlayerMoveDone ; $403e
	farptr SetScreenShake ; $4040
	farptr ScriptSetActorJumpVelocity ; $4042
	farptr ScriptWaitActorJumpDone ; $4044
	farptr RunMenuFromText ; $4046
	farptr SetActorActive ; $4048
	farptr InitStoryMatchSettings ; $404a
	farptr RunStoryMatch ; $404c
	farptr RestoreOverworldAfterMatch ; $404e
	farptr SetMatchDoublesMode ; $4050
	farptr Unused_0a_SetStoryMatchOpponent ; $4052
	farptr Unused_0a_SetCurrentlyUsedCourt ; $4054
	farptr Unused_0a_SetMatchNumberOfSets ; $4056
	farptr Unused_0a_SetMatchNumberOfGames ; $4058
	farptr LoadMatchSettingsFromTable ; $405a
	farptr RunStoryModeOverworld ; $405c
	farptr InitLocationActors ; $405e
	farptr WriteStoryStateWord ; $4060
	farptr SaveStoryReturnPoint ; $4062
	farptr RestoreStoryReturnPoint ; $4064
	farptr GetStoryLocationCount ; $4066
	farptr LoadStoryObjPalettes ; $4068
	farptr InitSceneScroll ; $406a
	farptr LoadStorySceneGraphics ; $406c
	farptr Unused_0a_CopySceneTilemapToVram ; $406e
	farptr UpdateSceneScroll ; $4070
	farptr Unused_0a_InitSceneViewer ; $4072
	farptr Unused_0a_RunSceneSelectDebugMenu ; $4074
	farptr CopyScrolledSceneTilemapToVram ; $4076
	farptr Unused_0a_LoadAndDisplayScene ; $4078
	farptr InitSceneTileAnimations ; $407a
	farptr StopSceneTileAnimations ; $407c
	farptr CopySceneTilemapRect ; $407e
	farptr CopyCollisionMapRect ; $4080
	farptr CopyBehaviorMapRect ; $4082
	farptr ReadCollisionMapCell ; $4084
	farptr ReadBehaviorMapCell ; $4086
	farptr Unused_0a_WriteCollisionMapCell ; $4088
	farptr WriteBehaviorMapCell ; $408a
	farptr LoadCourtSceneGraphics ; $408c
	farptr Unused_0a_UpdateSceneViewerScroll ; $408e
	farptr ShowLocationNamePopup ; $4090
	farptr Unused_0a_CopySceneTilemapChunk ; $4092
	farptr ClearStatusSetupMenuEntry ; $4094
	farptr InitMinigameTargets ; $4096
	farptr UpdateMinigameTargets ; $4098
	farptr SpawnMinigameTargetFormation ; $409a
	farptr DrawNumberWithSprites ; $409c
	farptr DeflectBallOffMinigameTarget ; $409e
	farptr StopSceneScrollTask ; $40a0
	farptr RunEndingCreditsSequence ; $40a2
