	farptr TryEstablishLink ; $4000
	farptr EnableSerialAndVBlankInterrupts ; $4002
	farptr RunLinkMatchFrameMaster ; $4004
	farptr RunLinkMatchFrameSlave ; $4006
	farptr ExchangeNibbleBlockMaster ; $4008
	farptr ExchangeNibbleBlockSlave ; $400a
	farptr SendNibbleBlockSlave ; $400c
	farptr ReceiveNibbleBlockMaster ; $400e
	farptr UnpackBytesToNibbles ; $4010
	farptr ExchangeLinkFrameByteMaster ; $4012
	farptr ExchangeLinkFrameByteSlave ; $4014
	farptr SyncLinkFrameMaster ; $4016
	farptr SyncLinkFrameSlave ; $4018
	farptr SyncLinkFrame ; $401a
	farptr RunLinkMatchFrame ; $401c
	farptr ExchangeLinkReadySignal ; $401e
	farptr RunLinkInputFrame ; $4020
	farptr UpdateLinkSession ; $4022
	farptr EndLinkSession ; $4024
	farptr ExchangeHandshakeBlockMaster ; $4026
	farptr ExchangeHandshakeBlockSlave ; $4028
	farptr ExchangeLinkBlockToWram5 ; $402a
	farptr PrimeSlaveSerialReply ; $402c
	farptr PrepareLinkStatePayload ; $402e
	farptr PrepareLinkInputPayload ; $4030
	farptr ResyncLinkSession ; $4032
	farptr ResyncLinkSessionWithTimer ; $4034
	farptr RunLinkCommandFrame ; $4036
	farptr ExchangeLinkDataBlock ; $4038
	farptr ComputeShotPlacement ; $403a
	farptr ExecuteShot ; $403c
	farptr ComputeShotTrajectory ; $403e
	farptr LookupCharSpriteSet ; $4040
	farptr SetupCharacterSprite ; $4042
	farptr LoadCharacterAttributes ; $4044
	farptr RunDebugTestMatch ; $4046
