"""Export the Archipelago base patch and the addresses the apworld needs.

Takes the built ROM, stamps the basepatch id into its fixed block (the first
4 bytes of a SHA-1 over the ROM with the block's id bytes zeroed), fixes the
global checksum, and writes into apworld/mario_tennis_gbc/:

  basepatch.bsdiff4  baserom.gbc -> the stamped ROM
  rom_addresses.py   BASEPATCH_ID; file offsets of every ROM `Ap*` symbol;
                     memory-domain offsets of every RAM `[swh]Ap*` symbol
  ids.py             the locations and items of include/constants/archipelago.inc

The stamped ROM is also left in build/ for playtesting."""
import argparse
import hashlib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
APWORLD = ROOT / "apworld" / "mario_tennis_gbc"
IDS_INC = ROOT / "include" / "constants" / "archipelago.inc"

ID_MAGIC = b"MTAP"
_SYM_RE = re.compile(r"^([0-9a-f]{2}):([0-9a-f]{4}) (\w+)$", re.I)
_ID_RE = re.compile(r'^\tap_(location|item) (\w+), "([^"]+)"', re.M)


def read_syms(path):
    out = {}
    for line in Path(path).read_text().splitlines():
        m = _SYM_RE.match(line)
        if m:
            out[m.group(3)] = (int(m.group(1), 16), int(m.group(2), 16))
    return out


def rom_offset(bank, addr):
    return addr if addr < 0x4000 else bank * 0x4000 + addr - 0x4000


def ram_domain(bank, addr):
    """(BizHawk Gambatte memory domain, offset) of a RAM address."""
    if 0xa000 <= addr < 0xc000:
        return "CartRAM", bank * 0x2000 + addr - 0xa000
    if 0xc000 <= addr < 0xd000:
        return "WRAM", addr - 0xc000
    if 0xd000 <= addr < 0xe000:
        return "WRAM", max(bank, 1) * 0x1000 + addr - 0xd000
    if 0xff80 <= addr < 0xffff:
        return "HRAM", addr - 0xff80
    raise ValueError(f"{bank:02x}:{addr:04x} is not RAM")


def global_checksum(rom):
    return (sum(rom) - rom[0x14e] - rom[0x14f]) & 0xffff


def stamp(rom, id_offset):
    if rom[id_offset:id_offset + 4] != ID_MAGIC:
        sys.exit(f"no {ID_MAGIC!r} at ${id_offset:04x}")
    rom[id_offset + 4:id_offset + 8] = bytes(4)
    ident = hashlib.sha1(rom).digest()[:4]
    rom[id_offset + 4:id_offset + 8] = ident
    rom[0x14e:0x150] = global_checksum(rom).to_bytes(2, "big")
    return ident


def read_ids():
    locations, items = [], []
    for kind, const, name in _ID_RE.findall(IDS_INC.read_text()):
        if kind == "location":
            locations.append((len(locations) + 1, const, name))
        else:
            items.append((len(items) + 1, const, name))
    return locations, items


def write_rom_addresses(path, ident, syms):
    rom = {n: rom_offset(b, a) for n, (b, a) in syms.items() if re.match(r"Ap[A-Z]", n) and a < 0x8000}
    ram = {n: ram_domain(b, a) for n, (b, a) in syms.items()
           if re.match(r"[swh]Ap[A-Z]", n) and a >= 0xa000}
    lines = ['"""Generated by tools/ap_export.py from the disassembly\'s archipelago branch; do not edit."""',
             "", f"BASEPATCH_ID = bytes.fromhex(\"{ident.hex()}\")", "",
             "# file offsets", "rom_addresses = {"]
    lines += [f'    "{n}": 0x{o:05x},' for n, o in sorted(rom.items(), key=lambda kv: (kv[1], kv[0]))]
    lines += ["}", "", "# (memory domain, offset)", "ram_addresses = {"]
    lines += [f'    "{n}": ("{d}", 0x{o:04x}),' for n, (d, o) in sorted(ram.items(), key=lambda kv: (kv[1], kv[0]))]
    lines += ["}", ""]
    path.write_text("\n".join(lines))


def write_ids(path, locations, items):
    lines = ['"""Generated by tools/ap_export.py from include/constants/archipelago.inc; do not edit."""', "",
             "# (Archipelago id, game constant, name); a location's done bit is its id - 1",
             "LOCATIONS = ["]
    lines += [f'    ({i}, "{c}", "{n}"),' for i, c, n in locations]
    lines += ["]", "", "# (Archipelago id = ledger counter, game constant, name)", "ITEMS = ["]
    lines += [f'    ({i}, "{c}", "{n}"),' for i, c, n in items]
    lines += ["]", ""]
    path.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--rom", default=ROOT / "mariotennis.gbc", type=Path)
    ap.add_argument("--sym", default=ROOT / "build" / "mariotennis.sym", type=Path)
    ap.add_argument("--base", default=ROOT / "baserom.gbc", type=Path)
    ap.add_argument("--out", default=APWORLD, type=Path)
    args = ap.parse_args()
    import bsdiff4

    syms = read_syms(args.sym)
    rom = bytearray(args.rom.read_bytes())
    ident = stamp(rom, rom_offset(*syms["ApBasepatchId"]))
    (ROOT / "build" / "mariotennis-ap.gbc").write_bytes(rom)

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "basepatch.bsdiff4").write_bytes(bsdiff4.diff(args.base.read_bytes(), bytes(rom)))
    write_rom_addresses(args.out / "rom_addresses.py", ident, syms)
    locations, items = read_ids()
    write_ids(args.out / "ids.py", locations, items)
    print(f"basepatch id {ident.hex()}: {len(locations)} locations, {len(items)} items -> {args.out}")


if __name__ == "__main__":
    main()
