SECTION "ROM Bank $6b", ROMX[$4000], BANK[$6b]

; <Label>_SIZE: decoded length of each tile block this bank copies whole through
; LoadCompressedTileBlock (each .inc is generated from its .bin by make)
	INCLUDE "data/bank_06c/lz_CutsceneGfx0.inc"
	INCLUDE "data/bank_06c/lz_CutsceneGfx1.inc"
	INCLUDE "data/bank_06c/lz_CutsceneGfx2.inc"
	INCLUDE "data/bank_06c/lz_CutsceneGfx3.inc"
	INCLUDE "data/bank_06c/lz_CutsceneGfx4.inc"
	INCLUDE "data/bank_06c/lz_CutsceneGfx5.inc"
	INCLUDE "data/bank_06c/lz_CutsceneGfx6.inc"
	INCLUDE "data/bank_06c/lz_IntroGfx0.inc"
	INCLUDE "data/bank_06c/lz_IntroGfx1.inc"
	INCLUDE "data/bank_06c/lz_IntroGfx2.inc"
	INCLUDE "data/bank_06c/lz_IntroGfx3.inc"
	INCLUDE "data/bank_06c/lz_IntroGfx4.inc"
	INCLUDE "data/bank_06c/lz_IntroGfx5.inc"
	INCLUDE "data/bank_06d/lz_TitleGfx0.inc"
	INCLUDE "data/bank_06d/lz_TitleGfx1.inc"
	INCLUDE "data/bank_06d/lz_TitleGfx2.inc"
	INCLUDE "data/bank_06d/lz_TitleGfx3.inc"
	INCLUDE "data/bank_06d/lz_TitleGfx4.inc"
	INCLUDE "data/bank_06d/lz_TitleGfx5.inc"
	INCLUDE "data/bank_06d/lz_TitleGfx6.inc"
	INCLUDE "data/bank_06d/lz_TitleGfx7.inc"

INCLUDE "src/engine/cutscenes/slots_6b.asm"
INCLUDE "src/engine/cutscenes/intro_6b.asm"
INCLUDE "src/engine/cutscenes/intro2_6b.asm"
INCLUDE "src/engine/cutscenes/intro3_6b.asm"
INCLUDE "src/engine/cutscenes/title_6b.asm"
