SECTION "ROM Bank $00", ROM0[$0000]

INCLUDE "src/home/joypad_00.asm"
INCLUDE "src/home/memory_00.asm"
INCLUDE "src/home/indexed_00.asm"
INCLUDE "src/home/mul_00.asm"
INCLUDE "src/home/mul2_00.asm"
INCLUDE "src/home/div_00.asm"
INCLUDE "src/home/mul3_00.asm"
INCLUDE "src/home/tangent_00.asm"
INCLUDE "src/home/hex_00.asm"
INCLUDE "src/home/adjust_00.asm"
INCLUDE "src/home/sprite_00.asm"
INCLUDE "src/home/number_00.asm"
INCLUDE "src/home/game_00.asm"
INCLUDE "src/home/serial_00.asm"
INCLUDE "src/home/window_00.asm"
INCLUDE "src/home/mul4_00.asm"
INCLUDE "src/audio/sound_00.asm"
INCLUDE "src/home/channel_00.asm"
INCLUDE "src/audio/sound2_00.asm"
