SECTION "ROM Bank $08", ROMX[$4000], BANK[$08]

INCLUDE "src/engine/match/slots_08.asm"
INCLUDE "src/engine/match/match_08.asm"
INCLUDE "src/engine/match/ball_08.asm"
INCLUDE "src/engine/match/char_08.asm"
INCLUDE "src/engine/match/point_08.asm"
INCLUDE "src/engine/match/ball2_08.asm"
INCLUDE "src/engine/match/ball3_08.asm"
INCLUDE "src/engine/match/project_08.asm"
INCLUDE "src/engine/match/court_08.asm"
INCLUDE "src/engine/match/char2_08.asm"
INCLUDE "src/engine/match/minigame_08.asm"
INCLUDE "src/engine/match/char3_08.asm"
INCLUDE "src/engine/match/char4_08.asm"
INCLUDE "src/engine/match/ball4_08.asm"
INCLUDE "src/engine/match/char5_08.asm"
INCLUDE "src/engine/match/char6_08.asm"
INCLUDE "src/engine/match/ai_08.asm"
INCLUDE "src/engine/match/ai2_08.asm"
