SECTION "ROM Bank $0a", ROMX[$4000], BANK[$0a]

INCLUDE "src/engine/story/slots_0a.asm"
INCLUDE "src/engine/story/script_0a.asm"
INCLUDE "src/engine/story/actor_0a.asm"
INCLUDE "src/engine/story/actor2_0a.asm"
INCLUDE "src/engine/story/match_0a.asm"
INCLUDE "src/engine/story/story_0a.asm"
INCLUDE "src/engine/story/story2_0a.asm"
INCLUDE "src/engine/story/scene_0a.asm"
INCLUDE "src/engine/story/scene2_0a.asm"
INCLUDE "src/engine/story/scene3_0a.asm"
INCLUDE "src/engine/story/scene4_0a.asm"
INCLUDE "src/engine/story/minigame_0a.asm"
INCLUDE "src/engine/story/credits_0a.asm"
