SECTION "ROM Bank $3b", ROMX[$4000], BANK[$3b]

; The name of each shared-template copy in this bank, for the templates
; that call one another (src/twins): a copy nothing reaches is Unused_<bank>_...
DEF DrawAsciiDigitChar_3b_NAME EQUS "Unused_3b_DrawAsciiDigitChar"
DEF DrawCornerBrackets_3b_NAME EQUS "Unused_3b_DrawCornerBrackets"

; <Label>_SIZE: decoded length of each tile block this bank copies whole through
; LoadCompressedTileBlock (each .inc is generated from its .bin by make)
	INCLUDE "data/bank_03c/lz_EraseSavedDataGfx0.inc"
	INCLUDE "data/bank_03c/lz_EraseSavedDataGfx1.inc"
	INCLUDE "data/bank_03c/lz_EraseSavedDataGfx2.inc"
	INCLUDE "data/bank_03c/lz_EraseSavedDataGfx3.inc"
	INCLUDE "data/bank_03c/lz_EraseSavedDataGfx4.inc"
	INCLUDE "data/bank_03c/lz_MainMenuGfx0.inc"
	INCLUDE "data/bank_03c/lz_MainMenuGfx1.inc"
	INCLUDE "data/bank_03c/lz_MainMenuGfx2.inc"
	INCLUDE "data/bank_03c/lz_MainMenuGfx3.inc"
	INCLUDE "data/bank_03c/lz_MainMenuGfx4.inc"
	INCLUDE "data/bank_03c/lz_MinigameSelectGfx0.inc"
	INCLUDE "data/bank_03c/lz_MinigameSelectGfx1.inc"
	INCLUDE "data/bank_03c/lz_MinigameSelectGfx2.inc"
	INCLUDE "data/bank_03c/lz_MinigameSelectGfx3.inc"
	INCLUDE "data/bank_03c/lz_MinigameSelectGfx4.inc"
	INCLUDE "data/bank_03c/lz_MinigameSelectGfx5.inc"
	INCLUDE "data/bank_03c/lz_N64RecordTypeGfx0.inc"
	INCLUDE "data/bank_03c/lz_N64RecordTypeGfx1.inc"
	INCLUDE "data/bank_03c/lz_SavedDataSourceGfx0.inc"
	INCLUDE "data/bank_03c/lz_SavedDataSourceGfx1.inc"
	INCLUDE "data/bank_03c/lz_SavedDataSourceGfx2.inc"
	INCLUDE "data/bank_03c/lz_SavedDataSourceGfx3.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx27.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx29.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx30.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx35.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx36.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx37.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx38.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx39.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx40.inc"
	INCLUDE "data/bank_03c/lz_SharedMenuGfx41.inc"
	INCLUDE "data/bank_03d/lz_MainMenuGfx5.inc"
	INCLUDE "data/bank_03d/lz_MinigameSelectGfx6.inc"
	INCLUDE "data/bank_03d/lz_N64RecordTypeGfx2.inc"
	INCLUDE "data/bank_03d/lz_N64TransferItemGfx0.inc"
	INCLUDE "data/bank_03d/lz_N64TransferItemGfx1.inc"
	INCLUDE "data/bank_03d/lz_N64TransferItemGfx2.inc"
	INCLUDE "data/bank_03d/lz_N64TransferItemGfx3.inc"
	INCLUDE "data/bank_03d/lz_SavedDataSourceGfx4.inc"
	INCLUDE "data/bank_03d/lz_SharedMenuGfx63.inc"
	INCLUDE "data/bank_03d/lz_SharedMenuGfx65.inc"
	INCLUDE "data/bank_03e/lz_N64TransferItemGfx4.inc"
	INCLUDE "data/bank_03e/lz_SavedDataSourceGfx5.inc"
	INCLUDE "data/bank_03f/lz_TournamentBracketGfx.inc"

INCLUDE "src/engine/menus/slots_3b.asm"
INCLUDE "src/engine/menus/menu_3b.asm"
INCLUDE "src/engine/menus/n64_3b.asm"
INCLUDE "src/engine/menus/n64exhib_3b.asm"
INCLUDE "src/engine/menus/n64trophies_3b.asm"
INCLUDE "src/engine/menus/n64tnmt_3b.asm"
INCLUDE "src/engine/menus/ring_3b.asm"
INCLUDE "src/engine/menus/menu2_3b.asm"
INCLUDE "src/engine/menus/saveslots_3b.asm"
INCLUDE "src/engine/menus/minigame_3b.asm"
INCLUDE "src/engine/menus/saved_3b.asm"
INCLUDE "src/engine/menus/erase_3b.asm"
INCLUDE "src/engine/menus/n64transfer_3b.asm"
INCLUDE "src/engine/menus/bracket_3b.asm"
INCLUDE "src/engine/menus/victory_3b.asm"
