SECTION "ROM Bank $05", ROMX[$4000], BANK[$05]

INCLUDE "src/engine/text/slots_05.asm"
INCLUDE "src/engine/text/window_05.asm"
INCLUDE "src/engine/text/shadow_05.asm"
INCLUDE "src/engine/text/window2_05.asm"
INCLUDE "src/engine/text/paged_05.asm"
INCLUDE "src/engine/text/cursor_05.asm"
INCLUDE "src/engine/text/arg_05.asm"
INCLUDE "src/engine/text/control_05.asm"
INCLUDE "src/engine/text/window3_05.asm"
INCLUDE "src/engine/text/dialogue_05.asm"
INCLUDE "src/engine/text/proportional_05.asm"
INCLUDE "src/engine/text/window4_05.asm"
INCLUDE "src/engine/text/debug_05.asm"
INCLUDE "src/engine/text/debug2_05.asm"
INCLUDE "src/engine/text/window5_05.asm"
INCLUDE "src/engine/text/rows_05.asm"
INCLUDE "src/engine/text/glyph_05.asm"
INCLUDE "src/engine/text/glyph2_05.asm"
