SECTION "ROM Bank $00", ROM0[$0000]

INCLUDE "src/home/vectors_00.asm"
INCLUDE "src/home/memory_00.asm"
INCLUDE "src/home/palettes_00.asm"
INCLUDE "src/home/mul_00.asm"
INCLUDE "src/home/sine_00.asm"
INCLUDE "src/home/div_00.asm"
INCLUDE "src/home/trig_00.asm"
INCLUDE "src/home/decompress_00.asm"
INCLUDE "src/home/debugtext_00.asm"
INCLUDE "src/home/colorfade_00.asm"
INCLUDE "src/home/fade_00.asm"
INCLUDE "src/home/numberfont_00.asm"
INCLUDE "src/home/flags_00.asm"
INCLUDE "src/home/vblank_00.asm"
INCLUDE "src/home/timer_00.asm"
INCLUDE "src/home/view_00.asm"
INCLUDE "src/audio/sound_00.asm"
INCLUDE "src/audio/note_00.asm"
INCLUDE "src/audio/tables_00.asm"
