name: Release APWorld
on:
  push:
    tags:
      - 'apworld-v*'

jobs:
  release:
    permissions:
      contents: write
    uses: Eijebong/ap-actions/.github/workflows/release-apworld.yml@7f1641d73c59edfbcbb564c9c0f24fd59033cbd8 # main as of 2026-10-05
    with:
      apworld-path: apworld/mario_tennis_gbc
      ap-version: '0.6.8'
      python-version: '3.13'
      prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
