name: Fuzz APWorld
on:
  push:
    branches: [ archipelago ]
    paths: [ "apworld/**", ".github/workflows/apworld-*.yml" ]
  pull_request:
    branches: [ archipelago ]
    paths: [ "apworld/**", ".github/workflows/apworld-*.yml" ]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/fuzz@7f1641d73c59edfbcbb564c9c0f24fd59033cbd8 # main as of 2026-10-05
        with:
          apworld-path: apworld/mario_tennis_gbc
          ap-version: '0.6.8'
          python-version: '3.13'
          # the action's default fuzzer predates Generate.py's allow_quantity (0.6.8)
          fuzzer-commit: 53686ba34f9e8852cbe1970666a5f56fd6abf75a
